### ISSUE TITLE
表示感谢，终于有大佬接手了

### ISSUE THREAD

**Issue by kofzhanganguo** [sqzw-x/mdcx#1]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

正常刮削，无问题，过来感谢一下。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
大佬算不上，尽力而为吧

**Comment by xmasrain** [comment]
感谢
