### ISSUE TITLE
curl errcode 77

### ISSUE THREAD

**Issue by dandannnn** [sqzw-x/mdcx#100]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

因JAVDB有识别到更多演员以及剧照，需要用到
0207和最新版本0220在JAVDB上搜刮没刮到真实地址，报错Error: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile，证书在windows11查看有，以及权限设置为everyone。均无法访问到。
发现0220版本获取JAVDB的cookie检查报错，而使用同一配置文件的0207检查cookie正常，有可能curl版本升级的bug?

以下是部分提示：
🙈 [Movie] E:\Downloads\0\fc2\failed\failed\FC2-PPV-3148438.mp4
 🚘 [Number] FC2-3148438
    🌐 javdb (⏱ 8S)
       搜索地址: https://javdb524.com/search?q=FC2-3148438&locale=zh 
       请求错误: https://javdb524.com/search?q=FC2-3148438&locale=zh
Error: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\郭耀华\AppData\Local\Temp\_MEI233722\certifi\cacert.pem CApath: none'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 
    🌐 fc2
       番号地址: https://adult.contents.fc2.com/article/3148438/
       数据获取失败: 未获取到cover！ 
    🌐 fc2club
       番号地址: https://fc2club.top/html/FC2-3148438.html 
       数据获取失败: 未获取到title！ 
    🌐 fc2hub
       搜索地址: https://fc2hub.com/search?kw=3148438 
       番号地址: http://fc2hub.com/video/1664240/id3148438/028_%E3%80%90%E6%80%A7%E6%AC%B2%E3%83%A2%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%BC%E3%80%91%E6%9C%AC%E9%A0%98%E7%99%BA%E6%8F%AE%EF%BC%81%E6%92%AE%E5%BD%B1%E7%9B%B4%E5%BE%8C%E3%81%AB%E3%82%AB%E3%83%A1%E3%83%A9%E3%83%9E%E3%83%B3%E8%AA%98%E6%83%91%E3%81%97%E3%81%A6%E3%82%82%E3%81%86%E4%B8%80%E6%88%A6%EF%BC%81%EF%BC%81%E5%BE%A9%E5%B8%B0%E3%81%97%E3%81%A6%E3%81%84%E3%81%8D%E3%81%AA%E3%82%8A%E5%A4%A7%E6%9A%B4%E8%B5%B0%EF%BC%81%E3%80%8C%E5%94%AF%E5%A5%88%E3%82%92%E6%BA%80%E8%B6%B3%E3%81%95%E3%81%9B%E3%81%A6%E3%81%8F%E3%82%8C%E3%82%8B%E3%82%93%E3%81%A7%E3%81%99%E3%82%88%E3%81%AD%EF%BC%9F%EF%BC%81%E3%80%8D%E3%81%BD%E3%81%A3%E3%81%A1%E3%82%83%E3%82%8A%E7%88%86%E4%B9%B3K%E3%82%AB%E3%83%83%E3%83%97%E5%94%AF%E5%A5%88%E3%81%A1%E3%82%83%E3%82%932nd%E7%AC%AC2%E7%AB%A0%E3%80%90%E6%B5%B7%E5%A4%96%E7%89%88%E3%80%91 
       数据获取成功！
    🟢 标题 获取成功！(fc2hub)
     ↳ 028_【性欲モンスター】本領発揮！撮影直後にカメラマン誘惑してもう一戦！！復帰していきなり大暴走！「唯奈を満足させてくれるんですよね？！」ぽっちゃり爆乳Kカップ唯奈ちゃん2nd第2章【海外版】 

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
#63 
检查 cookie 原本不是用的 curl，现在换成了 curl
你可以尝试 0207 刮削 db，应该会报同样错误

**Comment by dandannnn** [comment]
是的， 0207 刮削 db同样的报错。

**Comment by sqzw-x** [comment]
https://github.com/sqzw-x/mdcx/issues/63#issuecomment-1913036428

**Comment by dandannnn** [comment]
确实是中文导致出错，cookie无识别到也是。解决方法使用管理员账号重命名为英文，以及修改注册表的profilelist指向的用户文件夹注销，重新搜刮成功
