### ISSUE TITLE
如何直接重命名文件夹

### ISSUE THREAD

**Issue by MarkMoXs** [sqzw-x/mdcx#101]
在提问之前...
 我已经搜索了现有的 issues
 我在提问题之前至少花费了 5 分钟来思考和准备
 我正在使用最新版本
描述你的问题
只想重命名文件夹，而不需要刮削成功后移动文件，目前只看到更新模式的，更新B和C有类似功能，但是选择更新B和C后，B目录还是重新建了一个文件夹，而不只是直接重命名原文件夹，而不需要新建一个。虽然可以选择刮削结束后删除空文件夹，但有时候难免B目录下有没有番号的文件，而导致软件不会把它一起移动新建的文件夹，也就不是空目录它也不会删除。

如何复现
No response

预期行为
只是单纯的想直接重命名原文件夹，而不需要单独新建一个。

相关 Logs

截图
No response

还有别的吗？
No response

**Comment by yusilong** [comment]
更新后的文件夹和原始文件夹是一个的时候，就会只重命名文件夹吧

**Comment by sqzw-x** [comment]
重命名文件夹只能处理输出路径和视频目录在同一级的情况，而大部分情况下这两个未必相同
视频文件夹内的其他文件可以用文件清理功能删除。
另见 #11

**Comment by MarkMoXs** [comment]
假如需要刮削的以前其它刮削器刮削过的，文件又有一定数量，如有遇到演员较多的时候，又有上面的情况，是一件很头疼的事儿，因为一旦命名规则不同，就会出现这种情况，因为本刮削器分割演员用了,号，而以前刮削过的有可能是空格或其它符号，需要的不是清理文件，现在只能手动在万花丛中去找出来，移过去在删除以前的文件夹或文件。第一次整理起来会非常的头疼，要是能直接重命名原文件夹就好，还是非常感谢您的维护。
