### ISSUE TITLE
群晖 Video Station vsmeta 格式支持

### ISSUE THREAD

**Issue by 1525745393** [sqzw-x/mdcx#103]
能不能添加一个功能：刮削到的nfo元数据，转换成群晖Video Station专用vsmeta元数据。共享刮削数据

**Comment by 1525745393** [comment]
可以参考一下这个项目https://github.com/JuanWoo/nfo-to-vsmeta 项目不完善 封面和背景图无法写入vsmeta

**Comment by sqzw-x** [comment]
我看了一下，vsmeta 是 vs 的内部格式，而且是二进制文件，群晖官方并未给出此格式的规范，所以只能通过逆向分析。
我并不准备支持这类内部格式，因为厂商完全可以在不通告第三方的情况下任意修改此类格式的规范，届时还要重新适配，而我并不是群晖用户。
支持此类格式的最佳方案是由 Video Station 用户社区维护相关项目，不过相关社区似乎并不很活跃

**Comment by 1525745393** [comment]
好的 谢谢
