### ISSUE TITLE
优先通过Prestige刮取演员信息造成的错误

### ISSUE THREAD

**Issue by kiworets** [sqzw-x/mdcx#104]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

在刮削网站里我没有写prestige，我发现这个问题后甚至还写进了排除项，但程序还会第一优先使用prestige刮削演员信息（如附图），导致刮出诸如“OL4名”、“素人3名”这种错误信息

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![屏幕截图 2024-02-25 170015](https://github.com/sqzw-x/mdcx/assets/159447343/78596396-273a-4cde-9582-1d2cba4e486c)

**Comment by sqzw-x** [comment]
查看是否勾选了 `优先使用片商官网`

**Comment by kiworets** [comment]
> 查看是否勾选了 `优先使用片商官网`

哇 正是如此 解决了 感谢！
