### ISSUE TITLE
重启软件后，网址设置中第一个“7mmtv”会丢失配置

### ISSUE THREAD

**Issue by rosspsp** [sqzw-x/mdcx#106]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

自定义好“7mmtv”的网址后，关闭重启软件，网址会丢失，如下图
<img width="735" alt="iShot_2024-02-27_00 04 39" src="https://github.com/sqzw-x/mdcx/assets/73610222/8c8e66c1-31f4-46f3-b7f2-ad512c7f598e">

**Comment by sqzw-x** [comment]
实际上应该是生效了的，你可以切到其它网站再切回来，就会显示出来。
另外也可以执行网络检测，会打印所有自定义网址

**Comment by rosspsp** [comment]
> 实际上应该是生效了的，你可以切到其它网站再切回来，就会显示出来。 另外也可以执行网络检测，会打印所有自定义网址

没有生效，这是我网络检测后的截图：

设置7mmtv之后重启，进行网络检测，没有显示7mmtv的自定义网址，并且卡在xcity之后不再继续，下一个就应该是7mmtv了
![Uploading iShot_2024-02-28_01.26.04.png…]()


设置7mmtv值后进行网络检测，正常显示7mmtv的自定义网址，且可以顺利进行网络检测，没有卡住
![Uploading iShot_2024-02-28_01.31.19.png…]()

**Comment by rosspsp** [comment]
> 实际上应该是生效了的，你可以切到其它网站再切回来，就会显示出来。 另外也可以执行网络检测，会打印所有自定义网址

没有生效，这是我网络检测后的截图：

设置7mmtv之后重启，进行网络检测，没有显示7mmtv的自定义网址，并且卡在xcity之后不再继续，下一个就应该是7mmtv了
![Uploading iShot_2024-02-28_01.26.04.png…]()

设置7mmtv值后进行网络检测，正常显示7mmtv的自定义网址，且可以顺利进行网络检测，没有卡住
![Uploading iShot_2024-02-28_01.31.19.png…]()

对了，我用的mac arm版本的，最新本

**Comment by sqzw-x** [comment]
配置项是否正确写入? 检查保存后 `config.ini` 中是否出现 `7mmtv_website` 这项

**Comment by rosspsp** [comment]
> 7mmtv_website

config.ini中有7mmtv_website这一项，但是重启之后确实读不出来，网络检测也会卡在7mmtv_website这一项。。。

**Comment by sqzw-x** [comment]
@northsea4 你能否在 macos/arm 平台复现此问题? 

考虑到保存
https://github.com/sqzw-x/mdcx/blob/99f7174abd4f1d1f88d0962490946ae801df1f4f/src/models/config/config.py#L91
与读取
https://github.com/sqzw-x/mdcx/blob/99f7174abd4f1d1f88d0962490946ae801df1f4f/src/models/config/config.py#L81
https://github.com/sqzw-x/mdcx/blob/eb8207b5b96e0758a902f0bd8a0130a72960f533/src/controllers/main_window/main_window.py#L1950
的逻辑一致, 能正常保存却不能正常读取是不寻常的

**Comment by rosspsp** [comment]
可以复现，每次重启软件都得重新设置7mmtv的网址。。。发自我的手机-------- 原始邮件 --------发件人： sqzw-x ***@***.***>日期： 2024年3月2日周六 下午3:42收件人： sqzw-x/mdcx ***@***.***>抄送： rosspsp ***@***.***>, Author ***@***.***>主    题： Re: [sqzw-x/mdcx] 重启软件后，网址设置中第一个“7mmtv”会丢失配置 (Issue #106)
@northsea4 你能否在 macos/arm 平台复现此问题?
考虑到保存
https://github.com/sqzw-x/mdcx/blob/99f7174abd4f1d1f88d0962490946ae801df1f4f/src/models/config/config.py#L91
与读取
https://github.com/sqzw-x/mdcx/blob/99f7174abd4f1d1f88d0962490946ae801df1f4f/src/models/config/config.py#L81
https://github.com/sqzw-x/mdcx/blob/eb8207b5b96e0758a902f0bd8a0130a72960f533/src/controllers/main_window/main_window.py#L1950
的逻辑一致, 能正常保存却不能正常读取是不寻常的

**Comment by sqzw-x** [comment]
1. 设置 7mmtv 自定义网址
2. 关闭程序，检查配置文件中是否有 `7mmtv_website`, 其值是否正确
3. 再次打开程序, 问题发生, 此时再次检查配置文件
4. 设置页点击 `保存`, 再次检查配置文件

**Comment by rosspsp** [comment]
> 1. 设置 7mmtv 自定义网址
> 2. 关闭程序，检查配置文件中是否有 `7mmtv_website`, 其值是否正确
> 3. 再次打开程序, 问题发生, 此时再次检查配置文件
> 4. 设置页点击 `保存`, 再次检查配置文件
> 5. 关闭程序, 最后一次检查配置文件



> > > 7mmtv_website
> > 
> > 
> > config.ini中有7mmtv_website这一项，但是重启之后确实读不出来，网络检测也会卡在7mmtv_website这一项。。。
> 
> 那重启之后，config.ini中是否还有`7mmtv_website`这一项，有的话它的值是不是你自定义那个？

经过测试，[MDCx-120240308-macos-aarch64]这一版程序已修复这个问题
