### ISSUE TITLE
同视频不同版本，第二个版本刮削时下载图片失败

### ISSUE THREAD

**Issue by rosspsp** [sqzw-x/mdcx#107]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

视频文件：4k版本的“STARS-968.mp4”和破解字幕版本的“STARS-968-U-C”
仅刮削两个中的任何一个文件都没问题；如两个都刮削，第一个刮削的没有问题，第二个就会下载图片失败
配置文件如下，可以复现

**Comment by sqzw-x** [comment]
这是因为你的命名规则会将两个文件放到同一目录下，而其 number 相同，图片重名，所以创建失败

**Comment by sqzw-x** [comment]
我使用此配置文件无法复现
![image](https://github.com/sqzw-x/mdcx/assets/150016653/9c36d34f-999d-4beb-b87c-ee448465d946)
我注意到你的图片m'm'g命名规则是 文件名-fanart.jpg 那么理论上不应该出现命名冲突

**Comment by rosspsp** [comment]
> 我使用此配置文件无法复现 ![image](https://private-user-images.githubusercontent.com/150016653/308095448-9c36d34f-999d-4beb-b87c-ee448465d946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjAwNDUsIm5iZiI6MTcwOTIxOTc0NSwicGF0aCI6Ii8xNTAwMTY2NTMvMzA4MDk1NDQ4LTljMzZkMzRmLTk5OWQtNGJlYi1iODdjLWVlNDQ4NDY1ZDk0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQxNTE1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWVjZWYxYjc5ZjkwNjBkNWZkZDQ4N2FkYWJkNWY4NjEwOWM2MDdlNGVmYThkZDMzNWM5MDQ1M2NiYzQ3NjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2cnhTs1W8-tY1vANvxSk0ZV8hNN9FtKhliCb8HXWtxY) 我注意到你的图片命名规则是 `文件名-fanart.jpg` 那么理论上不应该出现命名冲突

你这里有个问题，你的“STARS-968.mp4”分辨率不是4k的，刮削的时候要检测分辨率，会添加“-4K”，变成“STARS-968-4K.mp4”，不知道是不是跟这个有关系。另外我用的是mac arm版本的，120240220

**Comment by sqzw-x** [comment]
有4K后缀更不可能出现命名冲突，你的图片命名规则是否确实是 `文件名-fanart.jpg` ?
如果排查命名冲突, 那考虑写入权限的问题，nfo 能否创建成功？或者尝试使用 root 权限运行

**Comment by rosspsp** [comment]
> 有4K后缀更不可能出现命名冲突，你的图片命名规则是否确实是 `文件名-fanart.jpg` ? 如果排除命名冲突, 那考虑写入权限的问题，nfo 能否创建成功？或者尝试使用 root 权限运行

好的，我再尝试一下吧
