### ISSUE TITLE
想通影音文件迭代替换的问题

### ISSUE THREAD

**Issue by war-SONG47** [sqzw-x/mdcx#109]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

作者大大，作为剧情爱好者和仓鼠症，影音有字幕会极大的体验观赏性，在使用了一段刮削后，发现软件没有对同番号，不同后缀的文件的更新功能。如：XXXX-152在已刮削的情况下，如果再次下载XXXX-152-C的文件后，再刮削会导致同名文件多个内容，导致空间的极大浪费，一般的后缀如：-C,-CH,-UN,-UC,-4K,能否在设置选项中增加此功能来对文件进行更新，如-C，-CH代替普通文件；-UC代替-C,-CH或者普通文件；-4K选择保留

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

增加新功能

**Comment by sqzw-x** [comment]
很多用户会保存同一个影片的不同版本，而且不同版本之间的替代性并不明显，比如无码破解能否作为有码4k的上位？这些都因人而异。
此外直接删除已刮削的视频文件是高风险行为，假如出现 bug 可能导致数据丢失，不会引入这类操作的

**Comment by war-SONG47** [comment]
那是否可以增加一个字幕版本的选项，您说的UC和4K和原版视频确实有喜欢多版本的，但是能否有一个选项对文件的后缀进行替代呢?如-C/-CH/UC 会替代已刮削文件夹内无后缀文件，并重新刮削；-UN/-4K和原版保持？

**Comment by sqzw-x** [comment]
这个功能还算合理, 但是 mdcx 的文件移动逻辑比较混乱, 刮削后处理部分相当复杂, 我并没有把握在不破坏原有功能的情况下加入此功能
