### ISSUE TITLE
工具中软链接助手的问题

### ISSUE THREAD

**Issue by tramp201** [sqzw-x/mdcx#11]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [ ] 我正在使用最新版本

### 描述你的问题

在使用工具中软链接助手的过程中，勾选同时复制网盘目录的nfo、图片、字幕文件到软链接目录后，.jpeg、.webp格式的会被忽略，不会建立软链接，请考虑添加或者增加图片格式选项。

### 预期行为

希望在勾选同时复制网盘目录的nfo、图片、字幕文件到软链接目录后，各种格式图片都会被创建软链接。

### 还有别的吗？

1

**Comment by sqzw-x** [comment]
这些图片是手工加入的吗，mdcx 刮削只会生成 jpg 格式

**Comment by sqzw-x** [comment]
> > 这些图片是手工加入的吗，mdcx 刮削只会生成 jpg 格式
> 
> 不一定是mdcx刮削的文件，比如一些挂载网盘的用户也有创建软链接的需求

那么 mdcx 不保证这些文件的处理，用户自己加入文件的类型无法预测
