### ISSUE TITLE
希望能扩展web版

### ISSUE THREAD

**Issue by KleinerSource** [sqzw-x/mdcx#111]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

现在有NAS的用户也挺多的了
希望能有web版本.
这样就不需要开PC去处理刮削问题了.

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

`

**Comment by sqzw-x** [comment]
NAS 可以使用 docker 版本，社区有用户维护。
以原项目的架构，想原生支持 web 基本不可能了
