### ISSUE TITLE
能否增加其他的欧美刮削

### ISSUE THREAD

**Issue by 1015156857** [sqzw-x/mdcx#113]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

THEPRONDB已经关闭了，目前欧美刮削很多资源缺少，比如法国公司啄木鸟系列，缺少的很多，能否增加一些欧美的刮削，例如www.adultdvdempire.com这类的网站！

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
欧美的品牌比较杂，似乎很难找到一个统一网站，而且这方面我关注较少。
不过欧美刮削已经有许多其他项目已经做的不错了，当然都是英文项目，例如：
* https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult  jellyfin 插件
* https://github.com/stashapp/stash 这个定位更像是视频服务器，类似 emby，不过包含社区刮削工具

**Comment by Stonebreakers** [comment]
> 欧美的品牌比较杂，似乎很难找到一个统一网站，而且这方面我关注较少。 不过欧美刮削已经有许多其他项目已经做的不错了，当然都是英文项目，例如：
> 
> * https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult  jellyfin 插件
> * https://github.com/stashapp/stash 这个定位更像是视频服务器，类似 emby，不过包含刮削工具

你好， jellyfin 插件安装后代理问题使用不了，求欧美刮削

**Comment by pkr5277** [comment]
PhoenixAdult 这个插件已经用不了

**Comment by bruceyang233** [comment]
希望能添加一个stashdb的刮削方式

**Comment by 1015156857** [comment]
> 欧美的品牌比较杂，似乎很难找到一个统一网站，而且这方面我关注较少。 不过欧美刮削已经有许多其他项目已经做的不错了，当然都是英文项目，例如：
> 
> * https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult  jellyfin 插件
> * https://github.com/stashapp/stash 这个定位更像是视频服务器，类似 emby，不过包含刮削工具

theporndb网址已经从metadataapi.net改成了theporndb.net
能否麻烦更新下

**Comment by sqzw-x** [comment]
> > 欧美的品牌比较杂，似乎很难找到一个统一网站，而且这方面我关注较少。 不过欧美刮削已经有许多其他项目已经做的不错了，当然都是英文项目，例如：
> > 
> > * [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult)  jellyfin 插件
> > * [stashapp/stash](https://github.com/stashapp/stash) 这个定位更像是视频服务器，类似 emby，不过包含刮削工具
> 
> theporndb网址已经从metadataapi.net改成了theporndb.net 能否麻烦更新下

#7

**Comment by jiaminxun** [comment]
> > > 欧美的品牌比较杂，似乎很难找到一个统一的网站，而这方面我很关心。不过欧美刮削已经有许多其他项目已经做的不错了，当然都是英文项目，例如：
> > > 
> > > * [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult)   jellyfin 插件
> > > * [stashapp/stash](https://github.com/stashapp/stash)这个定位是视频服务器，类似emby，不过包含刮削工具
> > 
> > 
> > theporndb网址已经从metadataapi.net改成了theporndb.net能否麻烦更新下
> 
> #7

求作者更新一下theporndb的新地址吧，自定义不会弄啊，而且这也不算是另外一一适配吧，两周前thepornDB还是能用的，现在唯一的网址变了求更新一下，就比如DMM，Javbus的主网址变了作者也得更新一下吧。

**Comment by sqzw-x** [comment]
theporndb 已修复.
StashDB 不准备增加, 原因如下:
- 数据比 theporndb 少很多, 而且显然有重复, 我不清楚是否有独特之处.
- 似乎只能靠文件哈希检索, 这对于云盘挂载用户是无意义的
- 其 api 为 graphql, 写起来比较麻烦
