### ISSUE TITLE
每次多线程刮削，最后一个老是卡住不动

### ISSUE THREAD

**Issue by chenchenno11** [sqzw-x/mdcx#115]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

<img width="541" alt="image" src="https://github.com/sqzw-x/mdcx/assets/142315291/0474ef12-8cee-4153-b3f9-2cf54481f647">

### 如何复现

每一次

**Comment by sqzw-x** [comment]
传一下配置文件，删除 cookie 等敏感信息

**Comment by chenchenno11** [comment]
偶尔是好的，但是时不时就卡最后几个文件，我等4分钟，他不动的话我就手动重启[11.txt](https://github.com/sqzw-x/mdcx/files/14469653/11.txt)

**Comment by chenchenno11** [comment]
<img width="857" alt="image" src="https://github.com/sqzw-x/mdcx/assets/142315291/df787940-f617-4249-8acd-d88e18e45792">
 像这样3分钟了还是没动静

**Comment by sqzw-x** [comment]
我对 200 个文件重复刮削了几次，没能复现此问题，可能是数据不够多。如果你能找到稳定触发的方法或者疑似相关因素，或许有助于排查问题

**Comment by chenchenno11** [comment]
<img width="887" alt="image" src="https://github.com/sqzw-x/mdcx/assets/142315291/3171e134-97d5-4dab-aa25-8d2ddf24d6b1">
感觉不是文件数量的原因，我甚至刮2个也会卡，我这个是云盘的软连接刮削会有影响吗？还是说梯子的原因？我用23年的原版没出现这样的情况

**Comment by sqzw-x** [comment]
你的挂载工具是什么? 有可能是 IO 瓶颈, 你是否开启了某些需要读取原文件的功能(据我所知应该只有获取分辨率需要), 或者检查你的挂载工具, 看看 IO 负载是否很高
另外, 你是每次都刮削这么大数量吗, 这种使用场景可能不多, 因此可能的 bug 更不容易暴露
