### ISSUE TITLE
补全演员信息和头像有一个报错

### ISSUE THREAD

**Issue by anyingxiuluo** [sqzw-x/mdcx#116]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

补全演员头像和信息时报错![IMG_0747](https://github.com/sqzw-x/mdcx/assets/125189022/107c621f-2ced-494f-aa23-550cf77ab089)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
这个不用管，表示 Wiki 没有某些信息，只是没有处理异常，所以会打印
