### ISSUE TITLE
Docker 内无法连接代理

### ISSUE THREAD

**Issue by Tamajiang** [sqzw-x/mdcx#119]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

梯子是可用的，防火墙没有屏蔽，在vps端 Ping 指定网址是可用的，另一个IP 检查vps终端端口也是可用的，docker 网络检查都不可用，网络检查显示error 104 connection rest by peer，docker 日志显示： Client needs protocol version 3.8，不知是否是日志显示问题，MDCx 端日志见下图。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
2024-03-06 11:10:44
stdout
[xvnc ] VNCSConnST: Client pixel format depth 24 (32bpp) little-endian bgr888
2024-03-06 11:10:44
stdout
[xvnc ] VNCSConnST: Server default pixel format depth 24 (32bpp) little-endian rgb888
2024-03-06 11:10:44
stdout
[xvnc ] SConnection: Client requests security type None(1)
2024-03-06 11:10:44
stdout
[xvnc ] SConnection: Client needs protocol version 3.8
2024-03-06 11:10:44
stdout
[xvnc ] Wed Mar 6 11:10:44 2024
2024-03-06 11:10:44
stdout
[xvnc ] Connections: accepted: /tmp/vnc.sock
2024-03-06 11:09:41
stdout
[supervisor ] all services started.
2024-03-06 11:09:40
stdout
[app ] nohup: appending output to 'nohup.out'
2024-03-06 11:09:40
stdout
[app ] 🔘 执行cacert.pem缺失问题的临时修复脚本
2024-03-06 11:09:40
stdout
[app ] ⏳ 启动MDCx...
```

### 截图

![截屏2024-03-06 12 15 42](https://github.com/sqzw-x/mdcx/assets/153880976/e055da89-f879-4a22-bcc0-1c6a10830671)

**Comment by sqzw-x** [comment]
docker 网络模式以及代理设置分别是什么？

**Comment by Tamajiang** [comment]
网络模式是 bridge，代理开的 http

**Comment by Tamajiang** [comment]
我是直接连接的外部vps地址，我在办公室电脑是ping得到的，端口用nt也是查到可用的，这种也需要修改为host模式吗？

**Comment by Tamajiang** [comment]
改为host也不行，全红，很奇怪的是前几天网络检测还可以连到github，今天偶尔一个能绿，但刮削依然没数据

**Comment by Tamajiang** [comment]
> 我用的是docker版，软件里面自带的socks5代理可以正常使用的

谢谢提醒，果然 socks 可以使用，只好开两个代理了，哪个能用用哪个

**Comment by Tamajiang** [comment]
> 因为我不是 dockerfile 的维护者以及用户, 所以不好确定问题 首先确认 vps 是否正常, 在 docker 之外测试, 不要仅仅 ping, 使用 curl 发送实际请求. 如果确认 vps 没有问题, 那么一定是 docker 设置的问题. 此外我查到似乎系统时间不正确也可能导致此问题, 你可以检查一下

算是解决了

**Comment by anyingxiuluo** [comment]
> > 我用的是docker版，软件里面自带的socks5代理可以正常使用的
> 
> 也就是说 http 代理无法在 docker 内正常使用是普遍问题吗

我测试了http代理在docker中也是可以用的
![image](https://github.com/sqzw-x/mdcx/assets/125189022/f78d55f5-f9ae-4188-803e-7916b9d5b4d4)

**Comment by sqzw-x** [comment]
好的.
我仍然倾向于 vps 设置问题, 建议检查一下代理服务器的配置.
不过既然 socks 可以正常工作, 那么此问题应当与 mdcx 无关
