### ISSUE TITLE
希望有docker版本

### ISSUE THREAD

**Issue by Lionzj** [sqzw-x/mdcx#12]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [ ] 我正在使用最新版本

### 描述你的问题

目前资料都在NAS上，整python环境相对有点麻烦，如果可以的话整一个docker镜像，这样泛用性就大大增加了

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
可以看一下 https://github.com/northsea4/mdcx-docker
不过需要自行构建镜像. `builtin` 版需打包新版可执行文件，`src` 版则需要修改程序入口为 `main.py`

**Comment by sqzw-x** [comment]
> 我有空对接一下

感谢


> @sqzw-x 请问以后发布的latest都是 `120231219` 这种格式的名称吗？看上去是前面一个 `1` 然后加上日期 `20231219`。

是的，主要是考虑与原版区分
