### ISSUE TITLE
检测网络到7mmtv.tv 卡住不动

### ISSUE THREAD

**Issue by cclove666** [sqzw-x/mdcx#121]
<img width="768" alt="微信图片_20240306212817" src="https://github.com/sqzw-x/mdcx/assets/91047444/4cccf2b5-a6cc-49c7-b62a-954dee317148">
检测网络到卡住不动

**Comment by cclove666** [comment]
<img width="483" alt="微信图片_20240306213031" src="https://github.com/sqzw-x/mdcx/assets/91047444/bcba56ec-9217-4dc8-b732-06ff1b5547fa">
手动停止后报错

**Comment by sqzw-x** [comment]
改成 `https://7mmtv.sx/` 原网址已经坏了, 而且不断重定向, 导致卡死, 下个版本修一下吧
