### ISSUE TITLE
theporndb网站修复之后仍削刮不出

### ISSUE THREAD

**Issue by pkr5277** [sqzw-x/mdcx#124]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

![image](https://github.com/sqzw-x/mdcx/assets/38154917/afcfcbb7-93b5-4dcd-ae88-d37d209775f3)
这个网站打开是这样的
![image](https://github.com/sqzw-x/mdcx/assets/38154917/ef31a574-0f5d-4051-83a3-e838c98a1327)
使用的是0306是最新版本
![image](https://github.com/sqzw-x/mdcx/assets/38154917/0cdcbbe7-9c57-4ae6-875b-9c6699361e54)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
这个 url 是不正确的，一直到本行最后都是
你直接访问没有 token 肯定显示未授权

**Comment by pkr5277** [comment]
> 我说你直接在浏览器打开是未授权的 把影片名称以文本发出来

名称是这个 nubilefilms-all-work-and-no-play 
对应的网址是 https://theporndb.net/scenes/nubile-films-all-work-and-no-play-s44e14
