### ISSUE TITLE
大佬更新之后的版本javdb的cookie仍然失效，theporndb仍然无法削刮

### ISSUE THREAD

**Issue by pkr5277** [sqzw-x/mdcx#127]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [x] 我正在使用最新版本

### 描述你的问题

大佬更新之后的版本javdb的cookie仍然失效，theporndb仍然无法削刮
大佬有电报吗，我加你单独给你发吧

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
cookie 格式为 `_jdb_session=xxxxxxx;` 也可以包含其它项, 但只有 `_jdb_session` 是必须的
theporndb 使用 hash 应该能正常刮削, 文件名还有点问题, 逻辑太复杂, 我正在查看

**Comment by pkr5277** [comment]
> cookie 格式为 `_jdb_session=xxxxxxx;` 也可以包含其它项, 但只有 `_jdb_session` 是必须的 theporndb 使用 hash 应该能正常刮削, 文件名还有点问题, 逻辑太复杂, 我正在查看

感谢大佬，javdb可以用了

**Comment by wangjd2** [comment]
Javdb获取的Cookie填入显示无效

**Comment by MinCheng7** [comment]
> > Javdb获取的Cookie填入显示无效
> 
> 这个检测机制似乎有刷新bug： 1.填完cookie一定要重启软件 2.关掉广告拦截器获取COOKIE 3.再不行就把IPV4 ONLY给关掉重启软件

果然 填入之后重启软件才显示正常😂

<img width="518" height="313" alt="Image" src="https://github.com/user-attachments/assets/a80b6604-a5bf-4909-8c9a-995c1a4276a7" />

**Comment by nikleechan** [comment]
> > Javdb获取的Cookie填入显示无效
> 
> 这个检测机制似乎有刷新bug： 1.填完cookie一定要重启软件 2.关掉广告拦截器获取COOKIE 3.再不行就把IPV4 ONLY给关掉重启软件

果然重启有用！！！感谢！！！
