### ISSUE TITLE
cableav和lulubar

### ISSUE THREAD

**Issue by anyingxiuluo** [sqzw-x/mdcx#128]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

cableav和lulubar网站能正常访问，网络检查显示403
![微信截图_20240307201714](https://github.com/sqzw-x/mdcx/assets/125189022/50d32214-2917-4cef-bd82-e77364ca638e)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
curl_cffi 就是为了绕 cf 盾引入的，如果这个也不行那确实不好办。
不太想引入无头浏览器，太慢了，维护成本也大大增加

**Comment by 201030LJK** [comment]
我无法加载视频，提示需要安装FluidPlayer，什么情况，求解
