### ISSUE TITLE
关于jav321网站拉取封面图不清晰的问题

### ISSUE THREAD

**Issue by xsm123006** [sqzw-x/mdcx#137]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

比如这个网页，https://www.jav321.com/video/13dsvr01446 ，本来左侧有高清图，但是程序默认拉取的是147*200的那个小图，太模糊了。能否修改拉取左侧大图呢？

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by xsm123006** [comment]
我是刮削VR发现的，我看了vr这边基本都是封面，能否专门做个VR的单个网站刮削？

**Comment by sqzw-x** [comment]
不准备加入新功能
