### ISSUE TITLE
单文件刮削报错，女优名称存在生僻字的情况

### ISSUE THREAD

**Issue by dbsxfz** [sqzw-x/mdcx#138]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

刮削MIDV-605出现的报错，刮削卡死，刮削情况如截图，怀疑情况是女优名称包含115或者挂载盘不兼容的字符导致重命名失败。

### 如何复现

刮削MIDV-605，使用字段优先，日本IP，使用的挂载盘是CLOUDDRIVE

### 截图

MDCX的截图，找到封面后卡死。
<img width="813" alt="{62371B53-F5C4-4cd2-91BF-9F904AC2111A}" src="https://github.com/sqzw-x/mdcx/assets/73024218/ff04133e-233d-46a1-b759-4f3f14f290f3">
刮削后的目录图，出现乱码。
<img width="1042" alt="{B6AEDEE6-C9CE-4adf-844D-A8E60CC74DBF}" src="https://github.com/sqzw-x/mdcx/assets/73024218/3031a79b-7502-4a69-bc0d-b6aa1206c5e6">
clouddrive报错的截图，可以看出确实是火军这个字不好打的问题。
<img width="920" alt="{F85D99FB-F9B1-4f07-9A5C-246A3738911F}" src="https://github.com/sqzw-x/mdcx/assets/73024218/3b0fbdad-2103-413c-9e7f-61abed80e1ee">

**Comment by dbsxfz** [comment]
我最后的解决方案是使用dmm刮削，就直接刮成日文名了，默认的字段优先的顺序是theporndb,javbus,javlibrary,javdb，不清楚是哪个导致出现不支持的字体的。

**Comment by sqzw-x** [comment]
Windows 本地是没问题的，是115的问题，在115网页端也无法创建此名称的文件夹
