### ISSUE TITLE
使用madouqu网站刮削失败

### ISSUE THREAD

**Issue by smilejoker365** [sqzw-x/mdcx#14]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

使用madouqu网站刮削失败，提示Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21047 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

### 如何复现

1. 前往 '设置'
2. 点击 '刮削网站'
3. 指定网站 'madouqu'
4. 出现问题

### 预期行为

能否修复madouqu的刮削，单纯使用mdtv进行刮削的话，还有一部分影片元数据不全，madouqu相对比较全

### 相关 Logs

```Text
Create log file: C:\Users\imac\Downloads\MDCx-win-20231014\Log\2023-12-25-11-48-18.txt

 🛠 当前配置：C:\Users\imac\Downloads\MDCx-win-20231014\config.ini 加载完成！
 📂 程序目录：C:\Users\imac\Downloads\MDCx-win-20231014 
 📂 刮削目录：X:\私人文件\国产 
 💠 刮削模式：正常模式 · 指定网站 · madouqu 
 🖥️ 系统信息：Windows-10-10.0.19044 
 🐰 软件版本：120231219 

 ❌ JavDb 未填写 Cookie，影响 FC2 刮削！可在「设置」-「网络」添加！
基于 MDC-GUI 修改 · 当前版本: 120231219 （ <font color="green">你使用的是最新版本！🎉 </font>）
================================================================================
 ❌ ThePornDB 未填写 API Token，影响欧美刮削！可在「设置」-「网络」添加！
 ✅ JavBus 连接正常！

 ⏰ Start time: 2023-12-25 11:48:24
 🖥 Movie path: X:\私人文件\国产
 🔎 Searching all videos, Please wait...
    11:48:24 Found (419)! Skip successfully scraped (0) repeat softlink (0)! (0s)... Still searching, please wait... 　
    Done!!! Found (419)! Skip successfully scraped (0) repeat softlink (0)! (0s) 　
 📺 Find 419 movies
 🕷 开启多线程，线程数量（10），线程延时（0）秒...
 🕷 11:48:24 开始刮削：1/419 18bt.net_糖心Vlog 【糖心独家】御梦子の操粉挑战 淫穴梦梦线下约炮男...
 🕷 11:48:24 开始刮削：2/419 91PCM-001 蒂洁 清纯系JK女学生 像极了初恋女友 91制片厂.mp4
 🕷 11:48:24 开始刮削：3/419 91PCM-002 蒂洁 农民工操上气质空姐 湿透的空乘服务 91制片厂.mp4
 🕷 11:48:24 开始刮削：4/419 91PCM-003 李娜娜 现代吸穴鬼传说 吸舔美女嫩穴 91制片厂.mp4
 🕷 11:48:24 开始刮削：5/419 HongKongDoll  假日瑜伽.mp4
 🕷 11:48:24 开始刮削：6/419 ID5370 乔安 情糜女体香 爱豆传媒.mp4
 🕷 11:48:24 开始刮削：7/419 MFK-0028 FLIXKO 家政妇：莫非定律 麻豆传媒映画.mp4
 🕷 11:48:24 开始刮削：8/419 PME-171 吴文淇 我的大嫂是骚逼 蜜桃影像传媒.mp4
 🕷 11:48:24 开始刮削：9/419 Yua  露天泳池の香艳肉欲 淫媚吸吮舔食肉棒 女上位全自动榨精 同步高潮瞬间 ...
 🕷 11:48:24 开始刮削：10/419 [ThZu.Cc]KM-008實習調酒師被潛規則.mp4

1/419 (0.24%) round(1) 18bt.net_糖心Vlog 【糖心独家】御梦子の操粉挑战 淫穴梦梦线下约炮男粉丝实录 高颜值绝美肉体服侍粉丝大肉棒.mp4
================================================================================
 🙈 [Movie] X:\私人文件\国产\failed\18bt.net_糖心Vlog 【糖心独家】御梦子の操粉挑战 淫穴梦梦线下约炮男粉丝实录 高颜值绝美肉体服侍粉丝大肉棒.mp4
 🚘 [Number] 糖心VLOG 御梦子の操粉挑战 淫穴梦梦线下约炮男粉丝实录 高颜值绝美肉体服侍粉丝大肉棒
 😸 [Note] You specified 「 madouqu 」, some videos may not have results! 
 🌐 [website] madouqu(63s)
    🌐 madouqu
       请求地址: https://madouqu.com/?s=御梦子の操粉挑战 
       网络请求错误: https://madouqu.com/?s=御梦子の操粉挑战
Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21060 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
 🔴 Data failed!(63s)
 🔴 [Failed] Reason: 网络请求错误: https://madouqu.com/?s=御梦子の操粉挑战
Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21060 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
 🙊 [Movie] X:\私人文件\国产\failed\18bt.net_糖心Vlog 【糖心独家】御梦子の操粉挑战 淫穴梦梦线下约炮男粉丝实录 高颜值绝美肉体服侍粉丝大肉棒.mp4
================================================================================
 🕷 11:49:27 1/419 18bt.net_糖心Vlog 【糖心独家】御梦子の操粉挑战 淫穴梦梦线下约炮男粉丝实录 高颜值绝美肉体服侍粉丝大肉棒.mp4 刮削完成！用时 63 秒！
 🕷 11:49:27 开始刮削：11/419 [ThZu.Cc]KM-009素人女優專訪實錄.mp4

2/419 (0.48%) round(1) 91PCM-002 蒂洁 农民工操上气质空姐 湿透的空乘服务 91制片厂.mp4
================================================================================
 🙈 [Movie] X:\私人文件\国产\failed\91PCM-002 蒂洁 农民工操上气质空姐 湿透的空乘服务 91制片厂.mp4
 🚘 [Number] 91PCM-002
 😸 [Note] You specified 「 madouqu 」, some videos may not have results! 
 🌐 [website] madouqu(63s)
    🌐 madouqu
       请求地址: https://madouqu.com/?s=91PCM-002 
       网络请求错误: https://madouqu.com/?s=91PCM-002
Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21059 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
 🔴 Data failed!(63s)
 🔴 [Failed] Reason: 网络请求错误: https://madouqu.com/?s=91PCM-002
Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21059 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
 🙊 [Movie] X:\私人文件\国产\failed\91PCM-002 蒂洁 农民工操上气质空姐 湿透的空乘服务 91制片厂.mp4
```

**Comment by sqzw-x** [comment]
检查网络情况，我这边测试正常

**Comment by wuaishanshan** [comment]
> ### 在提问之前...
> * [x]  我已经搜索了现有的 issues
> * [x]  我在提问题之前至少花费了 5 分钟来思考和准备
> * [x]  我正在使用最新版本
> 
> ### 描述你的问题
> 使用madouqu网站刮削失败，提示Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21047 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
> 
> ### 如何复现
> 1. 前往 '设置'
> 2. 点击 '刮削网站'
> 3. 指定网站 'madouqu'
> 4. 出现问题
> 
> ### 预期行为
> 能否修复madouqu的刮削，单纯使用mdtv进行刮削的话，还有一部分影片元数据不全，madouqu相对比较全
> 
> ### 相关 Logs
> ```
> Create log file: C:\Users\imac\Downloads\MDCx-win-20231014\Log\2023-12-25-11-48-18.txt
> 
>  🛠 当前配置：C:\Users\imac\Downloads\MDCx-win-20231014\config.ini 加载完成！
>  📂 程序目录：C:\Users\imac\Downloads\MDCx-win-20231014 
>  📂 刮削目录：X:\私人文件\国产 
>  💠 刮削模式：正常模式 · 指定网站 · madouqu 
>  🖥️ 系统信息：Windows-10-10.0.19044 
>  🐰 软件版本：120231219 
> 
>  ❌ JavDb 未填写 Cookie，影响 FC2 刮削！可在「设置」-「网络」添加！
> 基于 MDC-GUI 修改 · 当前版本: 120231219 （ <font color="green">你使用的是最新版本！🎉 </font>）
> ================================================================================
>  ❌ ThePornDB 未填写 API Token，影响欧美刮削！可在「设置」-「网络」添加！
>  ✅ JavBus 连接正常！
> 
>  ⏰ Start time: 2023-12-25 11:48:24
>  🖥 Movie path: X:\私人文件\国产
>  🔎 Searching all videos, Please wait...
>     11:48:24 Found (419)! Skip successfully scraped (0) repeat softlink (0)! (0s)... Still searching, please wait... 　
>     Done!!! Found (419)! Skip successfully scraped (0) repeat softlink (0)! (0s) 　
>  📺 Find 419 movies
>  🕷 开启多线程，线程数量（10），线程延时（0）秒...
>  🕷 11:48:24 开始刮削：1/419 18bt.net_糖心Vlog 【糖心独家】御梦子の操粉挑战 淫穴梦梦线下约炮男...
>  🕷 11:48:24 开始刮削：2/419 91PCM-001 蒂洁 清纯系JK女学生 像极了初恋女友 91制片厂.mp4
>  🕷 11:48:24 开始刮削：3/419 91PCM-002 蒂洁 农民工操上气质空姐 湿透的空乘服务 91制片厂.mp4
>  🕷 11:48:24 开始刮削：4/419 91PCM-003 李娜娜 现代吸穴鬼传说 吸舔美女嫩穴 91制片厂.mp4
>  🕷 11:48:24 开始刮削：5/419 HongKongDoll  假日瑜伽.mp4
>  🕷 11:48:24 开始刮削：6/419 ID5370 乔安 情糜女体香 爱豆传媒.mp4
>  🕷 11:48:24 开始刮削：7/419 MFK-0028 FLIXKO 家政妇：莫非定律 麻豆传媒映画.mp4
>  🕷 11:48:24 开始刮削：8/419 PME-171 吴文淇 我的大嫂是骚逼 蜜桃影像传媒.mp4
>  🕷 11:48:24 开始刮削：9/419 Yua  露天泳池の香艳肉欲 淫媚吸吮舔食肉棒 女上位全自动榨精 同步高潮瞬间 ...
>  🕷 11:48:24 开始刮削：10/419 [ThZu.Cc]KM-008實習調酒師被潛規則.mp4
> 
> 1/419 (0.24%) round(1) 18bt.net_糖心Vlog 【糖心独家】御梦子の操粉挑战 淫穴梦梦线下约炮男粉丝实录 高颜值绝美肉体服侍粉丝大肉棒.mp4
> ================================================================================
>  🙈 [Movie] X:\私人文件\国产\failed\18bt.net_糖心Vlog 【糖心独家】御梦子の操粉挑战 淫穴梦梦线下约炮男粉丝实录 高颜值绝美肉体服侍粉丝大肉棒.mp4
>  🚘 [Number] 糖心VLOG 御梦子の操粉挑战 淫穴梦梦线下约炮男粉丝实录 高颜值绝美肉体服侍粉丝大肉棒
>  😸 [Note] You specified 「 madouqu 」, some videos may not have results! 
>  🌐 [website] madouqu(63s)
>     🌐 madouqu
>        请求地址: https://madouqu.com/?s=御梦子の操粉挑战 
>        网络请求错误: https://madouqu.com/?s=御梦子の操粉挑战
> Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21060 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
>  🔴 Data failed!(63s)
>  🔴 [Failed] Reason: 网络请求错误: https://madouqu.com/?s=御梦子の操粉挑战
> Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21060 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
>  🙊 [Movie] X:\私人文件\国产\failed\18bt.net_糖心Vlog 【糖心独家】御梦子の操粉挑战 淫穴梦梦线下约炮男粉丝实录 高颜值绝美肉体服侍粉丝大肉棒.mp4
> ================================================================================
>  🕷 11:49:27 1/419 18bt.net_糖心Vlog 【糖心独家】御梦子の操粉挑战 淫穴梦梦线下约炮男粉丝实录 高颜值绝美肉体服侍粉丝大肉棒.mp4 刮削完成！用时 63 秒！
>  🕷 11:49:27 开始刮削：11/419 [ThZu.Cc]KM-009素人女優專訪實錄.mp4
> 
> 2/419 (0.48%) round(1) 91PCM-002 蒂洁 农民工操上气质空姐 湿透的空乘服务 91制片厂.mp4
> ================================================================================
>  🙈 [Movie] X:\私人文件\国产\failed\91PCM-002 蒂洁 农民工操上气质空姐 湿透的空乘服务 91制片厂.mp4
>  🚘 [Number] 91PCM-002
>  😸 [Note] You specified 「 madouqu 」, some videos may not have results! 
>  🌐 [website] madouqu(63s)
>     🌐 madouqu
>        请求地址: https://madouqu.com/?s=91PCM-002 
>        网络请求错误: https://madouqu.com/?s=91PCM-002
> Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21059 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
>  🔴 Data failed!(63s)
>  🔴 [Failed] Reason: 网络请求错误: https://madouqu.com/?s=91PCM-002
> Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21059 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
>  🙊 [Movie] X:\私人文件\国产\failed\91PCM-002 蒂洁 农民工操上气质空姐 湿透的空乘服务 91制片厂.mp4
> ```
> 
> ### 截图
> _No response_
> 
> ### 还有别的吗？
> _No response_

这是真的有问题，网络测试域名是通过的，同一节点下用6月份的版本刮削可以，但是新的就不行了，老版本有一个缺点就是只能刮番号，中文名无法刮削不然就完美了

**Comment by wuaishanshan** [comment]
新版本刮削都是报网络请求错误

**Comment by sqzw-x** [comment]
6月份之后的版本原作者更换了部分网站的请求库为 `curl_cffi`，可能是这一改动导致的。
以下网站使用该库：`airav.py
airav_cc.py
avsex.py
freejavbt.py
iqqtv.py
javdb.py
javlibrary.py
madouqu.py
mmtv.py` 以及获取亚马逊图片，可以看看其它网站是否同样报错
不排除是第三方库的问题，但是无法稳定复现
