### ISSUE TITLE
有办法将处理过的视频批量移回到原路径吗？

### ISSUE THREAD

**Issue by biubiushaka** [sqzw-x/mdcx#140]
初次使用mdcx这类刮削工具没有任何经验，也没仔细研究各设置项，就单纯设置了成功输出目录、失败输出目录这些配置。。。
结果成功刮削的倒还好，毕竟按规则放置的也比较有条理吧；但是刮削失败的就惨了，几千个文件全一股脑放一块了，原来手动归置的好歹按系列、剧名分门别类放置。。。结果没想到不仅没刮出来、还全都一勺烩了。。。

按说无论刮削成功还是失败都有日志记录吧，所以有没有脚本之类的工具能自动、批量的将处理过的视频文件移回原始目录？

**Comment by sqzw-x** [comment]
mdcx 本身没有这个功能
如果你有原始日志，一种方法是用正则表达式提取出所有文件的原始路径和失败路径，然后使用脚本批量移动

**Comment by biubiushaka** [comment]
好吧，那我去搜搜咋写脚本吧。。。。
