### ISSUE TITLE
软件自作聪明，在刮削时主动添加“-”分隔符的问题

### ISSUE THREAD

**Issue by anubisred253** [sqzw-x/mdcx#146]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

很多无码片的品番是没有分隔符的，比如FDD2211、FZ19、乃至C0930、H0930、H4610网站等等……
我的视频文件是标准的名字（如FDD2211.mp4），但刮削时软件却以FDD-2211进行搜索，肯定搜索不到啊，还得自己手动一个个输入链接地址重新搜索……
请问如何解决。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

<img width="314" alt="微信图片_20240317130827" src="https://github.com/sqzw-x/mdcx/assets/127456639/68725a8b-2fc7-4e67-b9b5-97d05278b89b">

**Comment by sqzw-x** [comment]
配置的数据源是哪些网站

**Comment by anubisred253** [comment]
> 配置的数据源是哪些网站

以影片FDD2211为例，javbus、avsox、javdb、freejavbt都有这个问题

**Comment by sqzw-x** [comment]
FDD2211 只在 javbus、avsox 存在，另外两个网站并没有该影片, 举例时建议确认有效性
你所谓的 "自作聪明" 是很傲慢的措辞. 你并不清楚网上资源命名的混乱程度, 不了解提取番号的复杂度, 有许多有码影片文件名中都没有 `-`, 除非你能让这些资源站都规范命名, 否则仅凭 mdcx 无法确认 XXX-1111 和 XXX1111 哪个正确, 所以仅就这个例子而言，无法在根本上解决.

**Comment by auroracamus** [comment]
> ### 在提问之前...
> * [x]  我已经搜索了现有的 issues
> * [x]  我在提问题之前至少花费了 5 分钟来思考和准备
> * [x]  我正在使用最新版本
> 
> ### 描述你的问题
> 很多无码片的品番是没有分隔符的，比如FDD2211、FZ19、乃至C0930、H0930、H4610网站等等…… 我的视频文件是标准的名字（如FDD2211.mp4），但刮削时软件却以FDD-2211进行搜索，肯定搜索不到啊，还得自己手动一个个输入链接地址重新搜索…… 请问如何解决。
> 
> ### 如何复现
> 1. 前往 '...'
> 2. 点击 '....'
> 3. 滑动到 '....'
> 4. 出现问题
> 
> ### 预期行为
> _No response_
> 
> ### 相关 Logs
> _No response_
> 
> ### 截图
> <img alt="微信图片_20240317130827" width="314" src="https://private-user-images.githubusercontent.com/127456639/313446745-68725a8b-2fc7-4e67-b9b5-97d05278b89b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTgzNTQsIm5iZiI6MTcxMDgxODA1NCwicGF0aCI6Ii8xMjc0NTY2MzkvMzEzNDQ2NzQ1LTY4NzI1YThiLTJmYzctNGU2Ny1iOWI1LTk3ZDA1Mjc4Yjg5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMzE0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTA4OGY3YmZhMjk1N2UzNzBkZjFlZTQ3ZmNjNzU1YWRkOGJiYjNjMmY4ZjM2MDk1MTAwN2I3YmY0YWUxNDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZS6ZCaF3SHGs7AcoGyjriD_uD7n41I0CBJjDbFlcyww">
> ### 还有别的吗？
> _No response_

你这个标题欠妥，软件永远不会完美，但是也不会“自作聪明”。

出现的问题都是有原因的，分析问题的前提是提交尽可能详细的描述。

提交问题前的三件事都做了吗？相关的日志、设定都提供了吗？

这些都是有助于解决问题的东西，而情绪输出则毫无帮助。

**Comment by fliclumsy** [comment]
好一个“自作聪明”，软件要解决的是大多数情况，不是特例
