### ISSUE TITLE
点击刮削后直接秒完成，但没有执行刮削任务

### ISSUE THREAD

**Issue by xmasrain** [sqzw-x/mdcx#15]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

点击刮削后直接秒完成，但没有执行刮削任务，目录有文件，但就是执行刮削任务，很着急。

### 如何复现

![image](https://github.com/sqzw-x/mdcx/assets/58833842/e2b4e94e-fa97-4280-bf64-0c8b9c890c6d)
![image](https://github.com/sqzw-x/mdcx/assets/58833842/c9fe300b-3ef3-42dd-97c6-f2206685758f)

**Comment by Ahaezio** [comment]
和我遇到的问题一样，偶尔可以刮，但是刮十几个又停。再刮怎么也刮不出

**Comment by Ahaezio** [comment]
取消勾选 高级 - 间歇刮削   根据前面的回答，已经解决~

**Comment by a525850194** [comment]
感谢，这个方法有用

**Comment by sqzw-x** [comment]
#13
