### ISSUE TITLE
建议：当作品演员为“未知”时，向nfo文件中添加相应名称的演员条目。

### ISSUE THREAD

**Issue by auroracamus** [sqzw-x/mdcx#151]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

当某个作品的演员条目为空时，软件会依照设定对文件或文件夹进行命名。

此时nfo文件中不会生成 ”actor“条目，这使得当使用管理软件进行搜索时，无法在演员分类中以”未知演员“进行搜索。

### 如何复现

1. 对”MEKO-299.mp4“进行处理
2. 打开生成的”MEKO-299.nfo“
3. 出现问题

### 预期行为

当演员为未知时，依然向nfo文件中添加相关条目。

**Comment by sqzw-x** [comment]
现在应当可以正常写入
