### ISSUE TITLE
大佬我发现一个网站希望支持

### ISSUE THREAD

**Issue by hfcj478** [sqzw-x/mdcx#153]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [ ] 我正在使用最新版本

### 描述你的问题

大佬我发现一个网站希望能支持
感觉比较全
https://javmulu.info/

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
粗看了一下，感觉也是搬得 dmm 数据。如果你认为有什么独特之处可以举例说明

**Comment by pastay** [comment]
希望增加https://hbox.jp/
这个网站当中可以获取高清封面图（免剪裁）
尤其是对于sod家支持比较好，sod的大部分封面剪裁完也是不对的。
可否优先查询hbox，如果没有匹配再去别的网站刮削？

**Comment by sqzw-x** [comment]
> 希望增加[hbox.jp](https://hbox.jp/) 这个网站当中可以获取高清封面图（免剪裁） 尤其是对于sod家支持比较好，sod的大部分封面剪裁完也是不对的。 可否优先查询hbox，如果没有匹配再去别的网站刮削？

看了下，这个网站似乎是没有番号的，只能通过标题搜索，这基本上无法用于刮削

**Comment by pastay** [comment]
用番号搜索也是可以的，只是页面内没有找到番号信息。
可以用这个测试，如果有收录，第一个搜索结果就是影片的信息页面
https://hbox.jp/search_result?category_val=23-5&x=0&y=0&stk=61bd1d912c358f9c&gaq=番号&q_array%5B%5D=番号

**Comment by freesrz93** [comment]
> 用番号搜索也是可以的，只是页面内没有找到番号信息。 如果有收录，第一个搜索结果就是影片的信息页面
> 
> 以搜索FSDSS-719为例 抓取链接为 [hbox.jp/search_result?category_val=23-5&x=0&y=0&stk=61bd1d912c358f9c&gaq=FSDSS-719&q_array%5B%5D=FSDSS-719](https://hbox.jp/search_result?category_val=23-5&x=0&y=0&stk=61bd1d912c358f9c&gaq=FSDSS-719&q_array%5B%5D=FSDSS-719) 在这个页面里，可以提取到搜索结果的cid号 XXXX 影片页面链接[hbox.jp/category/movie/av/=/cid/XXXX](https://hbox.jp/category/movie/av/=/cid/XXXX) 高清封面图片的链接为[hbox.jp/image3/content/XXXX/cover.jpg](https://hbox.jp/image3/content/XXXX/cover.jpg) 即 这个例子[hbox.jp/image3/content/524039/cover.jpg](https://hbox.jp/image3/content/524039/cover.jpg) 当然也可以获取其他信息

那如何确定搜索结果确实与番号匹配呢？我注意到在详情页是可以从源代码获取 番号 的，但是搜索结果页没有展示，这比较容易造成误判
