### ISSUE TITLE
当搜刮网站为airav.io时搜刮图片失败

### ISSUE THREAD

**Issue by bigzhang12** [sqzw-x/mdcx#157]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

MDCx-120240321-windows-x86_64-ecaf015e

### 描述你的问题

当搜刮网站为airav,io时搜刮图片失败
图片下载地址变为了搜索
![捕获](https://github.com/sqzw-x/mdcx/assets/79297361/876fdde8-d307-4894-bd5c-1b8eb40946b2)

### 如何复现

搜刮网站指定为[airav](https://airav.io/)

### 预期行为

期望能能修改一下airav网站的图片检测方式

### 截图

![捕获](https://github.com/sqzw-x/mdcx/assets/79297361/7334607c-ea7f-445d-a99f-80aa7ad70997)

**Comment by anyingxiuluo** [comment]
你这是ip被google限制了

**Comment by bigzhang12** [comment]
> 你这个ip被google限制了

ip没有被限制，其它网站的图片检测都能通过，[airav](https://airav.io/)的图片就是检测不通过
![捕获](https://github.com/sqzw-x/mdcx/assets/79297361/660db789-0c09-495f-a8ad-1e2c01c3561c)
好像是这个网站的图床屏蔽了google？
