### ISSUE TITLE
JavDb网站无法使用，已登录 cookie验证不通过 

### ISSUE THREAD

**Issue by 994371407** [sqzw-x/mdcx#158]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

120240321

### 描述你的问题

JavDb网站无法使用，已登录 cookie验证不通过 
实际  https://javdb.com/v/D16Q5?locale=zh 可以打开。

JavDb 连接失败！请检查网络或代理设置！ https://javdb.com/v/D16Q5?locale=zh
Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to javdb.com port 443 after 21252 ms: Couldn't connect to server'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by 994371407** [comment]
![screenshot-1711688172661](https://github.com/sqzw-x/mdcx/assets/165356440/030fa501-84e8-4398-bc97-9f945d6f9fef)

**Comment by sqzw-x** [comment]
网络问题

**Comment by 994371407** [comment]
> 网络问题

网络正常的，全局代理，cookie是当场获取的，提示的无法连接的，网页这个地址是可以打开的
![screenshot-1711716728823](https://github.com/sqzw-x/mdcx/assets/165356440/0ae880c7-3573-4961-87ed-f90d5c788e6f)

**Comment by sqzw-x** [comment]
cookie 的检测是没问题的，我本地测试正常，而且显示是 curl 请求报错，你可以检查一下代理设置是否正确

**Comment by 994371407** [comment]
好的 谢谢。那我换个代理试试。 奇怪 网页地址是可以的

**Comment by daiguaxiaobai** [comment]
偶尔重复几次可以测试成功一次

**Comment by daiguaxiaobai** [comment]
我这边代理问题，v2rayN开启Tun模式就可以用了

**Comment by daiguaxiaobai** [comment]
![Uploading 屏幕截图 2024-03-31 215355.png…]()

**Comment by daiguaxiaobai** [comment]
![屏幕截图 2024-03-31 215355](https://github.com/sqzw-x/mdcx/assets/160205638/34f4eb6e-eba5-445b-b364-ef09840beeb9)

**Comment by daiguaxiaobai** [comment]
> > v2rayN开启Tun模式
> 
> 现在显示了 ![image](https://private-user-images.githubusercontent.com/142315291/321107212-99e5ed50-317d-4842-b16b-794d77d41faa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzQ5MjIsIm5iZiI6MTcxMjczNDYyMiwicGF0aCI6Ii8xNDIzMTUyOTEvMzIxMTA3MjEyLTk5ZTVlZDUwLTMxN2QtNDg0Mi1iMTZiLTc5NGQ3N2Q0MWZhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNzM3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2QwMDMxYjllZDljM2YzZmUwYjllYTkxM2YxYmQ3ZmEzMmY3Y2JlY2Q5Zjk0ZDhiOTQ0NjdhOTY1MTliNzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bzc9U_iIuTuz7Su-ujT5T7gWiFgiqhThmX7bUb7R6Ew) 请问cookie是不是我这样的啊？
管理员运行v2rayN开启Tun模式   
![屏幕截图 2024-04-10 154212](https://github.com/sqzw-x/mdcx/assets/160205638/9b8be181-f5b4-4234-9f7b-352f750049bb)
路由--绕过大陆
MDCx     设置-代理   调为 不使用
