### ISSUE TITLE
间歇刮削时间不生效

### ISSUE THREAD

**Issue by anyingxiuluo** [sqzw-x/mdcx#159]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

120240321

### 描述你的问题

间歇刮削时间不生效，默认1分2秒，我改成40秒，不生效

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
重启后能生效
将就用吧，感觉不太好修。这么长时间没人报，估计用的人也不多

**Comment by anyingxiuluo** [comment]
> 重启后能生效
> 将就用吧，感觉不太好修。这么长时间没人报，估计用的人也不多

好的，无伤大雅
