### ISSUE TITLE
javdb ck一直显示不能连接

### ISSUE THREAD

**Issue by chenchenno11** [sqzw-x/mdcx#167]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

最新版，0321

### 描述你的问题

一直显示失败，
按照正确方法获得了ck，且多次尝试刷新都得到了同一串ck，仍然显示连接不上

### 如何复现

一直显示失败，
按照正确方法获得了ck，且多次尝试刷新都得到了同一串ck，仍然显示连接不上
![image](https://github.com/sqzw-x/mdcx/assets/142315291/2470be6c-5a39-40ef-aea7-630882c6c8da)

**Comment by sqzw-x** [comment]
#158
