### ISSUE TITLE
javdb cookie连接失败

### ISSUE THREAD

**Issue by ne7erland** [sqzw-x/mdcx#171]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

0321最新

### 描述你的问题

clash全局代理TUN模式开启 ，网页正常打开，cookie就是连不上。关掉代理，切换免翻地址后同样不行。

JavDb 连接失败！请检查网络或代理设置！ https://javdb.com/v/D16Q5?locale=zh
Error: Failed to perform, ErrCode: 43, Reason: 'Failed sending HTTP request'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by ne7erland** [comment]
切换免翻地址，软件上也更改好后报：

 JavDb 连接失败！请检查网络或代理设置！ https://javdb521.com/v/D16Q5?locale=zh
Error: Failed to perform, ErrCode: 35, Reason: 'Recv failure: Connection was reset'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

**Comment by a1139036147** [comment]
我也是这样的问题

**Comment by a1139036147** [comment]
已找到解决办法，网址要用http://javdb.com
https由于某些cookies 是HTTP request Only，所以会报错。希望后续更新作者能修复这个问题
![QQ图片20240423103344](https://github.com/sqzw-x/mdcx/assets/63767044/b1a81860-861f-4ced-82a7-a25d8b4f9d57)

**Comment by xmasrain** [comment]
同样的问题

**Comment by zhshp2008** [comment]
> 已找到解决办法，网址要用http://javdb.com https由于某些cookies 是HTTP request Only，所以会报错。希望后续更新作者能修复这个问题 ![QQ图片20240423103344](https://private-user-images.githubusercontent.com/63767044/324667222-b1a81860-861f-4ced-82a7-a25d8b4f9d57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODcyMjgsIm5iZiI6MTcxNDE4NjkyOCwicGF0aCI6Ii82Mzc2NzA0NC8zMjQ2NjcyMjItYjFhODE4NjAtODYxZi00Y2VkLTgyYTctYTI1ZDhiNGY5ZDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAzMDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNTIyOGM1NjE2ZWIyNDEyODg0ZWUzNWY2ZWI2ZWE2YTBjNjU2ZGI2Mjk4M2VlOTFkYjU2NzExOTY0Mzg0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IbTLeTA_6qmUX6HVwFpaIpgqbgPnb-TcmRhIyZ98yy4)

按照此办法已解决，不管是翻不翻墙的地址，去除前面的www即可例，https://javdb366.com

**Comment by ne7erland** [comment]
网址设置设成http://javdb.com 后

chrome强制进入http://javdb.com提取cookie，填入显示

 ❌ JavDb Cookie 无效！请重新填写！

是我操作有什么问题吗
设置免翻地址也一样

**Comment by a1139036147** [comment]
> 网址设置设成http://javdb.com 后
> 
> chrome强制进入[http://javdb.com提取cookie，填入显示](http://javdb.com%E6%8F%90%E5%8F%96cookie%EF%BC%8C%E5%A1%AB%E5%85%A5%E6%98%BE%E7%A4%BA)
> 
> ❌ JavDb Cookie 无效！请重新填写！
> 
> 是我操作有什么问题吗 设置免翻地址也一样

提取cookies不要进入http啊。。。
