### ISSUE TITLE
硬连接失败

### ISSUE THREAD

**Issue by Vic-TT** [sqzw-x/mdcx#176]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

https://github.com/sqzw-x/mdcx/commit/f49516adda5d569f9fbdfab12ec084476cf66b23

### 描述你的问题

环境：绿联云，通过smb挂载访问
文件夹：原始文件夹为NAS D1盘下的A文件夹，目标文件夹为D1盘下的B文件夹，均是Nas中的同一个盘
使用了MAC和Windows都尝试过，无法建立硬连接，会失败。手动从文件管理器中可以正常创建文件夹及文件，但是MCDX报无权限无法创建。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Vic-TT** [comment]
Windows已尝试过使用管理员权限

**Comment by chenstarsQ** [comment]
我有同样的问题，极空间nas挂载，不使用管理员权限报错“创建硬链接失败”，开启管理员权限目录中看不到极空间挂载的目录

**Comment by chenstarsQ** [comment]
更新，不要使用挂载方式，使用SMB共享的方式进行刮削，可以正常创建硬链接
