### ISSUE TITLE
发现了很奇怪的问题。

### ISSUE THREAD

**Issue by zyzhj520** [sqzw-x/mdcx#18]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

043010-361
012318-589
033114-572
051916-165
062709-100
080809-134
081018-724
082710-465
102309-198
090111-795
122415-053
xxx-av-22115
xxx-av-22116
以上全部在最新版本MDCx-120231226里刮削都失败，还有MDCx-120231219也失败，于是我使用了老版本MDCx-120231118全部刮削成功

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
参考 #10
这是因为类似 `111111-111` 的番号，在网站上的标准名称可能是不同的，有的是 `111111-111`，还有的是 `111111_111`，似乎跟片商有关系，而发布资源的人可能命名不规范，混用两种格式。我将回退此更改，后续看下有什么改进措施吧
