### ISSUE TITLE
Jellyfin头像刮削

### ISSUE THREAD

**Issue by jinhua2323** [sqzw-x/mdcx#19]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

Jellyfin头像无法刮削，下载头像文件存储路径错误

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by jinhua2323** [comment]
jellyfin演员头像正确默认存储路径C:\ProgramData\Jellyfin\Server\metadata\People\演员名字首字\演员名字\poster.jpg。
gfriends仓库刮削后需手动重命名演员jpg后自建对应文件夹。不知能否修复自动。

**Comment by sqzw-x** [comment]
mdcx 通过 jellyfin 的 api 上传演员头像，其它工作均由 jellyfin 自己完成
