### ISSUE TITLE
使用mapping actor會將 "坂" 誤翻譯為 "阪"

### ISSUE THREAD

**Issue by shiuh67** [sqzw-x/mdcx#194]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

MDCx-daily_release-windows-x86_64-f49516ad

### 描述你的问题

在開啟演員名稱映設的時候，如果選的是繁體中文並且開啟演員映射，不管在映射表有沒有資料 演員名稱有"坂"的都會變成"阪"
但在繁體中文內這兩個字都是個別存在的
關閉演員映射則正常，選擇簡體中文及日文開啟演員映射也正常

繁體中文 阪 及 坂 字典說明頁面
阪 [阜部-4畫-共7畫]
https://dict.revised.moe.edu.tw/dictView.jsp?ID=248&la=0&powerMode=0

坂 [土部-4畫-共7畫]
https://dict.revised.moe.edu.tw/dictView.jsp?ID=247&la=0&powerMode=0

### 如何复现

1. 前往 '設置'
2. 点击 '翻譯'
3. 滑动到 '演員'
4. 出现问题 選擇中文繁體並選使用演員映射表翻譯演員
5. 開始刮削
6. 演員名稱如果有 "坂" 的都會變成 "阪"
7. 使用簡體中文 跟 日文 以及關閉演員映射都正常

### 预期行为

繁體中文刮削 早坂ひめ 時候，應為 早坂ひめ 而不是變成 早阪ひめ

繁體中文刮削 小坂七香 時候，應為 小坂七香 而不是變成 小阪七香

### 相关 Logs

```Text
    🙋🏻‍ 演员 
    ====================================
    🌐 来源优先级：javbus -> airav_cc -> iqqtv -> freejavbt -> jav321 -> dmm -> avsex -> lulubar
    🟢 javbus (成功)
     ↳ 早坂ひめ
-----------------------------------

  🔴 Translation failed!(Deepl)(4s) Error: 网页接口请求失败! 错误：429 Client Error:  for url: https://www2.deepl.com/jsonrpc
 🔴 Translation failed!(Youdao)(4s) Error: 返回数据未找到翻译结果！返回内容：{'errorCode': 50}
 🍀 Translation done!(Google)(5s)
     number       : SONE-087
     letters      : SONE
     has_sub      : 中文字幕
     mosaic       : 有碼
     title        : 交わる體液、濃密セックス 完全ノーカットスペシャル
     originaltitle: 交わる体液、濃密セックス 完全ノーカットスペシャル
     actor        : 早阪ひめ
     outline      : 體液互換，激烈性愛，完全未剪特別
○○天后我就要成爲AV女優了！成爲SNS熱門話題的AV倒計時美少女「早阪姬」第三彈！ ！一直推崇AV的美少女的真實姿勢，與未剪裁、淫蕩的SEX 3製作的精緻肉體交……（略）
     originalplot : ○○日後にAV女優になります！SNSで話題沸騰のAVカウントダウン美少女「早坂ひめ」第3弾！！AVに憧れ続けた美少女のリアルな姿態、ノーカットで絡み合う絶品ボディ欲情SEX3本番。「もっと欲しいの……（略）
     tag          : 1080P，SONE，早阪ひめ，單體作品，美少女，巨乳，潮吹，接吻，乳交，DMM獨家，中文字幕，有碼，系列: 交わる體液、濃密セックス，片商: S1 NO.1 STYLE，發行: S1 NO.1 STYLE
     release      : 2024-03-22
     year         : 2024
     runtime      : 131
     score        : 3.0
     series       : 交わる体液、濃密セックス
     director     : ラムチョップ
     studio       : S1 NO.1 STYLE
     publisher    : S1 NO.1 STYLE
     trailer      : http://cc3001.dmm.co.jp/litevideo/freepv/s/son/sone00087/sone00087_mhb_w.mp4
     website      : https://www.javbus.com/SONE-087
```

### 截图

[2024-05-27-17-39-54.txt](https://github.com/sqzw-x/mdcx/files/15463184/2024-05-27-17-39-54.txt)

### 还有别的吗？

在 zhcdict.json 裡面有找到
https://github.com/sqzw-x/mdcx/blob/master/resources/zhconv/zhcdict.json#L13712

第13712行，強制轉換 "坂": "阪",

**Comment by fliclumsy** [comment]
可以自己修改mapping的那个文件，猜测是作者提供的文件里面没有区分这两个字

**Comment by shiuh67** [comment]
> 可以自己修改mapping的那个文件，猜测是作者提供的文件里面没有区分这两个字

使用mapping的文件後，也會被強制轉換，演員那個部份應該可以不再透過 zhcdict.json 轉換才對
演員勾選後應該是 mapping優先級要高於 簡繁轉換，可是看起來是不管有沒有mapping，只要繁體翻譯有 坂 就去對應成 阪
需要轉換的應該是 標題，內容文件，又或者把 zhcdict.json 修正，可以刪除該字轉換，又或者將 坂還是轉為坂才對
因為 resources/zhconv/zhcdict.json 這個應該是簡繁轉換，而不是日文轉中文
簡體中文跟繁體中文應該都有 "坂" 以及 "阪" 這兩個字，所以這兩個字應該不需要特地在轉換
