### ISSUE TITLE
Win可执行文件下载系统自带防护报毒

### ISSUE THREAD

**Issue by Devourd** [sqzw-x/mdcx#2]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

已检测：Trojan:Win32 Wacatac.B!ml
状态已隔离
隔离的文件在不会损害设备的受限区域内。系统将
自动除它们。

详细信息：这个程序很危险，而且执行来自攻击者的
命令。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by kofzhanganguo** [comment]
杀毒软件误报，关闭杀软，或者是到白名单吧。

**Comment by sqzw-x** [comment]
误报。这是因为没有对可执行文件进行签名，如不放心可使用源代码自行打包
