### ISSUE TITLE
裁剪页面是否可以选择不裁剪，直接复制背景图，并添加水印

### ISSUE THREAD

**Issue by chaomarks** [sqzw-x/mdcx#203]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

MDCx-120240321

### 描述你的问题

有些文件无法刮削到图片，然后自己找到图片，但是封面图不需要裁剪，又需要添加水印，所以可不可以在读取模式后读取后点击图片裁剪页面加上（不裁剪直接复制的选项），或者将下面的裁剪尺寸的大小可以覆盖整个图

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

.

### 相关 Logs

```Text
.
```

**Comment by smart0114** [comment]
使用中确实有手动替换封面图需要只添加水印 不知道可不可以手动添加
