### ISSUE TITLE
最新版图片裁剪bug

### ISSUE THREAD

**Issue by anyingxiuluo** [sqzw-x/mdcx#206]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

最新版图片裁剪，调节裁剪宽度和高度时裁剪框不会动，并且默认裁剪框尺寸似乎改变了
![微信截图_20240606172550](https://github.com/sqzw-x/mdcx/assets/125189022/90a783b2-7b66-47aa-905b-db75207848b8)

### 描述你的问题

1

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
新的裁剪功能，鼠标拖动可移动裁剪框，上下左右均可，下方拖动条仅用于调整裁剪框大小，最大可与原图一样大
