### ISSUE TITLE
有道翻译失效，谷歌会将翻译的标题插入进简介，deepl没问题

### ISSUE THREAD

**Issue by xiaoyaohg** [sqzw-x/mdcx#207]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

Ver.20240321

### 描述你的问题

有道翻译失效，谷歌会将翻译的标题插入进简介，deepl没问题
![QQ截图20240607051447](https://github.com/sqzw-x/mdcx/assets/171981652/299f38a4-8cc2-4109-b14a-934356a48f1c)
![QQ截图20240607054115](https://github.com/sqzw-x/mdcx/assets/171981652/a88eccbe-e348-4b60-840d-2c092ccc92ce)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
🍀 Translation done!(Google)(0s)
     number       : SONE-196
     letters      : SONE
     mosaic       : 有码
     title        : 谁もが憧れるバリキャリOLの周末メス犬日记 现场男の汗臭チ〇ポが生きがいとは、绝対に言えない。
     originaltitle: 誰もが憧れるバリキャリOLの週末メス犬日記 現場男の汗臭チ〇ポが生きがいとは、絶対に言えない。
     actor        : 楓ふうあ
     outline      : 人人敬佩的有礼貌的办公室女士的周末母狗日记。你永远不能说，拥有一个在外地工作的男人出汗的阴茎就是生活的目的。
主角 Kaede Fua 是一位忙碌的职业女性，为一家大型总承包商工作。无论是在办公室……（略）
     originalplot : 主人公の楓ふうあは、大手ゼネコンに勤務する、バリバリのキャリアウーマン。内勤でも現場でも、部下や下請けに躊躇なくダメ出しをする。優秀な彼女は上司からも好かれているが、男にも立場にも媚びず、週末の誘……（略）
     tag          : SONE，枫ふうあ，M女，职业装，痴女，苗条，单体作品，深喉，DMM独家，有码，片商: S1 NO.1 STYLE，发行: S1 NO.1 STYLE
     release      : 2024-05-24
     year         : 2024
     runtime      : 117
     score        : 3.5
     director     : キョウセイ
     studio       : S1 NO.1 STYLE
     publisher    : S1 NO.1 STYLE
     trailer      : https://cc3001.dmm.co.jp/litevideo/freepv/s/son/sone00196/sone00196hhb.mp4
     website      : https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=sone00196/
 🍀 Folder done! (new)
 🍀 Thumb done! (javbus)(1s) 
 🍀 Fanart done! (copy thumb)(0s)
 🍀 Poster done! (thumb right)(0s)
 🍀 Nfo done! (new)(0s)
 🍀 Movie done! 


 🍀 Translation done!(Deepl)(6s)
     number       : SONE-196
     letters      : SONE
     mosaic       : 有码
     title        : 一个忙碌的上班族的周末贱狗日记，每个人都渴望成为其中的一部分。 你永远不能说，一个野外男人汗流浃背、臭气熏天的老二是他活着的唯一理由。
     originaltitle: 誰もが憧れるバリキャリOLの週末メス犬日記 現場男の汗臭チ〇ポが生きがいとは、絶対に言えない。
     actor        : 楓ふうあ
     outline      : 主人公 Fūa Kaede 是一位勤奋工作的职业女性，供职于一家大型总承包商。 无论是在公司内部还是在工地上，她都会毫不犹豫地给下属和分包商一个下马威。 她才华横溢，深得上司赏识，但她对男人和自己……（略）
     originalplot : 主人公の楓ふうあは、大手ゼネコンに勤務する、バリバリのキャリアウーマン。内勤でも現場でも、部下や下請けに躊躇なくダメ出しをする。優秀な彼女は上司からも好かれているが、男にも立場にも媚びず、週末の誘……（略）
     tag          : SONE，枫ふうあ，M女，职业装，痴女，苗条，单体作品，深喉，DMM独家，有码，片商: S1 NO.1 STYLE，发行: S1 NO.1 STYLE
     release      : 2024-05-24
     year         : 2024
     runtime      : 117
     score        : 3.5
     director     : キョウセイ
     studio       : S1 NO.1 STYLE
     publisher    : S1 NO.1 STYLE
     trailer      : https://cc3001.dmm.co.jp/litevideo/freepv/s/son/sone00196/sone00196hhb.mp4
     website      : https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=sone00196/
 🍀 Folder done! (new)
```

**Comment by anyingxiuluo** [comment]
标题翻译似乎失效了

**Comment by anyingxiuluo** [comment]
deepl封的概率太高了，翻译一两个就开始封了，api又需要国外信用卡验证，有好的办法吗

**Comment by yanggang0225** [comment]
> deepl封的概率太高了，翻译一两个就开始封了，api又需要国外信用卡验证，有好的办法吗

我是在淘宝上买了两个，没有问题

**Comment by anyingxiuluo** [comment]
> > deepl封的概率太高了，翻译一两个就开始封了，api又需要国外信用卡验证，有好的办法吗
> 
> 我是在淘宝上买了两个，没有问题

买的好像只能用一个月，你用了多久了

**Comment by yanggang0225** [comment]
> > > deepl封的概率太高了，翻译一两个就开始封了，api又需要国外信用卡验证，有好的办法吗
> > 
> > 我是在淘宝上买了两个，没有问题
> 
> 买的好像只能用一个月，你用了多久了

4.22 买的，现在还能正常用，我是买了两个换着用的。你说的被封，是不是翻译的量太大了，超过免费的上限了啊

**Comment by anyingxiuluo** [comment]
> > > > deepl封的概率太高了，翻译一两个就开始封了，api又需要国外信用卡验证，有好的办法吗
> > > 
> > > 
> > > 我是在淘宝上买了两个，没有问题
> > 
> > 
> > 买的好像只能用一个月，你用了多久了
> 
> 4.22 买的，现在还能正常用，我是买了两个换着用的。你说的被封，是不是翻译的量太大了，超过免费的上限了啊

不是免费配额用尽的原因，我猜测是因为淘宝上的api都是用虚拟信用卡注册的，时间长了信用卡不能二次验证了就会被封号，你买的也是10元左右一个的那种么

**Comment by yanggang0225** [comment]
> > > > > deepl封的概率太高了，翻译一两个就开始封了，api又需要国外信用卡验证，有好的办法吗
> > > > 
> > > > 
> > > > 我是在淘宝上买了两个，没有问题
> > > 
> > > 
> > > 买的好像只能用一个月，你用了多久了
> > 
> > 4.22 买的，现在还能正常用，我是买了两个换着用的。你说的被封，是不是翻译的量太大了，超过免费的上限了啊
> 
> 不是免费配额用尽的原因，我猜测是因为淘宝上的api都是用虚拟信用卡注册的，时间长了信用卡不能二次验证了就会被封号，你买的也是10元左右一个的那种么

![Screenshot_20240704_092206.jpg](https://github.com/sqzw-x/mdcx/assets/132535087/3544a4de-b0b8-4fb2-bbe9-636eef16ae6d)

是的啊，8.5 一个的

**Comment by zjxuzhj** [comment]
老哥有空处理下谷歌的这个问题
