### ISSUE TITLE
轻量NFO批量修改器

### ISSUE THREAD

**Issue by cgkings** [sqzw-x/mdcx#211]
大佬
你好
因为网盘挂载操作比较慢，且容易触发问题，我想基于Mdcx写一个轻量NFO批量修改器
但是不会代码，就让chatgpt给生成了一个，见附件
但是始终有bug，且比较难修复，目前市面上还没有这样的软件，看看大佬是不是能截取mdcx部分功能做一个，其实就是去除了刮削功能的NFO修改器
![image](https://github.com/sqzw-x/mdcx/assets/58586625/742266b8-4f3f-479c-a463-decc00694854)

**Comment by cgkings** [comment]
![image](https://github.com/sqzw-x/mdcx/assets/58586625/4cc6236d-b6df-4c91-a0af-0f06d1760afc)
最新一版，始终没法解决类型和标签重复显示的问题，我让chatgpt参考mdcx的标签显示，逗号分隔，它还是搞不定

**Comment by cgkings** [comment]
暂时找不到大佬帮忙修改，只能临时做个简化版的
![image](https://github.com/sqzw-x/mdcx/assets/58586625/39bdc544-013d-49a4-b505-e64999ca769f)
[NFOEditor.zip](https://github.com/user-attachments/files/16017242/NFOEditor.zip)

**Comment by cgkings** [comment]
![image](https://github.com/sqzw-x/mdcx/assets/58586625/03cf4333-7b57-46de-aa71-541368308eb7)
类别和标签问题搞定了
下一步，琢磨怎么弄批量修改

**Comment by cgkings** [comment]
![image](https://github.com/sqzw-x/mdcx/assets/58586625/ed4c0d3d-9516-45ef-bfa2-66955b09fa3e)
快接近完整了

**Comment by cgkings** [comment]
没办法，大佬比较忙，只能自力更生了
https://github.com/cgkings/NFO.Editor
![image](https://github.com/sqzw-x/mdcx/assets/58586625/f09b50ea-6bbb-4566-bfeb-1fff734311cb)

**Comment by adaelves** [comment]
兄弟你这个牛逼呀！

**Comment by cgkings** [comment]
![image](https://github.com/sqzw-x/mdcx/assets/58586625/c40f7b04-ad02-47b7-8de3-1985735511e6)
增加了播放功能，后面再移植一下mdcx的图片裁剪功能，这就是去除刮削功能的mdcx

**Comment by anyingxiuluo** [comment]
> ![image](https://private-user-images.githubusercontent.com/58586625/344596948-c40f7b04-ad02-47b7-8de3-1985735511e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzMyMjgsIm5iZiI6MTcxOTgzMjkyOCwicGF0aCI6Ii81ODU4NjYyNS8zNDQ1OTY5NDgtYzQwZjdiMDQtYWQwMi00N2I3LThkZTMtMTk4NTczNTUxMWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDExMjIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxY2QwY2EzMDUyZThjNDYyOTY0YjFlNTg4ZDE2NWRhZGZiMjU5NmY3MGI1ZjVmZDcwNTVmODQzY2ZmNmJiMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FN3uzCXhJcxn0gZV5qA8gK_Dv23P1j5Iz3tToptYvrA) 增加了播放功能，后面再移植一下mdcx的图片裁剪功能，这就是去除刮削功能的mdcx

加个批量翻译功能

**Comment by cgkings** [comment]
![image](https://github.com/sqzw-x/mdcx/assets/58586625/0be5f667-5f9e-4f73-b71e-3afdb0d2fae1)

**Comment by cgkings** [comment]
![PixPin_2024-07-11_14-44-19](https://github.com/sqzw-x/mdcx/assets/58586625/c47dd4e7-2e0f-4b97-bf42-ee310341a8d8)
https://github.com/cgkings/NFO.Editor
完成体了

**Comment by deardeer7** [comment]
您也是大佬！用来管理影片很实用，感谢！

**Comment by gejianya** [comment]
看到这里发现chatGPT真的很有用哇，怪不得要收费，我是产品经理，这样看来，以后我画好原型图，搭配ChatGPT写代码，自己也能发布（简单）软件了，看来程序员（前端低级的）地位以后有变化。

**Comment by gejianya** [comment]
目前来看，美工和UI设计师以后大概率部分要被ai替代，一些初级程序员ai也可以替代，那么产品经理ai是否能够替代呢，应该没那么容易。
