### ISSUE TITLE
javdb javbus 等都不能用了，包括javdb的coolie。

### ISSUE THREAD

**Issue by kejizhihui** [sqzw-x/mdcx#217]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

javdb javbus 等都不能用了，包括javdb的coolie。

### 描述你的问题

javdb javbus 等都不能用了，包括javdb的coolie。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by zzwtsy** [comment]
有相关日志吗

**Comment by Crispy-Bones** [comment]
检查一下这两个网站是否使用了自定义网址, 路径: 设置->网络->网址设置

**Comment by Chenastron** [comment]
javdb的cookie格式似乎是有更新

**Comment by Crispy-Bones** [comment]
javdb的cookie无效的原因之一是开启了日本代理, 而在mdcx运行时就算切换为其他代理依然无效, 没深究内在逻辑是什么.
暂时解决方法: 切换非日本代理, 重启mdcx, 重新填写cookie

**Comment by ArtechZhu** [comment]
> javdb的cookie无效的原因之一是开启了日本代理, 而在mdcx运行时就算切换为其他代理依然无效, 没深究内在逻辑是什么. 暂时解决方法: 切换非日本代理, 重启mdcx, 重新填写cookie

HK和TW的代理同样不行

**Comment by an-other-leon** [comment]
> javdb的cookie无效的原因之一是开启了日本代理, 而在mdcx运行时就算切换为其他代理依然无效, 没深究内在逻辑是什么. 暂时解决方法: 切换非日本代理, 重启mdcx, 重新填写cookie

台湾和香港同样不行，现在有什么解决办法了吗？（客户端已最新v120240924, MDCx-daily_release-windows-x86_64-540b35be）

**Comment by Crispy-Bones** [comment]
> > javdb的cookie无效的原因之一是开启了日本代理, 而在mdcx运行时就算切换为其他代理依然无效, 没深究内在逻辑是什么. 暂时解决方法: 切换非日本代理, 重启mdcx, 重新填写cookie
> 
> 台湾和香港同样不行，现在有什么解决办法了吗？（客户端已最新v120240924, MDCx-daily_release-windows-x86_64-540b35be）

1. 请先确认浏览器是否可以访问网站
2. 确保mdcx中网络代理处于开启状态
3. 检查mdcx是否使用了自定义网址, 该网址能否使用浏览器访问
4. 确保cookie复制正确, 重启mdcx重新填写cookie, 多试几次
