### ISSUE TITLE
刮削过程文件被意外删除

### ISSUE THREAD

**Issue by PLA0185** [sqzw-x/mdcx#224]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

MDCx-120240321-windows-x86_64-ecaf015e

### 描述你的问题

我在使用刮削的时候在还没完成之前点击了中止，结果把我现有的影片全部删除了，出现了两次了，第一次不记得怎么删除的了，全没了，第二次就是刚开始我发现目录点错了之后马上终止，导致我的影片全部被删除，无法恢复。

### 如何复现

1. 点击刮削
2. 在任务刚刚开始时 点击 中止刮削
3. 刮削未结束，一个个提示任务失败
4. 刮削还未终止时回去看目录影片全部被删除

**Comment by yanggang0225** [comment]
哥们你好惨啊，之前的磁链有保存吗？

**Comment by PLA0185** [comment]
> 哥们你好惨啊，之前的磁链有保存吗？

就是第一次删除文件的时候，里面内容在磁盘已经完全删除干净了，但是程序还能识别出来，名字也能在失败栏里出现，但是就是提示文件不存在，所以截图保留了一部分

**Comment by PLA0185** [comment]
[桌面.zip](https://github.com/user-attachments/files/16229154/default.zip)


> 建议你上传脱敏后的配置文件和完整的日志

**Comment by PLA0185** [comment]
> > [桌面.zip](https://github.com/user-attachments/files/16229154/default.zip)
> > > 建议你上传脱敏后的配置文件和完整的日志
> 
> 这个问题能稳定复现吗，建议可以复制一份文件再次尝试，能稳定复现的问题才有处理的可能。另外日志中没有看到可疑的行为

我刚刚尝试了一下，暂时复现不了，只能再观望了，不过上一次已经是第二次了。感谢大佬回复

**Comment by PLA0185** [comment]
> > > > [桌面.zip](https://github.com/user-attachments/files/16229154/default.zip)
> > > > > 建议你上传脱敏后的配置文件和完整的日志
> > > 
> > > 
> > > 这个问题能稳定复现吗，建议可以复制一份文件再次尝试，能稳定复现的问题才有处理的可能。另外日志中没有看到可疑的行为
> > 
> > 
> > 我刚刚尝试了一下，暂时复现不了，只能再观望了，不过上一次已经是第二次了。感谢大佬回复
> 
> 搜了下以前也有类似issue，但是没有提供任何日志和线索细节，只会输出情绪，后来就关闭了。既然已经有类似的案例，我想这个问题肯定是真实存在的，但概率很低，无法人工复现。你被删除两次，是不是每次都是先开始刮削，未完成时手动停止线程，停止完后在硬盘中就找不到文件了？回收站也没有吗？只是删除了等待刮削的文件还是说待刮削目录全部清空了一个文件都不剩？

第一次我记不大清了，当时脑子也比较懵没记住，第二次是比较清楚的，第一次当时想的是好像emby海报啥的识别不出来，然后把刮削好的重新拿出来然后解散了文件夹删除了nfo文件，就剩下视频文件，然后就忘了是怎么操作的了，反正回去文件就消失了，但是终止之后继续上次的进程还是能识别出原来的文件名番号但是就是提示任务不存在了，我才回去看发现视频不见了，第二次是模式选错了然后终止，当时文件比较少但是进程里面的十个文件都消失了，ctrl+z无法恢复，回收站里面也没有，目录还在，但是里面的文件都没有了，硬盘和软件视频相关的目录位置都找过了，确实没有。没事我文件没了再下就行了，感谢大佬这么好的软件！

**Comment by PLA0185** [comment]
> > > > > > [桌面.zip](https://github.com/user-attachments/files/16229154/default.zip)
> > > > > > > 建议你上传脱敏后的配置文件和完整的日志
> > > > > 
> > > > > 
> > > > > 这个问题能稳定复现吗，建议可以复制一份文件再次尝试，能稳定复现的问题才有处理的可能。另外日志中没有看到可疑的行为
> > > > 
> > > > 
> > > > 我刚刚尝试了一下，暂时复现不了，只能再观望了，不过上一次已经是第二次了。感谢大佬回复
> > > 
> > > 
> > > 搜了下以前也有类似issue，但是没有提供任何日志和线索细节，只会输出情绪，后来就关闭了。既然已经有类似的案例，我想这个问题肯定是真实存在的，但概率很低，无法人工复现。你被删除两次，是不是每次都是先开始刮削，未完成时手动停止线程，停止完后在硬盘中就找不到文件了？回收站也没有吗？只是删除了等待刮削的文件还是说待刮削目录全部清空了一个文件都不剩？
> > 
> > 
> > 第一次我记不大清了，当时脑子也比较懵没记住，第二次是比较清楚的，第一次当时想的是好像emby海报啥的识别不出来，然后把刮削好的重新拿出来然后解散了文件夹删除了nfo文件，就剩下视频文件，然后就忘了是怎么操作的了，反正回去文件就消失了，但是终止之后继续上次的进程还是能识别出原来的文件名番号但是就是提示任务不存在了，我才回去看发现视频不见了，第二次是模式选错了然后终止，当时文件比较少但是进程里面的十个文件都消失了，ctrl+z无法恢复，回收站里面也没有，目录还在，但是里面的文件都没有了，硬盘和软件视频相关的目录位置都找过了，确实没有。没事我文件没了再下就行了，感谢大佬这么好的软件！
> 
> 我并不是仓库的owner，纯业余，也只是尽我所能的帮修一修能搞定的bug。也许这个问题和线程的调度以及操作系统相关，这个就比较深了，我是没有能力能解决的，下次再出现也记得保存好日志以及多回忆回忆细节。看后面会不会添加一些调试信息帮助诊断吧。另外尽量不要在线程运行时尤其是刮削时停止，我感觉这个地方有问题，比较卡，宁愿让他刮削完成或者等到间歇刮削停顿时再停止。

我发现了，可能是因为在刮削过程当中，有的重复文件只有视频没有目录，但是我选择删除文件夹和视频这个选项，就连带着上级目录一起删除了，可能是这个原因引起的

**Comment by maple-j** [comment]
我之前也被全删了，回退到原版不会删，现在回忆之前看到的日志错误原因是关于目录的错误，我用的是nas的网络共享资源目录，\\nas
希望能有帮助
