### ISSUE TITLE
javdb网站无法刮削

### ISSUE THREAD

**Issue by 999huppao** [sqzw-x/mdcx#235]
每日构建哪里下载了最新版本，刮不了javdb，自从javdb加入真人验证后就刮不了。我不知是我个人原因还是大家都刮不了
![Snipaste_2024-07-27_12-48-31](https://github.com/user-attachments/assets/488df823-3235-48e7-9795-969f3605396d)

**Comment by Seewr** [comment]
我的也是搞不了
