### ISSUE TITLE
javdb网络连接不上

### ISSUE THREAD

**Issue by 999huppao** [sqzw-x/mdcx#236]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

9704c1dc

### 描述你的问题

javdb无法刮削，检查cookie显示连接失败，请检查网络设置，已经设置全局代理，网页直接打开没问题

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![Snipaste_2024-07-27_12-48-31](https://github.com/user-attachments/assets/869afbc5-6b9d-4460-9d3d-b10e4c57ed2f)
![Snipaste_2024-07-28_21-41-05](https://github.com/user-attachments/assets/500228a6-e219-4149-8637-372bc5019aef)

### 还有别的吗？

看了之前的issue，将https改为http,无效

**Comment by iamjimmycheng** [comment]
我一直能用，我系统显示连接的是https://javdb.com，不是https://javdb366.com

**Comment by dxyad** [comment]
> 我一直能用，我系统显示连接的是[https://javdb.com，不是https://javdb366.com](https://javdb.com%EF%BC%8C%E4%B8%8D%E6%98%AFhttps://javdb366.com)

要挂代理吗

**Comment by 999huppao** [comment]
> 我一直能用，我系统显示连接的是 [https://javdb.com，不是 https://javdb366.com](https://javdb.com%EF%BC%8C%E4%B8%8D%E6%98%AFhttps://javdb366.com)

这个我都试过，这就是一个免翻不免翻的区别，换了好几个IP也不行，不过你能用而我不能用的话那就应该是我这边自己的问题了。

**Comment by iamjimmycheng** [comment]
> > 我一直能用，我系统显示连接的是[https://javdb.com，不是https://javdb366.com](https://javdb.com%EF%BC%8C%E4%B8%8D%E6%98%AFhttps://javdb366.com)
> 
> 要挂代理吗

当然要挂啊

**Comment by 999huppao** [comment]
> 我一直能用，我系统显示连接的是[https://javdb.com，不是https://javdb366.com](https://javdb.com%EF%BC%8C%E4%B8%8D%E6%98%AFhttps://javdb366.com)

你用的是每日构建里面最新的版本吗？

**Comment by 999huppao** [comment]
> ### 在提问之前...
> * [x] 我已经搜索了现有的 issues
> * [x] 我在提问题之前至少花费了 5 分钟来思考和准备
> 
> ### 你使用版本的 commit hash
> [9704C1D](https://github.com/sqzw-x/mdcx/commit/9704c1dc06578abb04defd62eaa2140c93596fc3)
> 
> ### 描述你的问题
> javdb无法刮削，检查cookie显示连接失败，请检查网络设置，已经设置全局代理，网页直接打开没问题
> 
> ### 如何复现
> 1. 前往 '...'
> 2. 点击 '....'
> 3. 滑动到 '....'
> 4. 出现问题
> 
> ### 预期行为
> _没有回应_
> 
> ### 相关 日志
> _没有回应_
> 
> ### 截图
> ![Snipaste_2024-07-27_12-48-31](https://private-user-images.githubusercontent.com/88283575/352816866-869afbc5-6b9d-4460-9d3d-b10e4c57ed2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjI0MTUsIm5iZiI6MTcyNDE2MjExNSwicGF0aCI6Ii84ODI4MzU3NS8zNTI4MTY4NjYtODY5YWZiYzUtNmI5ZC00NDYwLTlkM2QtYjEwZTRjNTdlZDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEzNTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwODc3ZjU2OGYxN2QwODMzZDdiYmU3YmY1MDk0MTE2MGVkZTRkY2UzN2Q0M2Y4NmY4MmM5MWM5ZGQxOThkYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DaIF1YjnIJUSZBcuLf7-4kkR_Vtd9Olzk3VGxN7Ddrc) ![Snipaste_2024-07-28_21-41-05](https://private-user-images.githubusercontent.com/88283575/352816873-500228a6-e219-4149-8637-372bc5019aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjI0MTUsIm5iZiI6MTcyNDE2MjExNSwicGF0aCI6Ii84ODI4MzU3NS8zNTI4MTY4NzMtNTAwMjI4YTYtZTIxOS00MTQ5LTg2MzctMzcyYmM1MDE5YWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEzNTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ODEyNjlkNTE1YjUxMDY4YTE1NTFhMjBmODNkYjllOGJjNjEwZWMwN2ZjMzRhMmExMjQwZDMwMmM4ZGJmYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8R4at5AWW6Tb3Z8zKxufeStJKtFIVHdhdp4EwZtBRHY)
> 
> ### 还有别的吗？
> 看了之前的问题，将https改为http，无效
