### ISSUE TITLE
发现了新的FC2刮削站点，它有演员信息，这是FC2特别需要而目前站点没有的，希望能添加到mdcx中。

### ISSUE THREAD

**Issue by YaoYouGuan** [sqzw-x/mdcx#243]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

928724b6

### 描述你的问题

在每日构建下载的 MDCx-daily_release-windows-x86_64-928724b6
打开看到FC2刮削网址还是 FC2 FC2HUB FC2CLUB 这些
最近发现了 https://fc2ppvdb.com/articles/4382449 ，它是日文网站，更新速度快，作品收录齐全，最主要的是它有网友补全演员信息，如图。
演员信息这块，原本是Javdb有的，现在它FC2板块基本弃了，更新慢，还有缺漏。
![20240814225130980](https://github.com/user-attachments/assets/6312fcce-44f5-4e13-a76e-6a4344c17405)
![20240814225139601](https://github.com/user-attachments/assets/3eb65a49-f8d9-486e-8eea-4ff9534ae167)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by YaoYouGuan** [comment]
这个2024-08-10收录的作品下，网友认出演员，在评论中补充了演员信息，网站是很快采纳，添加了演员信息。

https://fc2ppvdb.com/articles/4515706
![chrome_FRqJqBXu7w](https://github.com/user-attachments/assets/cc6f8af8-0a24-4cee-98df-385b74e65504)

**Comment by sqzw-x** [comment]
看了下, 这网站有 cf 盾, 而且 cookie 也加密了, 有点难搞

**Comment by YaoYouGuan** [comment]
> 看了下，这个网站有cf盾，而且cookie也加密了，有点难搞

啊 那有点可惜了，这个站的演员数据真的很齐全，很难得。
OK 感谢回复。

**Comment by liaox321** [comment]
> 看了下, 这网站有 cf 盾, 而且 cookie 也加密了, 有点难搞

onejav.com  这个网站的FC2也不错，能否考虑添加。可以PR

**Comment by fisheep885357-coder** [comment]
悲报，好像是被封了，看不懂日语，机翻理解可能不太准确，不知道还有没有可能恢复。

**Comment by blacktigermsl** [comment]
有没有新的检索网站出来，这个这么好用结果现在用不了了，很难受😭

**Comment by grapefruit19la** [comment]
我们需要你，快回来吧😭

**Comment by grapefruit19la** [comment]
we need u
