### ISSUE TITLE
用的今天的源码，非执行程序，madouqu抓取不了

### ISSUE THREAD

**Issue by ghxyxll** [sqzw-x/mdcx#248]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

同一网络环境 获取到的url直接在Chrome中可访问
问题大概在100行左右
查看了curl_html函数，未发现明显问题。应该是反爬了？

### 描述你的问题

 ⏰ 15:12:15 [1/3] https://mad----------------------
Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21051 ms: Couldn't connect to server'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

### 如何复现

1. 前往 'madouqu.py'
2. 运行后日志显示443
同一网络环境 获取到的url直接在Chrome中可访问
问题大概在100行左右
查看了curl_html函数，未发现明显问题。应该是反爬了？

### 相关 Logs

```Text
⏰ 15:12:15 [1/3] https://m--------------------------------
Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21051 ms: Couldn't connect to server'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
```

**Comment by 1562170596** [comment]
我也是这样

**Comment by a1233526962** [comment]
等待大佬修复，现在没办法刮国产了

**Comment by jinhua2323** [comment]
静待修复

**Comment by ghxyxll** [comment]
网站更新反爬措施，无限debugger，无法获取源码，F12都开不了

**Comment by a1233526962** [comment]
> 网站更新反爬措施，无限debugger，无法获取源码，F12都开不了

好像其他网站也不行，没有其他办法了吗

**Comment by 1562170596** [comment]
感谢大佬，我把网络里的代理设置点了 现在可以刮削了

**Comment by a1233526962** [comment]
> 感谢大佬，我把网络里的代理设置点了 现在可以刮削了

请教代理怎么设置呢，以前挂VPN就可以刮了，现在不懂怎么设置软件的代理

**Comment by a1233526962** [comment]
> 感谢大佬，我把网络里的代理设置点了 现在可以刮削了

🌐 [website] madouqu(70s) -> mdtv(3s) -> hdouban(1s) -> cnmdb(28s)
    🌐 madouqu
       请求地址: https://madouqu.com/?s=MD-0322 
       网络请求错误: https://madouqu.com/?s=MD-0322
Error: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to madouqu.com port 443 after 21047 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 
    🌐 mdtv
       搜索地址: https://www.mdpjzip.xyz/index.php/vodsearch/-------------.html {"wd": MD-0322}
       搜索结果: 未匹配到番号！ 
    🌐 hdouban
       搜索地址: https://api.6dccbca.com/api/search?ty=movie&search=MD-0322&page=1&pageSize=12 
       网络请求错误: 530 https://api.6dccbca.com/api/search?ty=movie&search=MD-0322&page=1&pageSize=12  
    🌐 cnmdb
       请求地址: [https://cnmdb.net/MD](https://github.com/sqzw-x/mdcx/issues/%3Ca%20href=)-0322">https://cnmdb.net/MD-0322 
       请求地址: [https://cnmdb.net/MD](https://github.com/sqzw-x/mdcx/issues/%3Ca%20href=)0322">https://cnmdb.net/MD0322 
       请求地址: https://cnmdb.net/MD 0322 
       请求地址: https://cnmdb.net/s0?q=T:\MDTV\2024 
       请求地址: https://cnmdb.net/s0?q=5\1\failed\[SHANA]MD-0322 
       没有匹配的搜索结果
    🔴 标题 获取失败！
 🔴 Data failed!(103s)
 🔴 [Failed] Reason: 没有匹配的搜索结果
 🙊 [Movie] T:\MDTV\2024.5\1\failed\[SHANA]MD-0322.mp4
================================================================================
 🕷 08:11:17 1/31 [SHANA]MD-0322.mp4 刮削完成！用时 103 秒！

**Comment by 1562170596** [comment]
> > 感谢大佬，我把网络里的代理设置点了 现在可以刮削了
> 
> 请教代理怎么设置呢，以前挂VPN就可以刮了，现在不懂怎么设置软件的代理



大概这样设置
![QQ截图20240823082308](https://github.com/user-attachments/assets/64894690-eaca-4033-8973-ad379910d162)
![QQ截图20240823083153](https://github.com/user-attachments/assets/cedaf453-83fc-47da-bc11-16fa30f5f12b)

**Comment by a1233526962** [comment]
> > > 感谢大佬，我把网络里的代理设置点了 现在可以刮削了
> > 
> > 
> > 请教代理怎么设置呢，以前挂VPN就可以刮了，现在不懂怎么设置软件的代理
> 
> 大概这样设置 ![QQ截图20240823082308](https://private-user-images.githubusercontent.com/58887099/360714386-64894690-eaca-4033-8973-ad379910d162.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzM2NzcsIm5iZiI6MTcyNDM3MzM3NywicGF0aCI6Ii81ODg4NzA5OS8zNjA3MTQzODYtNjQ4OTQ2OTAtZWFjYS00MDMzLTg5NzMtYWQzNzk5MTBkMTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAwMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZjNhNGIyYmY5MjE5YWZmNTljYzk3MjE4ZjM0YmQ5Njg0ZmE3M2JjYmEyMzE2NDc1ODk4OGZmMGE2M2UyZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uMwqq4iSlA2lfLeTq08p1gyXCLOF6EL5Aw6NTJl6abE) ![QQ截图20240823083153](https://private-user-images.githubusercontent.com/58887099/360715030-cedaf453-83fc-47da-bc11-16fa30f5f12b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzM2NzcsIm5iZiI6MTcyNDM3MzM3NywicGF0aCI6Ii81ODg4NzA5OS8zNjA3MTUwMzAtY2VkYWY0NTMtODNmYy00N2RhLWJjMTEtMTZmYTMwZjVmMTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAwMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ODZmYTEzY2MyMTU2NTYyODhmMDFjYzUyYWY2NGU1NmQ4NzAzYzllMzJiOTRiZWU1NjZkOTdkNjM0ZmJiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DfM6N467KN1hY6VrZEuaEvZoSe7qtHlZ0RmBofPgOCY)

感谢大佬，一部分7mmtv成功刮削了
