### ISSUE TITLE
演员头像补全问题

### ISSUE THREAD

**Issue by THIS-W** [sqzw-x/mdcx#25]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

大佬，在演员界面的最后一个选项，补全Kodi/Plex/Jvedio演员头像，此选项无效。
我不使用Emby和Jellyfin，只使用Jvedio的情况，mcdx并不会在文件目录生成/.actors文件夹。
所有视频都是这样的情况，会导致在Jvedio里演员无头像，此选项也没有开关，只有一个覆盖图像的开关，如何才能在文件目录生成演员头像文件夹呢

### 如何复现

1. 前往 '设置'
2. 点击 '演员'
3. 滑动到 '补全Kodi/Plex/Jvedio演员头像'
4. 出现问题

### 预期行为

希望此选项有效，能在每个视频目录生成演员头像文件夹

### 截图

![Uploading QQ截图20240102214129.png…]()

**Comment by sqzw-x** [comment]
是UI的问题，运行按钮被挡住了，后续会进行调整
