### ISSUE TITLE
使用最新每日版的读取模式检查本地资源库时，大部分nfo文件被删除

### ISSUE THREAD

**Issue by ShiYang999** [sqzw-x/mdcx#256]
从图片和日志可以看到原本18个视频文件，对应18个nfo文件，执行完读取后被删掉了8个nfo文件，所有这些nfo文件都是刚刚使用MDCx刮取的，MDCx的版本是最新的8月4日每日版【928724b6】，退回版本【9704c1dc】，问题消失，同样的配置读取同样的视频文件夹，没有nfo被删除
![读取配置](https://github.com/user-attachments/assets/7ba42880-62d6-475f-b5b0-def50a876874)
![读取日志](https://github.com/user-attachments/assets/68a10984-7f79-4db8-9668-de9982cdaf31)
![读取前](https://github.com/user-attachments/assets/07b2c518-46a3-4d13-b535-f27c6ee20a3b)
![读取后文件数量](https://github.com/user-attachments/assets/bbac7d19-10a7-44f8-a178-72c324c674d7)
下面是用上个版本执行的结果
![上个版本结果](https://github.com/user-attachments/assets/74889bd7-0630-4223-aa62-35bc8e15d757)

**Comment by sqzw-x** [comment]
这两个版本之间并没有修改文件清理相关代码

**Comment by ShiYang999** [comment]
我有检查了设置，发现是设置了文件清理下面的[文件大小(KB)<=:10.0]同时没有排除.nfo导致的，设置了排除项后正常了
![image](https://github.com/user-attachments/assets/1266c6b0-d7db-4ec7-9b86-b88a28b39450)
