### ISSUE TITLE
极空间采用挂载方式进行目录读取，刮削提示硬链接创建失败

### ISSUE THREAD

**Issue by chenstarsQ** [sqzw-x/mdcx#257]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

MDCx-120240321-windows-x86_64-ecaf015e

### 描述你的问题

使用极空间nas挂载方式，在电脑段打开MDCx应用进行刮削，设置为硬链接方式，但刮削过程中报错，提示“硬链接创建失败”

### 如何复现

1. 前往 '极空间-设置-挂载为磁盘-开启'
2. 点击 'MDCx.exe'启动应用，完成相关目录设置，以及刮削模式设置，其中刮削模式设置为“硬链接”，刮削目录与硬链接输出目录是同一个磁盘
3. 开始刮削
4. 出现问题：提示“创建硬链接失败”

### 预期行为

创建硬链接成功，输出刮削好的文件信息到设定好的文件夹

### 相关 Logs

```Text
🥺 HardLink failed! (创建硬连接失败！注意：硬链接要求待刮削文件和输出目录必须是同盘，不支持跨卷！如要跨卷可以尝试软链接模式！)
[WinError 50] 不支持该请求。: 'Z:\\vidHub\\video\\9KG\\待刮削\\IPZZ-364.mp4' -> 'Z:\\vidHub\\video\\link\\9KG\\桃乃木香奈\\IPZZ-364 桃乃木香奈\\IPZZ-364.mp4' 
 🔴 [Failed] Reason: 创建硬连接失败！
 🙊 [Movie] Z:\vidHub\video\9KG\待刮削\IPZZ-364.mp4
```

**Comment by chenstarsQ** [comment]
更新：采用SMB方式共享文件夹，进行刮削，不报错，可以成功创建硬链接

**Comment by MrZhangWeiCe** [comment]
编辑容器-环境-UMASK的值修改成 0777

**Comment by MrZhangWeiCe** [comment]
> ### 在提问之前...
> * [x]  我已经搜索了现有的 issues
> * [x]  我在提问题之前至少花费了 5 分钟来思考和准备
> 
> ### 你使用版本的 commit hash
> MDCx-120240321-windows-x86_64-ecaf015e
> 
> ### 描述你的问题
> 使用极空间nas挂载方式，在电脑段打开MDCx应用进行刮削，设置为硬链接方式，但刮削过程中报错，提示“硬链接创建失败”
> 
> ### 如何复现
> 1. 前往 '极空间-设置-挂载为磁盘-开启'
> 2. 点击 'MDCx.exe'启动应用，完成相关目录设置，以及刮削模式设置，其中刮削模式设置为“硬链接”，刮削目录与硬链接输出目录是同一个磁盘
> 3. 开始刮削
> 4. 出现问题：提示“创建硬链接失败”
> 
> ### 预期行为
> 创建硬链接成功，输出刮削好的文件信息到设定好的文件夹
> 
> ### 相关 Logs
> ```
> 🥺 HardLink failed! (创建硬连接失败！注意：硬链接要求待刮削文件和输出目录必须是同盘，不支持跨卷！如要跨卷可以尝试软链接模式！)
> [WinError 50] 不支持该请求。: 'Z:\\vidHub\\video\\9KG\\待刮削\\IPZZ-364.mp4' -> 'Z:\\vidHub\\video\\link\\9KG\\桃乃木香奈\\IPZZ-364 桃乃木香奈\\IPZZ-364.mp4' 
>  🔴 [Failed] Reason: 创建硬连接失败！
>  🙊 [Movie] Z:\vidHub\video\9KG\待刮削\IPZZ-364.mp4
> ```
> 
> ### 截图
> _No response_
> 
> ### 还有别的吗？
> _No response_

编辑容器-环境-UMASK的值修改成 0777
