### ISSUE TITLE
FC2HUB更换域名了

### ISSUE THREAD

**Issue by paperpeel** [sqzw-x/mdcx#265]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

e5c0df939c6a7e8051b765caa22efa2780424cfa

### 描述你的问题

搜了一下还没然讨论这个话题
`由於FC2的商標問題，FC2hub.com將以新網域Javten.com正式經營`
虽然现在还有重定向,是否应该准备好迁移到新域名上

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by YuGhi-bug** [comment]
相同問題
