### ISSUE TITLE
cookies的格式是什么？

### ISSUE THREAD

**Issue by weigeloveu** [sqzw-x/mdcx#27]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

用editcookies导出的cookies不能用，且下次启动的时候会造成配置文件格式错误。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by tanguanyu2002** [comment]
我也遇到了相同的问题
