### ISSUE TITLE
能否增加文件夹分类

### ISSUE THREAD

**Issue by 744532022** [sqzw-x/mdcx#306]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

[120240924](https://github.com/sqzw-x/mdcx/releases/tag/120240924)

### 描述你的问题

搜刮后有码  无码   fc2分类到单独的文件夹而不是都放在一个文件夹

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by cgkings** [comment]
本身就有这个功能

**Comment by 744532022** [comment]
> 本身具有这个功能

命名字段是什么？？
