### ISSUE TITLE
削刮时生成软链接出现问题

### ISSUE THREAD

**Issue by mobilesuits** [sqzw-x/mdcx#307]
版本MDCx-120240924-macos-aarch64-e5c0df93

之前一直用rclone挂载115网盘，最近挂载出问题用不了了，换成了Clouddrivr2，网盘挂载的路径没变，但是之前很多削刮生成的软链接都失效了，只有重新削刮生成。

但问题来了，目前在削刮时我设置的是削刮前在本地目录先生成软链接，之后再削刮软链接。在削刮路径中我可以访问已挂载的网盘和目录，也能看到待削刮的文件，但是开始削刮后似乎不能生成软链接，导致本地的待削刮软链接目录为空，削刮结果数量显示一直是成功0，跳过0，失败0，1秒就结束了，没法削刮了。

经过几种测试，目前初步判断是网盘的削刮路径中带有日文浊音（也就是日文右上角的小符号）的好像会出这个问题，求问一下解决办法，如果一个一个改网盘的原始目录名称就太费事了。

**Comment by sqzw-x** [comment]
> 经过几种测试，目前初步判断是网盘的削刮路径中带有日文浊音（也就是日文右上角的小符号）的好像会出这个问题，求问一下解决办法，如果一个一个改网盘的原始目录名称就太费事了。

这个是网盘自己的问题, 之前也遇到过, mdcx 是没法解决的.
我自己的刮削设定里路径中不包括假名, 如果你非要包含假名, 我认为可以这样:
1. 用更新模式刮削网盘目录, 设置路径中不包含假名, 这样可以修复网盘路径
2. 在第一步刮削时开启 工具-软链接助手-刮削过程中自动创建软链接, 不勾选复制nfo等, 然后设置本地目录
3. 这样, 在第一步刮削完后, 应该能成功在本地创建所有视频的软链接
4. 进行第二次刮削, 用正常模式, 刮削本地的软链接目录, 这步输出路径中可以包含假名
5. 如果有新的视频加入网盘, 先对网盘目录运行读取模式, 清除垃圾文件并在本地创建软链接, 然后刮削本地的软链接目录

以上只是一个大概思路, 没有实测, 你可以尝试一下
