### ISSUE TITLE
亚马逊的封面图 在日志里看到已经正常找到了 但是软件还是使用海报图裁剪的方式获取封面图 

### ISSUE THREAD

**Issue by helo1220** [sqzw-x/mdcx#312]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

MDCx-120240924-windows-x86_64-e5c0df93

### 描述你的问题

亚马逊的封面图 在日志里看到已经正常找到了 但是软件还是使用海报图裁剪的方式获取封面图 

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Crispy-Bones** [comment]
亚马逊网站页面做了变更，已修复 https://github.com/sqzw-x/mdcx/pull/315#issue-2735734408 ， 等管理员合并

**Comment by helo1220** [comment]
还是没修复呢 今天刮削还是这个情况

> 亚马逊网站页面做了变更，已修复 [#315 (comment)](https://github.com/sqzw-x/mdcx/pull/315#issue-2735734408) ， 等管理员合并

**Comment by Crispy-Bones** [comment]
> 还是没修复呢 今天刮削还是这个情况
> 
> > 亚马逊网站页面做了变更，已修复 [#315 (comment)](https://github.com/sqzw-x/mdcx/pull/315#issue-2735734408) ， 等管理员合并

我看daily realise还是上周的版本，需要等管理员更新版本

**Comment by jiaminxun** [comment]
> > 还是没修复呢今天刮削还是这个情况
> > > 亚马逊网站页面已变更，已修复[#315 (comment)](https://github.com/sqzw-x/mdcx/pull/315#issue-2735734408)，等管理员合并
> 
> 我看每日实现还是上周的版本，需要等管理员更新版本

https://github.com/northsea4/mdcx/releases/tag/daily_release
这里有一个修复了上周无法运行的版本，而且这个还可以刮削dmm 2K横版封面，大佬能不能用这个修复下啊

**Comment by Crispy-Bones** [comment]
> > > 还是没修复呢今天刮削还是这个情况
> > > > 亚马逊网站页面已变更，已修复[#315 (comment)](https://github.com/sqzw-x/mdcx/pull/315#issue-2735734408)，等管理员合并
> > 
> > 
> > 我看每日实现还是上周的版本，需要等管理员更新版本
> 
> https://github.com/northsea4/mdcx/releases/tag/daily_release 这里有一个修复了上周无法运行的版本，而且这个还可以刮削dmm 2K横版封面，大佬能不能用这个修复下啊

我放网盘了，如果急用的话可以先用这个
链接：https://pan.quark.cn/s/7b581c9389fb
提取码：qNJZ

**Comment by jiaminxun** [comment]
> > > > 还是没修复呢今天刮削还是这个情况
> > > > > 亚马逊网站页面已变更，已修复[#315 (comment)](https://github.com/sqzw-x/mdcx/pull/315#issue-2735734408)，等管理员合并
> > > 
> > > 
> > > 我看每日实现还是上周的版本，需要等管理员更新版本
> > 
> > 
> > https://github.com/northsea4/mdcx/releases/tag/daily_release 这里有一个修复了上周无法运行的版本，而且这个还可以刮削dmm 2K横版封面，大佬能不能用这个修复下啊
> 
> 我放网盘了，如果急用的话可以先用这个 链接：https://pan.quark.cn/s/7b581c9389fb 提取码：qNJZ

感谢，日亚和dmm 2K横版封面都能刮了

**Comment by smart0114** [comment]
> > > > 还是没修复呢今天刮削还是这个情况
> > > > > 亚马逊网站页面已变更，已修复[#315 (comment)](https://github.com/sqzw-x/mdcx/pull/315#issue-2735734408)，等管理员合并
> > > 
> > > 
> > > 我看每日实现还是上周的版本，需要等管理员更新版本
> > 
> > 
> > https://github.com/northsea4/mdcx/releases/tag/daily_release 这里有一个修复了上周无法运行的版本，而且这个还可以刮削dmm 2K横版封面，大佬能不能用这个修复下啊
> 
> 我放网盘了，如果急用的话可以先用这个 链接：https://pan.quark.cn/s/7b581c9389fb 提取码：qNJZ

大佬 你网盘这个版本刮DMM 2K也包含了吗？

**Comment by Agon1111** [comment]
> > > > 还是没修复呢今天刮削还是这个情况
> > > > > 亚马逊网站页面已变更，已修复[#315 （comment），](https://github.com/sqzw-x/mdcx/pull/315#issue-2735734408)等管理员合并
> > > 
> > > 
> > > 我看每日实现还是上周的版本，需要等管理员更新版本
> > 
> > 
> > https://github.com/northsea4/mdcx/releases/tag/daily_release 这里有一个修复了上周无法运行的版本，而且这个还可以刮削dmm 2K横版封面，大佬能不能用这个修复下啊
> 
> 我放网盘了，如果急用的话可以先用这个 链接：https://pan.quark.cn/s/7b581c9389fb 提取码：qNJZ

大佬链接过期了，能补一下吗，谢谢

**Comment by Juhraya** [comment]
> > > > > 还是没修复呢今天刮削还是这个情况
> > > > > > 亚马逊网站页面已变更，已修复[#315 （comment），](https://github.com/sqzw-x/mdcx/pull/315#issue-2735734408)等管理员合并
> > > > 
> > > > 
> > > > 我看每日实现还是上周的版本，需要等管理员更新版本
> > > 
> > > 
> > > https://github.com/northsea4/mdcx/releases/tag/daily_release 这里有一个修复了上周无法运行的版本，而且这个还可以刮削dmm 2K横版封面，大佬能不能用这个修复下啊
> > 
> > 
> > 我放网盘了，如果急用的话可以先用这个 链接：https://pan.quark.cn/s/7b581c9389fb 提取码：qNJZ
> 
> 大佬链接过期了，能补一下吗，谢谢

求补链
