### ISSUE TITLE
12月5日版本在win8、win11系统均无法运行

### ISSUE THREAD

**Issue by 13521254555** [sqzw-x/mdcx#317]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

MDCx-daily_release-windows-x86_64-f5b42615.exe

### 描述你的问题

启动程序报告异常错误退出

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![123](https://github.com/user-attachments/assets/1c2c4e47-9f14-4884-b80b-219b725cc7dd)

**Comment by smart0114** [comment]
#304 有解决方案了 可以参考
