### ISSUE TITLE
不确定的Emby以及元数据BUG~

### ISSUE THREAD

**Issue by miria0** [sqzw-x/mdcx#32]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

已确定元数据导入下载完毕，但是Emby却没有任何动作，依旧只是一个番号...

已确定重新在刮刮乐主界面重新编辑NFO文件生效，在EMBY生效，所以是否可以弄一个重新保存选项？

我已经弄这个东西弄了快2个小时了！2个小时！2个小时！！！！！！！

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

![Snipaste_2024-01-06_05-59-24](https://github.com/sqzw-x/mdcx/assets/50533928/1a13c164-0111-4efe-bf33-c222c0838467)

增加一个快速保存NFO保存选项。这是我发现的BUG。软件都是最新版本。

### 截图

![Snipaste_2024-01-06_05-59-24](https://github.com/sqzw-x/mdcx/assets/50533928/f53b017c-6cd5-4e50-a77b-e64e7d053d0f)
![Snipaste_2024-01-06_06-01-34](https://github.com/sqzw-x/mdcx/assets/50533928/933a8ec1-bd35-4e98-b468-f1840a50fb19)

**Comment by miria0** [comment]
![Snipaste_2024-01-06_06-03-38](https://github.com/sqzw-x/mdcx/assets/50533928/0eb8a00c-62b7-42dc-a06f-2bdc3611688c)
 手动保存太麻烦了...本来数据量就有600多个...还得一个一个看那个数据正常，那个数据不正常...

**Comment by sqzw-x** [comment]
你有没有试过在 emby 控制台-媒体库 界面点击  `扫描媒体库文件`

**Comment by miria0** [comment]
> 你有没有试过在 emby 控制台-媒体库 界面点击 `扫描媒体库文件`

都试过了..最后挨个删掉不生效的NFO，重新导入了...

**Comment by sqzw-x** [comment]
> 不生效的NFO

不生效是因为内容错误，还是 emby 未能识别？
点击保存后 nfo 内容是否有变化？
如果是正常的 nfo emby 无法识别，那么应该是emby元数据刷新的问题
