### ISSUE TITLE
封面图过于低清且无法利用google以图搜图功能搜索高清封面图

### ISSUE THREAD

**Issue by ygt1233211** [sqzw-x/mdcx#34]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

这问题绝大多数为vr类影片
举例番号：kavr-321
1、在字段模式下，搜刮出的封面为裁剪封面；
2、在指定网站模式（dmm或javbus）下，搜刮出正常影片封面，但分辨率仅为147*200；
3、尝试将指定网站模式下搜刮出的封面图拉进google搜索无任何结果（不清楚是否图片清晰度过低的原因）
4、试过其他指定网站，均无法搜刮出高于147*200分辨率的封面图；
5、但高清版封面图实际存在，但包括dmm或javbus网站都仅将高清版的封面作为剧照展示。
以kavr-321影片为例子：
dmm封面图的链接为https://pics.dmm.co.jp/digital/video/kavr00321/kavr00321pl.jpg
而作为剧照展示的高清封面图链接为：
https://pics.dmm.co.jp/digital/video/kavr00321/kavr00321jp-1.jpg

不知道从技术上能不能解决封面图清晰度过低的问题

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
1. 仅针对此影片，我手动搜索了一下，似乎 dmm 的图片就是可找到的最高清版，Google 搜图确实没有结果
2. 其它网站的数据来源大概率也是 dmm，dmm 详情页的封面图是 https://pics.dmm.co.jp/digital/video/kavr00321/kavr00321ps.jpg ，这就是你说的低画质封面来源
3. 我随机查看了其它几个影片的 dmm 页面，并不是每部影片的第一张剧照都是封面
4. 因此目前缺少准确的依据，来决定是否需要将第一张剧照作为封面

**Comment by ygt1233211** [comment]
> 1. 仅针对此影片，我手动搜索了一下，似乎 dmm 的图片就是可找到的最高清版，Google 搜图确实没有结果
> 2. 其它网站的数据来源大概率也是 dmm，dmm 详情页的封面图是 https://pics.dmm.co.jp/digital/video/kavr00321/kavr00321ps.jpg ，这就是你说的低画质封面来源
> 3. 我随机查看了其它几个影片的 dmm 页面，并不是每部影片的第一张剧照都是封面
> 4. 因此目前缺少准确的依据，来决定是否需要将第一张剧照作为封面

理解。我还以为剧照的第一张都是高清封面，那只能看看有没有别的源点站提供高清的封面图，谢谢！
