### ISSUE TITLE
演员信息无法导入

### ISSUE THREAD

**Issue by l57480302** [sqzw-x/mdcx#35]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

演员信息搜索成功，但更新导入报错，刮削和头像更新都正常，api没问题

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

<img width="655" alt="图片1" src="https://github.com/sqzw-x/mdcx/assets/98759844/c5d2951b-a585-46e8-a014-ccef2f0412c7">

**Comment by sqzw-x** [comment]
api 请求返回 400，检查 emby 设置

**Comment by l57480302** [comment]
我用的是jellyfin10.8.13，具体是什么设置呢？api应该是没问题的，头像搜索导入功能正常

**Comment by l57480302** [comment]
找到原因了，是选中了使用数据库补全，可能不兼容jellyfin

**Comment by l57480302** [comment]
有木有办法？

**Comment by sqzw-x** [comment]
关闭数据库补全时可以正常导入吗？
如果是，我将重新检查该功能是否兼容 Jellyfin API

**Comment by l57480302** [comment]
是的，关闭数据库补全，用默认的维基百科可以导入。另外获取指定用户媒体库中的演员功能用不了，设置对的id并在jellyfin里设置好允许访问的媒体库后，刮削头像和信息还是会查找所有媒体库的演员；填写了id后ini配置文件没有对应的内容，id不对的情况下日志会显示连接失败。
![image](https://github.com/sqzw-x/mdcx/assets/98759844/cdc1ff4b-5995-460b-b4fc-e0a89b45f5ea)

**Comment by sqzw-x** [comment]
已修复 userid 无法保存

**Comment by sqzw-x** [comment]
尝试修复演员信息导入

**Comment by sqzw-x** [comment]
userid 能否实现获取指定用户媒体库中的演员有待进一步测试，参考 #24，jellyfin 并没有测试过

**Comment by sqzw-x** [comment]
jellyfin 演员信息已修复
