### ISSUE TITLE
求个mac版本

### ISSUE THREAD

**Issue by qingpei88800** [sqzw-x/mdcx#36]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

求个mac版本

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
我没有 macOS 环境，你可以尝试自行构建
下面是原作者的 mac 打包教程：
* 官网下载安装 [python](https://www.python.org)
* 命令行cd到MDCx所在目录
* 命令行安装所需模块 pip install -r requirements.txt
* 命令行安装打包工具 pip install py2app
* 命令行运行 python setup.py py2app --packages=PIL
* 打包好的程序在dist文件夹里面，MDCx.app 右键「显示包内容」，删除Contents/plugins文件夹即可(如果有这个的话)
如果不成功，可能需要修改 setup.py 内容

**Comment by yanis8787** [comment]
大佬～同求个mac版～

**Comment by qingpei88800** [comment]
请问是使用你的代码 还是使用原来的代码 

`Collecting py2app
  Using cached py2app-0.28.6-py2.py3-none-any.whl.metadata (63 kB)
Collecting altgraph>=0.17.3 (from py2app)
  Using cached altgraph-0.17.4-py2.py3-none-any.whl.metadata (7.3 kB)
Collecting modulegraph>=0.19.5 (from py2app)
  Downloading modulegraph-0.19.6-py2.py3-none-any.whl.metadata (14 kB)
Collecting macholib>=1.16.2 (from py2app)
  Using cached macholib-1.16.3-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from modulegraph>=0.19.5->py2app) (49.2.1)
Using cached py2app-0.28.6-py2.py3-none-any.whl (835 kB)
Using cached altgraph-0.17.4-py2.py3-none-any.whl (21 kB)
Using cached macholib-1.16.3-py2.py3-none-any.whl (38 kB)
Downloading modulegraph-0.19.6-py2.py3-none-any.whl (34 kB)
Installing collected packages: altgraph, modulegraph, macholib, py2app
Successfully installed altgraph-0.17.4 macholib-1.16.3 modulegraph-0.19.6 py2app-0.28.6
➜  mdcx git:(master) python setup.py py2app --packages=PIL
zsh: command not found: python
➜  mdcx git:(master) python3 setup.py py2app --packages=PIL
  error: subprocess-exited-with-error
  
  × Building wheel for pygobject (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-39
      creating build/lib.macosx-10.9-x86_64-cpython-39/pygtkcompat
      copying pygtkcompat/pygtkcompat.py -> build/lib.macosx-10.9-x86_64-cpython-39/pygtkcompat
      copying pygtkcompat/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-39/pygtkcompat
      copying pygtkcompat/generictreemodel.py -> build/lib.macosx-10.9-x86_64-cpython-39/pygtkcompat
      creating build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/_signalhelper.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/_constants.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/pygtkcompat.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/_ossighelper.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/importer.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/_error.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/_gtktemplate.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/_propertyhelper.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/types.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/docstring.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/_option.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      copying gi/module.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi
      creating build/lib.macosx-10.9-x86_64-cpython-39/gi/repository
      copying gi/repository/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/repository
      creating build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      copying gi/overrides/GIMarshallingTests.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      copying gi/overrides/Gdk.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      copying gi/overrides/Pango.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      copying gi/overrides/GdkPixbuf.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      copying gi/overrides/Gtk.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      copying gi/overrides/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      copying gi/overrides/GLib.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      copying gi/overrides/GObject.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      copying gi/overrides/Gio.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      copying gi/overrides/keysyms.py -> build/lib.macosx-10.9-x86_64-cpython-39/gi/overrides
      running build_ext
      Package gobject-introspection-1.0 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'gobject-introspection-1.0' found
      Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.64.0')' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pygobject
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.9/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/sc/78kn3vys22b107gwv156kjbh0000gn/T/tmpi4svw55e', '--quiet', 'pygobject']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/liuqingpei/PycharmProjects/mdcx/setup.py", line 28, in <module>
    setup(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 164, in setup
    _install_setup_requires(attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 779, in resolve
    dist = best[req.key] = env.best_match(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1064, in best_match
    return self.obtain(req, installer)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1076, in obtain
    return installer(requirement)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/Library/Frameworks/Python.framework/Versions/3.9/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/sc/78kn3vys22b107gwv156kjbh0000gn/T/tmpi4svw55e', '--quiet', 'pygobject']' returned non-zero exit status 1.
`
我运行报错了

**Comment by qingpei88800** [comment]
在mac中用pycharm运行了，多谢。但是还是没有打包成可执行文件

**Comment by qingpei88800** [comment]
生成可执行文件后 运行报错 
<img width="255" alt="image" src="https://github.com/sqzw-x/mdcx/assets/11956017/d729943f-e519-43e9-b3d0-fa6758153502">

**Comment by sqzw-x** [comment]
我没有环境调试，只能等一个 mac 平台的开发者进行构建了

**Comment by rosspsp** [comment]
同求mac版本

**Comment by qingpei88800** [comment]
> > 生成可执行文件后 运行报错 <img alt="image" width="255" src="https://private-user-images.githubusercontent.com/11956017/295147201-d729943f-e519-43e9-b3d0-fa6758153502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDk2OTMsIm5iZiI6MTcwNDgwOTM5MywicGF0aCI6Ii8xMTk1NjAxNy8yOTUxNDcyMDEtZDcyOTk0M2YtZTUxOS00M2U5LWIzZDAtZmE2NzU4MTUzNTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0MDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZmIzMzRlNTE5MzIzMmI0NzEyMmYzNGZlMzBhNjBhZmI1NTNmODMzYWRkMjBmM2JjMWE3MjVmZDcxMzhlYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2TOmyUHWegA8eYuJBu4QoFhywizRDCVJQjDSF4zZ0EU">
> 
> 可以描述一下相关的命令或者有修改的地方吗？ 我尝试使用py2app打包，卡在了这个 `no module named "models"` 错误。

把src文件夹标记为source root

**Comment by qingpei88800** [comment]
> > > > 生成可执行文件后 运行报错 <img alt="image" width="255" src="https://private-user-images.githubusercontent.com/11956017/295147201-d729943f-e519-43e9-b3d0-fa6758153502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDk2OTMsIm5iZiI6MTcwNDgwOTM5MywicGF0aCI6Ii8xMTk1NjAxNy8yOTUxNDcyMDEtZDcyOTk0M2YtZTUxOS00M2U5LWIzZDAtZmE2NzU4MTUzNTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0MDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZmIzMzRlNTE5MzIzMmI0NzEyMmYzNGZlMzBhNjBhZmI1NTNmODMzYWRkMjBmM2JjMWE3MjVmZDcxMzhlYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2TOmyUHWegA8eYuJBu4QoFhywizRDCVJQjDSF4zZ0EU">
> > > 
> > > 
> > > 可以描述一下相关的命令或者有修改的地方吗？ 我尝试使用py2app打包，卡在了这个 `no module named "models"` 错误。
> > 
> > 
> > 把src文件夹标记为source root
> 
> 请问这是一个在pycharm中进行的操作，还是setup.py里参数的设置呢？最好可以把打包过程写一下，谢谢
> 
> 另外看不到错误日志这个问题，可以试试在terminal中启动应用： `open -a /path/to/MDCx.app` 或者 `/path/to/MDCx.app/Contents/MacOS/MDCx`

在pycharm 中直接右键src文件夹标记为source root
<img width="642" alt="image" src="https://github.com/sqzw-x/mdcx/assets/11956017/889eb4f4-39c9-41e5-a7b5-b757d69d7af0">

**Comment by qingpei88800** [comment]
> > > > 生成可执行文件后 运行报错 <img alt="image" width="255" src="https://private-user-images.githubusercontent.com/11956017/295147201-d729943f-e519-43e9-b3d0-fa6758153502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDk2OTMsIm5iZiI6MTcwNDgwOTM5MywicGF0aCI6Ii8xMTk1NjAxNy8yOTUxNDcyMDEtZDcyOTk0M2YtZTUxOS00M2U5LWIzZDAtZmE2NzU4MTUzNTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0MDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZmIzMzRlNTE5MzIzMmI0NzEyMmYzNGZlMzBhNjBhZmI1NTNmODMzYWRkMjBmM2JjMWE3MjVmZDcxMzhlYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2TOmyUHWegA8eYuJBu4QoFhywizRDCVJQjDSF4zZ0EU">
> > > 
> > > 
> > > 可以描述一下相关的命令或者有修改的地方吗？ 我尝试使用py2app打包，卡在了这个 `no module named "models"` 错误。
> > 
> > 
> > 把src文件夹标记为source root
> 
> 请问这是一个在pycharm中进行的操作，还是setup.py里参数的设置呢？最好可以把打包过程写一下，谢谢
> 
> 另外看不到错误日志这个问题，可以试试在terminal中启动应用： `open -a /path/to/MDCx.app` 或者 `/path/to/MDCx.app/Contents/MacOS/MDCx`

<img width="791" alt="image" src="https://github.com/sqzw-x/mdcx/assets/11956017/22ef8deb-b260-4776-9043-84e907201776">
这样试了，日志只有：Last login: Wed Jan 10 12:00:14 on ttys001
/Applications/MDCx.app/Contents/MacOS/MDCx ; exit;                              
➜  ~ /Applications/MDCx.app/Contents/MacOS/MDCx ; exit;

**Comment by rosspsp** [comment]
> 我没有 macOS 环境，你可以尝试自行构建 下面是原作者的 mac 打包教程：
> 
> * 官网下载安装 [python](https://www.python.org)
> * 命令行cd到MDCx所在目录
> * 命令行安装所需模块 pip install -r requirements.txt
> * 命令行安装打包工具 pip install py2app
> * 命令行运行 python setup.py py2app --packages=PIL
> * 打包好的程序在dist文件夹里面，MDCx.app 右键「显示包内容」，删除Contents/plugins文件夹即可(如果有这个的话)
>   如果不成功，可能需要修改 setup.py 内容

好像github可以打包全平台程序包，不太懂。。。

**Comment by rosspsp** [comment]
> > > 我没有 macOS 环境，你可以尝试自行构建 下面是原作者的 mac 打包教程：
> > > 
> > > * 官网下载安装 [python](https://www.python.org)
> > > * 命令行cd到MDCx所在目录
> > > * 命令行安装所需模块 pip install -r requirements.txt
> > > * 命令行安装打包工具 pip install py2app
> > > * 命令行运行 python setup.py py2app --packages=PIL
> > > * 打包好的程序在dist文件夹里面，MDCx.app 右键「显示包内容」，删除Contents/plugins文件夹即可(如果有这个的话)
> > >   如果不成功，可能需要修改 setup.py 内容
> > 
> > 
> > 好像github可以打包全平台程序包，不太懂。。。
> 
> 是可以这么说。
> 
> 目前的进展：
> 
> 1. 可以使用pyinstaller打包成功（py2app卡在找不到module，暂时放弃）。
> 2. 可以打包macOS x86_64版，在Apple Silicon芯片系统上，打开时要20+秒才出现应用窗口，具体原因未知，此外暂未发现其他异常。
> 3. 可以打包macOS aarch64版，但github目前未提供免费的`运行器`，只能在Apple Silicon芯片系统上搭建「[自托管运行器](https://docs.github.com/zh/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#%E8%87%AA%E6%89%98%E7%AE%A1%E8%BF%90%E8%A1%8C%E5%99%A8%E4%B8%8E-github-%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1)」。这玩意儿简单来说就是在自己的设备搭建一个运行器，交给github调用运行打包处理。
> 4. 配置文件目录权限方面比较麻烦，打包后应用获取到的默认路径没有写入权限，导致应用完全启动不了。暂时的想法是默认目录为`~/.mdcx`，可以在之后自行修改到其他目录，标记文件`MDCx.config`会一直保留在`~/.mdcx`下面，好处是以后更新应用不需要再设置配置文件目录(因为`~/.mdcx/MDCx.config`文件固定了，它是"指路人"，自然能找到以前设置的目录路径)。
> 5. 打包Windows版自然也是可以的。
> 6. Linux版则暂不考虑，一是鲜见需求，二是我已经维护了一个相对成熟的docker版了。

mac版的程序从哪里下载？

**Comment by rosspsp** [comment]
> > > 我没有 macOS 环境，你可以尝试自行构建 下面是原作者的 mac 打包教程：
> > > 
> > > * 官网下载安装 [python](https://www.python.org)
> > > * 命令行cd到MDCx所在目录
> > > * 命令行安装所需模块 pip install -r requirements.txt
> > > * 命令行安装打包工具 pip install py2app
> > > * 命令行运行 python setup.py py2app --packages=PIL
> > > * 打包好的程序在dist文件夹里面，MDCx.app 右键「显示包内容」，删除Contents/plugins文件夹即可(如果有这个的话)
> > >   如果不成功，可能需要修改 setup.py 内容
> > 
> > 
> > 好像github可以打包全平台程序包，不太懂。。。
> 
> 是可以这么说。
> 
> 目前的进展：
> 
> 1. 可以使用pyinstaller打包成功（py2app卡在找不到module，暂时放弃）。
> 2. 可以打包macOS x86_64版，在Apple Silicon芯片系统上，打开时要20+秒才出现应用窗口，具体原因未知，此外暂未发现其他异常。
> 3. 可以打包macOS aarch64版，但github目前未提供免费的`运行器`，只能在Apple Silicon芯片系统上搭建「[自托管运行器](https://docs.github.com/zh/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#%E8%87%AA%E6%89%98%E7%AE%A1%E8%BF%90%E8%A1%8C%E5%99%A8%E4%B8%8E-github-%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1)」。这玩意儿简单来说就是在自己的设备搭建一个运行器，交给github调用运行打包处理。
> 4. 配置文件目录权限方面比较麻烦，打包后应用获取到的默认路径没有写入权限，导致应用完全启动不了。暂时的想法是默认目录为`~/.mdcx`，可以在之后自行修改到其他目录，标记文件`MDCx.config`会一直保留在`~/.mdcx`下面，好处是以后更新应用不需要再设置配置文件目录(因为`~/.mdcx/MDCx.config`文件固定了，它是"指路人"，自然能找到以前设置的目录路径)。
> 5. 打包Windows版自然也是可以的。
> 6. Linux版则暂不考虑，一是鲜见需求，二是我已经维护了一个相对成熟的docker版了。

大神！厉害！

**Comment by rosspsp** [comment]
> @rosspsp 暂时只是测试打包，不过也欢迎测试使用。 暂时可以从Actions的Artifacts里下载到已打包文件（打开页面翻到底部）。
> 
> * `macOS-x86_64版` 和 `windows版` ：https://github.com/northsea4/mdcx/actions/runs/7513541641
> * `macOS-aarch64版`：https://github.com/northsea4/mdcx/actions/runs/7513558762

好的，厉害！！！

**Comment by rosspsp** [comment]
> @sqzw-x 或者你抽空看一下：https://github.com/northsea4/mdcx 当然了，目前这个Release action 算是一个demo，仅供参考。

macOS-aarch64版：https://github.com/northsea4/mdcx/actions/runs/7513558762
演员信息配置页
<img width="772" alt="iShot_2024-01-14_01 06 06" src="https://github.com/sqzw-x/mdcx/assets/73610222/f81d242d-0977-4767-b5e3-8463382e27f8">

大神，补全演员信息时会报下面的错误信息
<img width="610" alt="iShot_2024-01-14_00 55 19" src="https://github.com/sqzw-x/mdcx/assets/73610222/6fceded2-618d-487d-a982-e8403986c888">
<img width="550" alt="iShot_2024-01-14_00 55 02" src="https://github.com/sqzw-x/mdcx/assets/73610222/182cc7a8-db85-465f-a14e-497c27a716a7">

**Comment by sqzw-x** [comment]
@northsea4 已经新建 macos 分支

**Comment by sqzw-x** [comment]
https://github.com/sqzw-x/mdcx/releases/tag/pre-20240115
