### ISSUE TITLE
刮削fc2hub的时候，默认使用英文，并且没有简介信息

### ISSUE THREAD

**Issue by Viskym** [sqzw-x/mdcx#4]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

刮削fc2hub的时候，默认使用英文
fc2hub.com/en/video，并且没有简介信息

### 如何复现

1. 使用软件刮削fc2番号。例如FC2-806892。
2. 自动刮削到fc2hub，获取英文内容。
（本人使用欧洲IP）

### 预期行为

默认使用繁中(fc2hub.com/tw/video)或者日文
并刮削简介内容

**Comment by freesrz93** [comment]
简介获取已修复。
关于刮削语言，mdcx 请求的地址是 https://fc2hub.com/search?kw=，只是会在获取后执行翻译，这对应的确实是日语，我用法国 IP 测试也是这样，不清楚你那边为什么跳到英语

**Comment by freesrz93** [comment]
又看了一下，确实会跳转，已修复，现在始终会请求日语页面

**Comment by sqzw-x** [comment]
已修复。现在应该始终使用日语页面
