### ISSUE TITLE
字段优先下mgstage不能连续刮削

### ISSUE THREAD

**Issue by shiyan1012** [sqzw-x/mdcx#41]
字段优先下刮削MGS片子，不勾选厂商优先情况下按照mgstage第一优先级去刮削ABW-011，启动软件第一次刮削正常，第二次刮削或者多片连续刮削下，mgstage请求成功但是原标题获取失败后按次优先级进行刮削。只能重启软件挂削一部，再次重启再次刮削.......而指定mgstage网站缺可以连续刮削。这是为什么？谢谢   附配置文件
![222222](https://github.com/sqzw-x/mdcx/assets/142632371/5847a85e-3b58-47f8-a17f-5edbf1c07864)
[config.zip](https://github.com/sqzw-x/mdcx/files/13879889/config.zip)

**Comment by sqzw-x** [comment]
确实有此问题。当使用字段优先时，mgstage 有时会返回空的内容，仅 html 头。
原因可能是是仅使用 mgstage 时可复用 TCP 连接，而字段优先时中途转去刮削其它网站，导致连接池释放连接，刮削下一个文件访问 mgstage 时需要重新连接，触发了网站的连接限制。
该问题比较难以修复，因为涉及到网络请求部分的实现，代码已经究极混乱，基本没有改写的可能性了
