### ISSUE TITLE
女优多个名字的怎么合在一起?

### ISSUE THREAD

**Issue by arthurlyk** [sqzw-x/mdcx#43]
如题有没有办法将女优不同化名下的作品合在一起? 如有栖花緋在javdb下有别名:有栖花あか,凪ひかる, 汐世. 在默认情况下作品会分在不同的文件下. 有没有手动或者自动的方法将所有作品合在视频目录为有栖花あか,或: 有栖花あか(凪ひかる)(汐世)的文件夹下? 谢谢!

**Comment by arthurlyk** [comment]
之所以要这样是因为在jellyfin下如果搜索有栖花あか, 在其他名字下的作品将无法搜到. 如果库存太多非常不方便

**Comment by anyingxiuluo** [comment]
有女优名字映射表，但是里面信息应该有段时间没更新了

**Comment by arthurlyk** [comment]
> 有女优名字映射表，但是里面信息应该有段时间没更新了

你知道手动添加怎么用吗? 我试了两个但没有什么卵用. 这软件太强大了, 可惜搞得太复杂了不会用啊
<img width="668" alt="2024-01-12_202953" src="https://github.com/sqzw-x/mdcx/assets/153576773/a267a1c5-99d5-468a-bcdb-aa34a75a264e">
<img width="719" alt="2024-01-12_203106" src="https://github.com/sqzw-x/mdcx/assets/153576773/8f8e2d9a-8b15-4460-a6d9-0da8a5542064">

**Comment by anyingxiuluo** [comment]
你这几个别名不都有么，开启后都会翻译成有栖花緋，如果有漏网的别名在keyword字段后面加上就行了

**Comment by arthurlyk** [comment]
> 你这几个别名不都有么，开启后都会翻译成有栖花緋，如果有漏网的别名在keyword字段后面加上就行了

这两个我自己加的, 试了没用

**Comment by anyingxiuluo** [comment]
加了之后把他的作品放在一起重新刮削，如果不行就贴出日志给作者看看哪里出问题了

**Comment by sqzw-x** [comment]
由于我并不清楚原始的映射表是如何得到的（肯定不是手工写的），所以没办法维护此表以及相关的功能

**Comment by anyingxiuluo** [comment]
> 由于我并不清楚原始的映射表是如何得到的（肯定不是手工写的），所以没办法维护此表以及相关的功能

应该是从javbd网站爬取的

**Comment by anyingxiuluo** [comment]
> > 由于我并不清楚原始的映射表是如何得到的（肯定不是手工写的），所以没办法维护此表以及相关的功能
> 
> 应该是从javdb网站爬取的

**Comment by sqzw-x** [comment]
> > > 由于我并不清楚原始的映射表是如何得到的（肯定不是手工写的），所以没办法维护此表以及相关的功能
> > 
> > 
> > 应该是从javdb网站爬取的

里面还有国产演员，应该不是从单一网站获取的。
我说的不清楚主要是指原作者没有开源爬虫，因此如果维护必须重写一个，工作量有点大

**Comment by arthurlyk** [comment]
> 由于我并不清楚原始的映射表是如何得到的（肯定不是手工写的），所以没办法维护此表以及相关的功能
多谢大佬, 手动添加已经够用了, 维护辛苦了

**Comment by anyingxiuluo** [comment]
> > > > 由于我并不清楚原始的映射表是如何得到的（肯定不是手工写的），所以没办法维护此表以及相关的功能
> > > 
> > > 
> > > 应该是从javdb网站爬取的
> 
> 里面还有国产演员，应该不是从单一网站获取的。 我说的不清楚主要是指原作者没有开源爬虫，因此如果维护必须重写一个，工作量有点大

我用采集器已经写好了一个脚本，但是我发现javdb演员页只能查看前30页，导致能爬取的数据很少

**Comment by haoylee** [comment]
最后一个名字后面没有加逗号，所以这一行应该都无效了。
<img width="691" alt="屏幕截图 2024-01-19 003517" src="https://github.com/sqzw-x/mdcx/assets/37681300/34571122-b6b8-416b-84f2-7cdb2a1bcfdf">


> > 有女优名字映射表，但是里面信息应该有段时间没更新了
> 
> 你知道手动添加怎么用吗? 我试了两个但没有什么卵用. 这软件太强大了, 可惜搞得太复杂了不会用啊 <img alt="2024-01-12_202953" width="668" src="https://private-user-images.githubusercontent.com/153576773/296401549-a267a1c5-99d5-468a-bcdb-aa34a75a264e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTU4ODksIm5iZiI6MTcwNTU5NTU4OSwicGF0aCI6Ii8xNTM1NzY3NzMvMjk2NDAxNTQ5LWEyNjdhMWM1LTk5ZDUtNDY4YS1iY2RiLWFhMzRhNzVhMjY0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxNjMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmI4NGM5NzI1NDBjNWMxN2YwNmE0NWI0MDcwYjI4OTQzMGExMjM3NWU2MmViNzg1NjBkY2VjMmY4NjFhNTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z-pwsAp8pTNhdBVexn1WlqZjfBDa_zWDhpwC5J8SwEg"> <img alt="2024-01-12_203106" width="719" src="https://private-user-images.githubusercontent.com/153576773/296401552-8f8e2d9a-8b15-4460-a6d9-0da8a5542064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTU4ODksIm5iZiI6MTcwNTU5NTU4OSwicGF0aCI6Ii8xNTM1NzY3NzMvMjk2NDAxNTUyLThmOGUyZDlhLThiMTUtNDQ2MC1hNmQ5LTBkYThhNTU0MjA2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxNjMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODQ2YjFhOGZlYmM2ODZhMmNhZDNkYzdmODM3NmUwNWJiMDdlMzQxZTRhMjA3OGYyMjFkN2I5YzMzMTcwYzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uT6QbrNfz5ok-sP2DgI04frQ7Mev1hxnYj_qtR44RWo">

**Comment by arthurlyk** [comment]
> 最后一个名字后面没有加逗号，所以这一行应该都无效了。 <img alt="屏幕截图 2024-01-19 003517" width="691" src="https://private-user-images.githubusercontent.com/37681300/297815340-34571122-b6b8-416b-84f2-7cdb2a1bcfdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzE4NTYsIm5iZiI6MTcwNTYzMTU1NiwicGF0aCI6Ii8zNzY4MTMwMC8yOTc4MTUzNDAtMzQ1NzExMjItYjZiOC00MTZiLTg0ZjItN2NkYjJhMWJjZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAyMzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjN2EyYWE5MDhjZjhiN2EzNzZjYmY5ZmI4YzFjZDRkOGFmZTVhZTIwZGUwOGQ0ZjI5NjM3NjIyYzVhODJiZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TYmErfWYLKv9VxRgOCOu0bTYAJOnqFZWmNg6RZezYVY">
> 
> > > 有女优名字映射表，但是里面信息应该有段时间没更新了
> > 
> > 
> > 你知道手动添加怎么用吗? 我试了两个但没有什么卵用. 这软件太强大了, 可惜搞得太复杂了不会用啊 <img alt="2024-01-12_202953" width="668" src="https://private-user-images.githubusercontent.com/153576773/296401549-a267a1c5-99d5-468a-bcdb-aa34a75a264e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTU4ODksIm5iZiI6MTcwNTU5NTU4OSwicGF0aCI6Ii8xNTM1NzY3NzMvMjk2NDAxNTQ5LWEyNjdhMWM1LTk5ZDUtNDY4YS1iY2RiLWFhMzRhNzVhMjY0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxNjMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmI4NGM5NzI1NDBjNWMxN2YwNmE0NWI0MDcwYjI4OTQzMGExMjM3NWU2MmViNzg1NjBkY2VjMmY4NjFhNTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z-pwsAp8pTNhdBVexn1WlqZjfBDa_zWDhpwC5J8SwEg"> <img alt="2024-01-12_203106" width="719" src="https://private-user-images.githubusercontent.com/153576773/296401552-8f8e2d9a-8b15-4460-a6d9-0da8a5542064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTU4ODksIm5iZiI6MTcwNTU5NTU4OSwicGF0aCI6Ii8xNTM1NzY3NzMvMjk2NDAxNTUyLThmOGUyZDlhLThiMTUtNDQ2MC1hNmQ5LTBkYThhNTU0MjA2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxNjMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODQ2YjFhOGZlYmM2ODZhMmNhZDNkYzdmODM3NmUwNWJiMDdlMzQxZTRhMjA3OGYyMjFkN2I5YzMzMTcwYzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uT6QbrNfz5ok-sP2DgI04frQ7Mev1hxnYj_qtR44RWo">

加不加好像都是可以的, 我后来下载了最新版本,手动添加词条然后重启软件就好了

**Comment by auroracamus** [comment]
修改后不起作用的可以看看是不是配置文件的目录不对，主程序和真正的配置文件不在一个目录里。看“设置-高级-配置文件目录”那里。
