### ISSUE TITLE
getchu命名问题

### ISSUE THREAD

**Issue by Hasuki360** [sqzw-x/mdcx#46]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

之前用的软件文件夹命名都是GETCHU-XXXX，而且很多网站的资源也是用这个格式，大佬维护的软件是DLID-XXXX，不知道后续的版本能不能变成GETCHU-XXXX

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
能不能给出一些示例，因为这个网站我没用过，根据代码它应该是用网站上的 品番 信息作为名称

**Comment by Hasuki360** [comment]
> 能不能给出一些示例，因为这个网站我没用过，根据代码它应该是用网站上的 品番 信息作为名称
别人的
<?xml version="1.0" encoding="UTF-8" ?>
<movie>
  <title><![CDATA[]]></title>
  <originaltitle><![CDATA[【リ◻︎リ◻︎まとめ】ファーストvsセカンドの激しい銃撃戦♡ 兜合わせ、アナル拡張、 前から後ろから上から... 最後は顔に発砲♡]]></originaltitle>
  <sorttitle><![CDATA[]]></sorttitle>
  <customrating>JP-18+</customrating>
  <mpaa>JP-18+</mpaa>
  <set>サードムーン</set>
  <studio>サードムーン</studio>
  <year>2023</year>
  <outline><![CDATA[]]></outline>
  <plot><![CDATA[]]></plot>
  <runtime>52分</runtime>
  <director>しゃな（サードムーン）</director>
  <poster>poster.jpg</poster>
  <thumb>thumb.jpg</thumb>
  <fanart>fanart.jpg</fanart>
  <actor>
    <name>しゃな（サードムーン）</name>
  </actor>
  <maker>サードムーン</maker>
  <label>サードムーン</label>
  <tag>口交</tag>
  <tag>ぶっかけ</tag>
  <tag>肛交</tag>
  <tag>男の娘・女装</tag>
  <tag>着衣エッチ</tag>
  <tag>学生妹</tag>
  <tag>Getchu</tag>
  <tag>Getchu</tag>
  <genre>口交</genre>
  <genre>ぶっかけ</genre>
  <genre>肛交</genre>
  <genre>男の娘・女装</genre>
  <genre>着衣エッチ</genre>
  <genre>学生妹</genre>
  <genre>Getchu</genre>
  <genre>Getchu</genre>
  <num>GETCHU-4051758</num>
  <premiered>2023-09-09</premiered>
  <releasedate>2023-09-09</releasedate>
  <release>2023-09-09</release>
  <cover>https://dl.getchu.com/data/item_img/40517/4051758/4051758top.jpg</cover>
  <website>https://dl.getchu.com/i/item4051758</website>
</movie>

大佬的
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movie>
  <plot><![CDATA[这是由 Third Moon 制作的 re◻︎ re◻︎ 视频合集！ 接吻＆互相撸管调情，卡布托比赛+电击自慰（肥仔射精） 肥仔的肛门延伸 肛交（正常体位，后背） 肥仔撸管，口交，面部完成（肥仔射精） 肥仔舔精液时射精 这是一部长达52分钟的电影，内容丰富！ 演员信息】 Nishikiki Chikata→Yayoi https://twitter.com/yayoi_satin？s=21＆t=ccIko4Rlo2WrKA1ovRXf9w Inoue Fatty→Shana https://twitter.com/eka_ksana？s=21＆t=ccIko4Rlo2 WrKA1ovRXf9w]]></plot>
  <outline><![CDATA[这是由 Third Moon 制作的 re◻︎ re◻︎ 视频合集！ 接吻＆互相撸管调情，卡布托比赛+电击自慰（肥仔射精） 肥仔的肛门延伸 肛交（正常体位，后背） 肥仔撸管，口交，面部完成（肥仔射精） 肥仔舔精液时射精 这是一部长达52分钟的电影，内容丰富！ 演员信息】 Nishikiki Chikata→Yayoi https://twitter.com/yayoi_satin？s=21＆t=ccIko4Rlo2WrKA1ovRXf9w Inoue Fatty→Shana https://twitter.com/eka_ksana？s=21＆t=ccIko4Rlo2 WrKA1ovRXf9w]]></outline>
  <originalplot><![CDATA[サードムーンで作成したリ◻︎リ◻︎の動画をまとめました！<br><br>キス＆相互手コキいちゃいちゃ<br>兜あわせ＋電マオナニー（千◯射精）<br>千◯のアナル拡張<br>アナルセックス（正常位、バック）<br>千◯自分でシコりながら手コキ、フェラ、顔射フィニッシュ（た◯な射精）<br>精液を舐めながら千◯射精<br><br>盛りだくさんの52分の長編となっております！<br><br>【演者情報】<br>錦木千◯→弥生 <br>https://twitter.com/yayoi_satin？s=21＆t=ccIko4Rlo2WrKA1ovRXf9w<br>井上た◯な→しゃな<br>https://twitter.com/eka_ksana？s=21＆t=ccIko4Rlo2WrKA1ovRXf9w]]></originalplot>
  <tagline>发行日期 2023-09-09</tagline>
  <premiered>2023-09-09</premiered>
  <releasedate>2023-09-09</releasedate>
  <release>2023-09-09</release>
  <num>DLID-4051758</num>
  <title>[李＆#9723;＆#65038;李＆#9723;＆#65038;总结]在激烈的枪战中，第一名对第二名＆#9825;；头盔对头盔、肛门延伸、前胸对后背、上身对下身…最后射向脸部＆#9825;。</title>
  <originaltitle>DLID-4051758 【リ＆#9723;＆#65038;リ＆#9723;＆#65038;まとめ】ファーストvsセカンドの激しい銃撃戦＆#9825; 兜合わせ、アナル拡張、 前から後ろから上から… 最後は顔に発砲＆#9825;</originaltitle>
  <sorttitle>DLID-4051758 【リ＆#9723;＆#65038;リ＆#9723;＆#65038;まとめ】ファーストvsセカンドの激しい銃撃戦＆#9825; 兜合わせ、アナル拡張、 前から後ろから上から… 最後は顔に発砲＆#9825;</sorttitle>
  <mpaa>JP-18+</mpaa>
  <customrating>JP-18+</customrating>
  <countrycode>JP</countrycode>
  <director>しゃな（サードムーン）</director>
  <year>2023</year>
  <runtime>52</runtime>
  <studio>サードムーン</studio>
  <maker>サードムーン</maker>
  <publisher>サードムーン</publisher>
  <label>サードムーン</label>
  <tag>720P</tag>
  <tag>DLID</tag>
  <tag>口交</tag>
  <tag>ぶっかけ</tag>
  <tag>肛交</tag>
  <tag>男の娘·女装</tag>
  <tag>着衣エッチ</tag>
  <tag>学生妹</tag>
  <tag>同人</tag>
  <tag>片商: サードムーン</tag>
  <tag>发行: サードムーン</tag>
  <genre>720P</genre>
  <genre>DLID</genre>
  <genre>口交</genre>
  <genre>ぶっかけ</genre>
  <genre>肛交</genre>
  <genre>男の娘·女装</genre>
  <genre>着衣エッチ</genre>
  <genre>学生妹</genre>
  <genre>同人</genre>
  <genre>片商: サードムーン</genre>
  <genre>发行: サードムーン</genre>
  <poster>https://dl.getchu.com/data/item_img/40517/4051758/4051758top.jpg</poster>
  <cover>https://dl.getchu.com/data/item_img/40517/4051758/4051758top.jpg</cover>
  <website>https://dl.getchu.com/i/item4051758</website>
  <javdbsearchid>DLID-4051758</javdbsearchid>
</movie>
![`TH2VQ%H(QOMPWR55I@0H2D](https://github.com/sqzw-x/mdcx/assets/54326603/cb7f1943-b5b9-42a8-92c3-b524761d5ac8)

**Comment by Hasuki360** [comment]
![_~P9(Q1`R W3NL@0QB~8 9F](https://github.com/sqzw-x/mdcx/assets/54326603/64127341-fb66-4a26-9cef-7a505df73779)
![`TH2VQ%H(QOMPWR55I@0H2D](https://github.com/sqzw-x/mdcx/assets/54326603/dcf4c128-1a37-4492-941d-b7626ef1d89c)

**Comment by Hasuki360** [comment]
> 能不能给出一些示例，因为这个网站我没用过，根据代码它应该是用网站上的 品番 信息作为名称

![_~P9(Q1`R W3NL@0QB~8 9F](https://github.com/sqzw-x/mdcx/assets/54326603/64127341-fb66-4a26-9cef-7a505df73779)

**Comment by sqzw-x** [comment]
现在可以识别 GETCHU-XXXX，不过仍会以 DLID-XXXX 重命名

**Comment by Hasuki360** [comment]
> 现在可以识别 GETCHU-XXXX，不过仍会以 DLID-XXXX 重命名
![5{JA_JZ1ACLZWKZ7OUS@@2M](https://github.com/sqzw-x/mdcx/assets/54326603/cd198860-e90b-4291-9d90-e056dd155517)

希望在这个基础再增加itemxxx的识别，因为文件都是以https://dl.getchu.com/i/itemxxxx的后续itemxxx来起名的
