### ISSUE TITLE
有个很久之前就想要的功能：批量编辑nfo信息

### ISSUE THREAD

**Issue by toobigpao** [sqzw-x/mdcx#47]
除了从网站上刮削的标签/风格以外，有时候想要自定义一些片子的分类/标签/风格，要么是在mdcx的刮削页面里单个改，要么就是在emby里面单个改，能不能出一个功能可以给一些片子集体添加/删除标签/风格呢？从最早的avdc用到现在，感觉这是一个很强大且并不鸡肋的功能，如果大大有空希望考虑一下

**Comment by sqzw-x** [comment]
你说的这个功能我也考虑过，不过 mdcx 的架构已经积重难返了，想进行任何大的改动工作量都是难以忍受的
我正在尝试写一个新项目来代替 mdcx 的一部分功能，主要是元数据管理方面的，可能会加入此功能
不过拿出成品可能还得挺长时间，不要过于期待
