### ISSUE TITLE
如何修改窗口大小

### ISSUE THREAD

**Issue by Jebynn** [sqzw-x/mdcx#5]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

目前使用4k显示器 软件打开后 占用差不多1/3的屏幕
如何能修改程序的显示大小？

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
1. 现在可以在 `设置 - 高级 - 高分屏缩放` 勾选 `非整数倍缩放`，此前这一设置没有正确启用，可能导致窗口过大
2. 使用这一设置会按照你的显示器缩放比例等比（此前是取整）改变窗口大小，不过可能导致显示模糊
3. 原作者的设计里所有控件的尺寸都是绝对值，因此就算允许改变窗口大小，内部的控件尺寸不会变化，最终只会导致显示不全

**Comment by TOP-01** [comment]
请问 这是原作者回来了吗  还是源代码二次开发

**Comment by sqzw-x** [comment]
> 请问 这是原作者回来了吗 还是源代码二次开发

[readme.md](https://github.com/sqzw-x/mdcx/blob/master/README.md)

**Comment by Jebynn** [comment]
> 1. 现在可以在 `设置 - 高级 - 高分屏缩放` 勾选 `非整数倍缩放`，此前这一设置没有正确启用，可能导致窗口过大
> 
>     2. 使用这一设置会按照你的显示器缩放比例等比（此前是取整）改变窗口大小，不过可能导致显示模糊
> 
>     3. 原作者的设计里所有控件的尺寸都是绝对值，因此就算允许改变窗口大小，内部的控件尺寸不会变化，最终只会导致显示不全

好像没什么变化  继续用了 影响不是太大
