### ISSUE TITLE
JAVDB挂了

### ISSUE THREAD

**Issue by arthurlyk** [sqzw-x/mdcx#51]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

<img width="574" alt="2024-01-14_141043" src="https://github.com/sqzw-x/mdcx/assets/153576773/205ad7ce-7d3e-4ebb-9cd1-f35141c92884">
如图Javdb搜刮失败

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
848f07bbe045056cf7b13fa8cf48d94d2e4db45e

**Comment by Leslie-Chiang** [comment]
确实，单文件刮削指定javdb来刮削，就会报错如上，实测MDCx-120240113最新版本并未修复
