### ISSUE TITLE
部分预告片无法刮削

### ISSUE THREAD

**Issue by Dhty617** [sqzw-x/mdcx#52]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

![屏幕截图 2024-01-15 101348](https://github.com/sqzw-x/mdcx/assets/123385337/8adedaf0-8648-4c58-b495-485ad54b6b40)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Dhty617** [comment]
运行环境：
1.Windows 11
2.已开启代理
3.使用字段刮削
4.软链接

**Comment by Dhty617** [comment]
我试了下23年10月版的MDCX是没有问题的
![屏幕截图 2024-01-15 113454](https://github.com/sqzw-x/mdcx/assets/123385337/897319c9-c4c7-428b-98a4-92c399e51c75)

**Comment by sqzw-x** [comment]
需要你的预告片来源网站配置，最好能确定：
1. 其它成功获取的影片，其预告片来源
2. 对于未获取的影片，是否确定该网站存在预告片
3. 失败影片是否成功从同一网站获取了其它字段
4. 是否有多个番号失败，如有最好多发几个示例

**Comment by Dhty617** [comment]
1. 预告片全部来自DMM
2. 肯定是有的
3. 没有，只获取了预告片
4. ![2](https://github.com/sqzw-x/mdcx/assets/123385337/91bbcfaf-ec5d-4de3-bd30-6774cff5f407)

**Comment by sqzw-x** [comment]
确定来源为 DMM ？
我使用 dmm 刮削上图三个番号，均能得到预告片，但大小与你图中显示不符
<img width="536" alt="2024-01-16_11-40-53" src="https://github.com/sqzw-x/mdcx/assets/150016653/4747400b-0649-49d1-ab95-075458f2cc97">

**Comment by Dhty617** [comment]
![1](https://github.com/sqzw-x/mdcx/assets/123385337/ea94b0d1-17c5-4e17-8d24-c3584ce971ec)
![2](https://github.com/sqzw-x/mdcx/assets/123385337/5209f6bd-1cac-4af1-b267-f249b2f80cef)
上面是这么写的，刮削网站我全部用的是默认配置

**Comment by sqzw-x** [comment]
这个地址是最终来源，绝大多数网站都是从 dmm 获取
我需要的是直接来源，即从哪个网站上获取的此链接。
打开调试日志：
![image](https://github.com/sqzw-x/mdcx/assets/150016653/923a0232-8751-4900-a71e-3f10748460fe)
另外建议多次重复刮削实验，因为这种一部分能获取、一部分不能的情况大概率不是 mdcx 的问题，而是网站或者网络的问题

**Comment by Dhty617** [comment]
![1](https://github.com/sqzw-x/mdcx/assets/123385337/a95f875d-34a7-456f-b516-f7134003681c)
肯定都试过了的，但就是刮削不全

**Comment by sqzw-x** [comment]
freejavbt 上不是每部影片都有预告片
确认网站上有信息后再考虑 mdcx 问题
建议更换刮削来源
