### ISSUE TITLE
求一个简单的新功能：vr作品的水印

### ISSUE THREAD

**Issue by toobigpao** [sqzw-x/mdcx#53]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

本来今天自己想弄一下，又怕之后的某个版本突然有了，与我自己的魔改冲突，所以想先咨询下大大，将来会不会新增对vr作品的水印，如果有我就默默等待大大的官方版好了

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
不会
欢迎实现后 PR
