### ISSUE TITLE
读取模式或更新模式，没有完全重新整理目录结构的选项

### ISSUE THREAD

**Issue by mm519897405** [sqzw-x/mdcx#55]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

比如我之前的目录结构为：letters\number
现在我因为想区分码，我想修改目录结构为：mosaic\letters\number
因为之前所有数据都刮削好了，数据量很庞大，所以我不想再次刮削，所以选择了读取模式。
而读取模式对应选择的更新模式的三个模式，只更新C，更新B和C，创建D目录，似乎都不能很好的解决该问题
问题点：
1、必须把所有文件移动到根目录，然后再去执行更新模式才行。
2、如果我想增加更多的目录规则，似乎更新模式的也不行，因为更新模式只支持最多2个目录层级，比如我想根据nfo重新整理为：mosaic\cnword\letters\number，就需要执行两次更新才能达到这个效果。

### 如何复现

原结构：letters\number
希望结构：mosaic\letters\number
不刮削的情况下重整理

### 预期行为

可以不刮削的情况下，整理原有目录结构为预期目录结构

### 相关 Logs

```Text
无需LOG
```

**Comment by anyingxiuluo** [comment]
![微信截图_20240117143054](https://github.com/sqzw-x/mdcx/assets/125189022/da8e64f3-8003-4f30-8fca-e9d6ecbe8724)
这样设置就行了

**Comment by mm519897405** [comment]
> ![微信截图_20240117143054](https://private-user-images.githubusercontent.com/125189022/297281606-da8e64f3-8003-4f30-8fca-e9d6ecbe8724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzM4NzQsIm5iZiI6MTcwNTQ3MzU3NCwicGF0aCI6Ii8xMjUxODkwMjIvMjk3MjgxNjA2LWRhOGU2NGYzLTgwMDMtNGYzMC04ZmNhLWU5ZDZlY2JlODcyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwNjM5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGUyNTI0MjdlMmU2NTAzYzFlN2YwNzBkYjM2ZTA4NTNjMGE4MzU1ZDZjOTEzNWU2NTc2ZTRhZWNmOGYwZjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M3OiuNI2jA59btuuStz8XF6ioLz4fJ9IPY_T74pQDJQ) 这样设置就行了

妙啊,感谢大佬.
不过有一说一,这里的叙述真有点令人费解了,你发这个我也愣了一会才懂

**Comment by mm519897405** [comment]
> ![微信截图_20240117143054](https://private-user-images.githubusercontent.com/125189022/297281606-da8e64f3-8003-4f30-8fca-e9d6ecbe8724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzY4NzUsIm5iZiI6MTcwNTQ3NjU3NSwicGF0aCI6Ii8xMjUxODkwMjIvMjk3MjgxNjA2LWRhOGU2NGYzLTgwMDMtNGYzMC04ZmNhLWU5ZDZlY2JlODcyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwNzI5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjE0MmQwMmJmYTRiZWEzOGMyNTQzNzRlM2NhNjE5OWJhN2ZiZTQ5ZTVmZWNhZjIyMTFlZTVlNmM2ZmJmZDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QWU_5j0En32Y1-n623QvidJHWDIzrVAuybIAGVFJU6Y) 这样设置就行了

我测了下,还是没有完全解决,如果我本身是3级目录,要改成4级目录,就会出问题

**Comment by anyingxiuluo** [comment]
目录只会越刮越深，3级变4级可以，4级变不了3级

**Comment by mm519897405** [comment]
> 目录只会越刮越深，3级变4级可以，4级变不了3级

那我提的问题其实依然存在。

**Comment by sqzw-x** [comment]
> 目录只会越刮越深，3级变4级可以，4级变不了3级

可以. 将命名规则置空就会减少一级目录，也可以使用相对路径 `..` 以提升两级，以此类推

**Comment by sqzw-x** [comment]
> 原结构：letters\number
希望结构：mosaic\letters\number

选择 `更新B和C -> 同时更新A`
设置 `A=mosaic  B=letters/number`
即可

**Comment by sqzw-x** [comment]
此处的设计逻辑有一点绕，更新模式不是幂等操作，每次读入的 A B 一定是单级目录，但是可以写入多级或0级
