### ISSUE TITLE
配置文件修改问题

### ISSUE THREAD

**Issue by iamjimmycheng** [sqzw-x/mdcx#56]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

配置ini文件中有一行是fields_rule = del_actor,del_char,fc2_seller,；我理解应该是对应的功能是：当FC2无演员时，使用卖家名字作为演员名字。

因此，我想把国产影片检索不到演员时，用studio名字作为演员名字，尝试将此参数改为fields_rule = del_actor,del_char,guochan_studio

但实际并不起作用，程序启动以后，后面添加的参数就被自动删除了，我想问问，如果想要实现我要的功能，要怎么修改呢？

### 如何复现

1. 修改ini
2. 启动程序
3. 前面修改ini中的参数被自动删除
4. 出现问题

### 预期行为

希望把国产影片检索不到演员时，用studio名字作为演员名字

**Comment by sqzw-x** [comment]
程序没有提供这样的配置，你必须自己实现
