### ISSUE TITLE
我记得前任版本可以刮moodyz官网，现在是特意取消了还是什么？以后会加回来吗？

### ISSUE THREAD

**Issue by toobigpao** [sqzw-x/mdcx#57]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

rt
我记得前任版本可以刮moodyz官网，现在是特意取消了还是什么？以后会加回来吗？

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by anyingxiuluo** [comment]
的确是这样，同一个番号，我以前刮的是moodyz，现在刮是dmm了
![微信截图_20240119101105](https://github.com/sqzw-x/mdcx/assets/125189022/dbeeedf1-8445-46ce-9149-dae692448422)

**Comment by sqzw-x** [comment]
可以检查其它片商官网刮削功能，具体支持的网站及对应番号参考：
https://github.com/sqzw-x/mdcx/blob/a05cfe0e529a098ae86df73cc1830af92711c684/src/models/config/config_manual.py#L370-L402

这些网站用的同一套刮削逻辑，因为他们的网站结构是完全相同的，所以如果某个失效就意味着全部失效

**Comment by anyingxiuluo** [comment]
> 可以检查其它片商官网刮削功能，具体支持的网站及对应番号参考：
> 
> https://github.com/sqzw-x/mdcx/blob/a05cfe0e529a098ae86df73cc1830af92711c684/src/models/config/config_manual.py#L370-L402
> 
> 这些网站用的同一套刮削逻辑，因为他们的网站结构是完全相同的，所以如果某个失效就意味着全部失效

这些的确全都失效了，我试了ssis番号，也不能从s1s1s1网站刮削了
