### ISSUE TITLE
更新模式或者读取模式都无法重写nfo里的演员

### ISSUE THREAD

**Issue by RainwalkerDean** [sqzw-x/mdcx#59]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [x] 我正在使用最新版本

### 描述你的问题

想把nfo里的演员名改成中文

1、更新模式 更新模式规则”是“更新b和c”、“同时更新a目录”
2、读取模式，勾选【本地已刮削的文件，重新整理分类】和【重新翻译映射nfo的的信息】，“更新模式规则”是“更新b和c”、“同时更新a目录”

结果只会把a目录重命名，nfo里演员没变。 但我试了如果“翻译”那里的“简介”切换语言，“简介”是能响应改动的。

**Comment by RainwalkerDean** [comment]
@sqzw-x 我发现只要不勾选【nfo】【写入男女演员】就没有这个bug了。。。。

**Comment by sqzw-x** [comment]
其实 976ceeb 已经修了，还没发布
