### ISSUE TITLE
javbus刮削失败

### ISSUE THREAD

**Issue by godofworld** [sqzw-x/mdcx#6]
不知道是不是增加反爬，之前可以刮削javbus的图片，这几天就突然不行了，看日志并没有报错，很奇怪的问题，求解答

⏰ 20:36:06 🔎 请求 https://www.javbus.com/sivr-256
 ⏰ 20:36:07 ✅ 成功 https://www.javbus.com/sivr-256
 ⏰ 20:36:07 🔎 请求 https://www.google.com/searchbyimage?sbisrc=2&image_url=https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:36:09 ✅ 成功 https://www.google.com/searchbyimage?sbisrc=2&image_url=https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:36:09 🔎 请求 https://www.google.com/search?sca_esv=586607062&tbs=simg:CAQSswIJJNuOaA5VjpAapwILEKjU2AQaBAhDCBgMCxCwjKcIGjsKOQgEEhSjC6kW-hPXAaUK1xTJOoIGowbnFBobe3LnJ7ar3ep2hvqJj_1UxLAZPLLmIGCF1IOCSIAUwBAwLEI6u_1ggaCgoICAESBGpdjM4MCxCd7cEJGrkBCigKFXBvcm5vZ3JhcGhpYyBtYWdhemluZdqliPYDCwoJL20vMDR0NDk1CiMKD3dvbWVuJ3MgZXJvdGljYdqliPYDDAoKL20vMDI3eTE4dgokChBudWRlIHBob3RvZ3JhcGh52qWI9gMMCgovbS8wM2NyMHRnCiQKEXNleHVhbCBhdHRyYWN0aW9u2qWI9gMLCgkvbS8wMWRfbDAKHAoJZm9yIGFkdWx02qWI9gMLCgkvYS85M2N3X3kM,isz:m&q=vr+%E8%91%B5+s1&tbm=isch&sa=X&ved=2ahUKEwiRlL6r3uuCAxW0bPUHHZsLCJIQ2A4oAnoECAYQBA
 ⏰ 20:36:10 ✅ 成功 https://www.google.com/search?sca_esv=586607062&tbs=simg:CAQSswIJJNuOaA5VjpAapwILEKjU2AQaBAhDCBgMCxCwjKcIGjsKOQgEEhSjC6kW-hPXAaUK1xTJOoIGowbnFBobe3LnJ7ar3ep2hvqJj_1UxLAZPLLmIGCF1IOCSIAUwBAwLEI6u_1ggaCgoICAESBGpdjM4MCxCd7cEJGrkBCigKFXBvcm5vZ3JhcGhpYyBtYWdhemluZdqliPYDCwoJL20vMDR0NDk1CiMKD3dvbWVuJ3MgZXJvdGljYdqliPYDDAoKL20vMDI3eTE4dgokChBudWRlIHBob3RvZ3JhcGh52qWI9gMMCgovbS8wM2NyMHRnCiQKEXNleHVhbCBhdHRyYWN0aW9u2qWI9gMLCgkvbS8wMWRfbDAKHAoJZm9yIGFkdWx02qWI9gMLCgkvYS85M2N3X3kM,isz:m&q=vr+%E8%91%B5+s1&tbm=isch&sa=X&ved=2ahUKEwiRlL6r3uuCAxW0bPUHHZsLCJIQ2A4oAnoECAYQBA
 ⏰ 20:36:10 ⛑️ 检测链接 https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:36:11 ✅ 检测通过！返回大小(167154) https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:36:11 🔎 请求 https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:36:12 ✅ 成功 https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:36:13 🎉 All finished!!! Total 1 , Success 0 , Failed 1 
 ⏰ 20:38:59 🔎 请求 https://www.javbus.com/sivr-256
 ⏰ 20:39:00 ✅ 成功 https://www.javbus.com/sivr-256
 ⏰ 20:39:01 🔎 请求 https://www.google.com/searchbyimage?sbisrc=2&image_url=https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:39:04 ✅ 成功 https://www.google.com/searchbyimage?sbisrc=2&image_url=https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:39:04 🔎 请求 https://www.google.com/search?sca_esv=586607062&tbs=simg:CAQSswIJJNuOaA5VjpAapwILEKjU2AQaBAhDCBgMCxCwjKcIGjsKOQgEEhSjC6kW-hPXAaUK1xTJOoIGowbnFBobe3LnJ7ar3ep2hvqJj_1UxLAZPLLmIGCF1IOCSIAUwBAwLEI6u_1ggaCgoICAESBGpdjM4MCxCd7cEJGrkBCigKFXBvcm5vZ3JhcGhpYyBtYWdhemluZdqliPYDCwoJL20vMDR0NDk1CiMKD3dvbWVuJ3MgZXJvdGljYdqliPYDDAoKL20vMDI3eTE4dgokChBudWRlIHBob3RvZ3JhcGh52qWI9gMMCgovbS8wM2NyMHRnCiQKEXNleHVhbCBhdHRyYWN0aW9u2qWI9gMLCgkvbS8wMWRfbDAKHAoJZm9yIGFkdWx02qWI9gMLCgkvYS85M2N3X3kM,isz:m&q=vr+%E8%91%B5+s1&tbm=isch&sa=X&ved=2ahUKEwjyzO3-3uuCAxW0cvUHHexIBFsQ2A4oAnoECAcQBA
 ⏰ 20:39:11 ✅ 成功 https://www.google.com/search?sca_esv=586607062&tbs=simg:CAQSswIJJNuOaA5VjpAapwILEKjU2AQaBAhDCBgMCxCwjKcIGjsKOQgEEhSjC6kW-hPXAaUK1xTJOoIGowbnFBobe3LnJ7ar3ep2hvqJj_1UxLAZPLLmIGCF1IOCSIAUwBAwLEI6u_1ggaCgoICAESBGpdjM4MCxCd7cEJGrkBCigKFXBvcm5vZ3JhcGhpYyBtYWdhemluZdqliPYDCwoJL20vMDR0NDk1CiMKD3dvbWVuJ3MgZXJvdGljYdqliPYDDAoKL20vMDI3eTE4dgokChBudWRlIHBob3RvZ3JhcGh52qWI9gMMCgovbS8wM2NyMHRnCiQKEXNleHVhbCBhdHRyYWN0aW9u2qWI9gMLCgkvbS8wMWRfbDAKHAoJZm9yIGFkdWx02qWI9gMLCgkvYS85M2N3X3kM,isz:m&q=vr+%E8%91%B5+s1&tbm=isch&sa=X&ved=2ahUKEwjyzO3-3uuCAxW0cvUHHexIBFsQ2A4oAnoECAcQBA
 ⏰ 20:39:11 ⛑️ 检测链接 https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:39:12 ✅ 检测通过！返回大小(167154) https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:39:12 🔎 请求 https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:39:13 ✅ 成功 https://www.javbus.com/pics/cover/9oup_b.jpg
 ⏰ 20:39:14 🎉 All finished!!! Total 1 , Success 0 , Failed 1

**Comment by sqzw-x** [comment]
需要更多信息，这段日志没有异常，但是显示刮削失败。nfo是否正常生成？是否成功从其他来源获取图片？

**Comment by godofworld** [comment]
并没有生成nfo，最近用优先模式成功过1天，之后又莫名不行了，换了字段优先也不行，看日志都没问题结果就一直失败，真是头痛，需要我提交什么信息才能找到问题呢?

**Comment by sqzw-x** [comment]
传一下 `config.ini` 的 `website` 部分

**Comment by godofworld** [comment]
[website]
scrape_like = speed
website_single = javbus
website_youma = airav_cc,iqqtv,freejavbt,jav321,dmm,javbus,javlibrary,7mmtv,javdb,avsex,lulubar,airav,xcity,avsox
website_wuma = iqqtv,javbus,freejavbt,jav321,avsox,7mmtv,javdb,airav
website_suren = mgstage,avsex,jav321,freejavbt,7mmtv,javbus,javdb
website_fc2 = fc2,fc2club,fc2hub,freejavbt,7mmtv,javdb,avsox,airav
website_oumei = theporndb,javdb,javbus
website_guochan = madouqu,mdtv,cnmdb
whole_fields = outline,actor,thumb,release,tag,
none_fields = wanted,
website_set = official,
title_website = theporndb,mgstage,dmm,javbus,jav321,javlibrary
title_zh_website = airav_cc,iqqtv,avsex,lulubar
title_website_exclude = 
outline_website = theporndb,dmm,jav321
outline_zh_website = airav_cc,avsex,iqqtv,lulubar
outline_website_exclude = avsox,fc2club,javbus,javdb,javlibrary,freejavbt
actor_website = theporndb,javbus,javlibrary,javdb
actor_website_exclude = 
thumb_website = theporndb,javbus
thumb_website_exclude = javdb
poster_website = theporndb,avsex,javbus
poster_website_exclude = airav,fc2club,fc2hub,iqqtv,7mmtv,javlibrary,lulubar
extrafanart_website = javbus,freejavbt
extrafanart_website_exclude = airav,airav_cc,avsex,avsox,iqqtv,javlibrary,lulubar
trailer_website = freejavbt,mgstage,dmm
trailer_website_exclude = 7mmtv,lulubar
tag_website = javbus,freejavbt
tag_website_exclude = 
release_website = javbus,freejavbt,7mmtv
release_website_exclude = fc2club,fc2hub
runtime_website = javbus,freejavbt
runtime_website_exclude = airav,airav_cc,fc2,fc2club,fc2hub,lulubar
score_website = jav321,javlibrary,javdb
score_website_exclude = airav,airav_cc,avsex,avsox,7mmtv,fc2,fc2hub,iqqtv,javbus,xcity,lulubar
director_website = javbus,freejavbt
director_website_exclude = airav,airav_cc,avsex,avsox,fc2,fc2hub,iqqtv,jav321,mgstage,lulubar
series_website = javbus,freejavbt
series_website_exclude = airav,airav_cc,avsex,iqqtv,7mmtv,javlibrary,lulubar
studio_website = javbus,freejavbt
studio_website_exclude = avsex
publisher_website = javbus
publisher_website_exclude = airav,airav_cc,avsex,iqqtv,lulubar
wanted_website = javlibrary,javdb
translate_by = youdao,google,
deepl_key = 
title_language = jp
title_sehua = on
title_yesjav = off
title_translate = on
title_sehua_zh = on
outline_language = jp
outline_translate = on
outline_show = show_from,show_zh_jp,
actor_language = jp
actor_realname = on
actor_translate = on
tag_language = zh_cn
tag_translate = on
tag_include = actor,letters,series,studio,publisher,cnword,mosaic,definition,
director_language = jp
director_translate = on
series_language = jp
series_translate = on
studio_language = jp
studio_translate = on
publisher_language = jp
publisher_translate = on
nfo_include_new = sorttitle,originaltitle,title_cd,outline,plot_,originalplot,release_,releasedate,premiered,country,mpaa,customrating,year,runtime,wanted,score,criticrating,actor,director,series,tag,genre,series_set,studio,maker,publisher,label,poster,cover,trailer,website,
nfo_tagline = 发行日期 release
nfo_tag_series = 系列: series
nfo_tag_studio = 片商: studio
nfo_tag_publisher = 发行: publisher
# website: iqqtv, javbus, javdb, freejavbt, jav321, dmm, avsox, xcity, mgstage, fc2, fc2club, fc2hub, airav, javlibrary, mdtv

**Comment by zhaojifang** [comment]
JAVBUS现在好像不能使用美国节点，如果使用美国节点则需要账号登录。会不会是这个原因？
