### ISSUE TITLE
请教一下，如何能自动对“待刮削视频目录”进行刮削

### ISSUE THREAD

**Issue by fnscar** [sqzw-x/mdcx#62]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

设置-高级-自动刮削好像无效，依然只能手动点“开始”，刮削完就停了，目录内又有文件了还得手动点“开始”才开始刮削。

### 预期行为

想要每隔一段时间自动对“待刮削视频目录”开始刮削

**Comment by sqzw-x** [comment]
我本地测试正常，你再看下设置

**Comment by fnscar** [comment]
反复试了无数遍，在windows电脑上本地运行怎么都不行。。。
反而nas上docker可以循环自动刮削。算了放弃了。
谢谢大佬的帮助。
