### ISSUE TITLE
[功能请求] 能否不依赖 Emby / Jellyfin / kodi 等运行，简单地将头像下到视频文件夹内？

### ISSUE THREAD

**Issue by 921j** [sqzw-x/mdcx#64]
如题，现在很多文件管理器比如 Total Commander 或 Tablacus 通过它们的一些插件就能很好的管理并查看文件夹预览图，我只需要把头像放到以该演员名字命名的文件夹内，并将图片改名成 "Folder.jpg" 或 "Folder.png" 就可以了，效果如下：

![1](https://github.com/sqzw-x/mdcx/assets/29940386/b4235bab-f51f-4153-bc54-2ac000224b19)

所以我只需要一个能批量将本地或网络演员头像库内的头像要么按目录名称、要么按目录内视频文件番号下载或复制到对应演员文件夹下并重命名为“Folder.png”的工具，找了一大圈都没有，都只有补全 Emby / Jellyfin / kodi 元数据的功能，但却可以将封面或背景图这样处理，求一个也可以将头像下到视频文件夹的功能，谢谢！
1.如果是按番号匹配且目录内有多个番号视频，只需要成功匹配了一个就跳到下一个目录继续；
2.希望有跳过功能，因为我自己截了一些头像，感觉比头像库里的更真实一些，所以不需要覆盖。

**Comment by sqzw-x** [comment]
![image](https://github.com/sqzw-x/mdcx/assets/150016653/ee6d820e-4d89-4a26-9237-252e895b7644)
这个功能是否符合你的需求？

**Comment by 921j** [comment]
好像这些媒体管理软件都不会直接把演员头像保存在对应的演员文件夹下？
我的文件都是自己手动整理的，感觉这些媒体管理软件都不怎么直观方便，我是个简洁党，只要有正确的演员名和演员头像就够了，平时并不需要有那么详细的信息和标签，导入导入维护之类的太麻烦且繁琐，远不如 Total Commander 这些文件管理器可以直接预览复制删除粘贴等管理方便。
![2024-01-28_180816](https://github.com/sqzw-x/mdcx/assets/29940386/b0386c86-9808-41fc-bc55-cc66c3c5fc86)

**Comment by sqzw-x** [comment]
这个功能适用面太小了, 毕竟并不是所有人都会以演员为单位区分目录, 我无法预设用户的目录结构

**Comment by 921j** [comment]
一定要判断用户的目录结构吗？不能简单的根据目录下的番号下载或复制女演员头像吗？不需要判断目录名之类的行为，就像封面图背景图之类的。
其次我也不求自动重命名了，我自己可以批量重命名。
比如说软件自带的 “ 补全 Kodi / Plex / Jvedio ” 这一功能，一不支持本地头像库，二选择父文件夹就无效，能否先完善一下呢，只要能根据子目录内视频番号下载或复制演员头像到该目录就行，其他的我自己来。

**Comment by auroracamus** [comment]
> ![image](https://private-user-images.githubusercontent.com/150016653/300177283-ee6d820e-4d89-4a26-9237-252e895b7644.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDE2NDUsIm5iZiI6MTcwODQwMTM0NSwicGF0aCI6Ii8xNTAwMTY2NTMvMzAwMTc3MjgzLWVlNmQ4MjBlLTRkODktNGEyNi05MjM3LTI1MmU4OTViNzY0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQwMzU1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDVjYTE3OTU0N2Q1M2FmOGMzMThkM2Q1ZDAxZDQ2ZjI4ZDBlZjhkNzIzYzRkNTIxNTE4ODY2YmYyOGI2YjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PJOlaoppwr8RXm0sJyjZnGg_vkNhWBKnfWhA_k5FHkY) 这个功能是否符合你的需求？

这个功能似乎只能手动执行？能否让其在刮削时一并执行？
