### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by epubc** [sqzw-x/mdcx#67]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

I'm trying to edit the interface language to suit me, I have installed all the components but when I run it it gives me the following error:
----
```
C:\Users\epub\Downloads\Compressed\mdcx-120240119\mdcx-120240119>python main.py
Traceback (most recent call last):
  File "C:\Users\epub\Downloads\Compressed\mdcx-120240119\mdcx-120240119\main.py", line 13, in <module>
    from controllers.main_window.main_window import MyMAinWindow
ModuleNotFoundError: No module named 'controllers'
```
----
I also used the pip install controllers command to install but still got the above error

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
For powershell, run:
```
$env:PYTHONPATH = "$PWD\src"
```
If you use pycharm, just mark `./src` as source root
