### ISSUE TITLE
能添加https://javbooks.com/的支持么 很多都是从这里下载的

### ISSUE THREAD

**Issue by hanfenglong315** [sqzw-x/mdcx#68]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

能添加 https://javbooks.com/ 的支持么 很多都是从这里下载的  。为什么选择别的网站 刮取不成功呢。能添加https://javbooks.com/ 的支持么 很多都是从这里下载的

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
一般情况不考虑支持新网站
检查你的设置以及网络情况
