### ISSUE TITLE
文件清理规则问题

### ISSUE THREAD

**Issue by nxy1999** [sqzw-x/mdcx#69]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

文件目录清理时，没有走排除掉的目录，把路径下的文件全部删除了

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

不删除排除目录下的文件

**Comment by sqzw-x** [comment]
排除目录是哪个配置项？

**Comment by nxy1999** [comment]
> 排除目录是哪个配置项？

**Comment by nxy1999** [comment]
> 排除目录是哪个配置项？

刮削目录下的排除目录

**Comment by sqzw-x** [comment]
这个配置并未说明会影响文件清理。
文件清理的匹配对象是待刮削目录下所有的 **文件**，不会考虑其所在目录

**Comment by nxy1999** [comment]
> 这个配置并未说明会影响文件清理。 文件清理的匹配对象是待刮削目录下所有的 **文件**，不会考虑其所在目录

好吧
