### ISSUE TITLE
从 title 中移除 number

### ISSUE THREAD

**Issue by cougarzee** [sqzw-x/mdcx#70]
今天第一次使用20231014以後的新版本
但是發現 設置-命名內 "目录名字支持自定义。命名字段有： title （标题）" title這個內容
顯示為 "[番号]标题"
例如 [WZEN-050]禁止發售 03 建設公司OL 友美（22）
（我在翻譯里有設定標題顯示為繁體中文）
請問可以不要加上 [WZEN-050] 這樣的字樣嗎 
因為如果要顯示番號，自己可以去設定 number 這個參數
我自己的emby視頻標題是格式化為  number | title
現在標題還帶番號，變成還得再去移除 "title （标题）"參數帶的 "[番號]"這個內容
覺得有點多此一舉

以上建議，謝謝

**Comment by sqzw-x** [comment]
可以打开 `设置 - 高级 - 调试模式`，看看标题的来源
不同网站的标题格式不一样，有的可能带有番号，有的则没有，位置也不定，无法统一处理
如果你确定某个网站的标题全部具有 `[number]` 前缀, 可以反馈, 我看看能不能处理

**Comment by cougarzee** [comment]
您好

我的設置如附件
![2024-01-30_140139](https://github.com/sqzw-x/mdcx/assets/8738616/a2699393-b93f-4ce2-b020-2bbb624b4d4e)
![2024-01-30_140302](https://github.com/sqzw-x/mdcx/assets/8738616/f7a0d6b7-4adc-462d-b638-c1158b4a620b)

會提出這個問題，是因為我用120240127版本和202310141版本，在相同的設置下，刮削出來的結果略有出入。

120240127版本
![2024-01-30_142446](https://github.com/sqzw-x/mdcx/assets/8738616/8ba5ecc0-2f47-49f1-9fc2-8c3cc28483e2)

202310141版本
![2024-01-30_142702](https://github.com/sqzw-x/mdcx/assets/8738616/48afc805-8a3e-4ab6-b188-39c2181f1263)

若因為是資料源的問題非程式本身的問題，那就是我誤會了。
僅提出參考，謝謝

**Comment by sqzw-x** [comment]
下图来源是 iqqtv.
看了下 airavcc 的解析确实有问题, 估计是网站改版了, 已修复

**Comment by cougarzee** [comment]
了解 謝謝了 所以如果我想延續上一個版本刮削的結果 把 iqqtv放在 airavcc的前面 就可以了 對嗎

**Comment by sqzw-x** [comment]
是的
