### ISSUE TITLE
演员设置为日语但仍显示中文

### ISSUE THREAD

**Issue by cougarzee** [sqzw-x/mdcx#71]
在"設置-翻譯"裡，演員區塊 演員語言選定為日語，但是有些片子卻會選是演員的中文名稱
例如 WZEN-075 
演員是美咲かんな，但顯示"美咲佳奈"
請確認，謝謝

**Comment by sqzw-x** [comment]
同 #70, 说明具体的信息来源, 另外检查是否开启了 `使用演员映射表翻译演员`

**Comment by toobigpao** [comment]
这个应该不是翻译的问题，而是很多刮削源网站上，刮出来的就是繁体中文的演员名，即便不启用翻译也还是繁体中文，这个没办法
