### ISSUE TITLE
搜刮会把搜刮目录del掉和搜刮后权限问题

### ISSUE THREAD

**Issue by saz369** [sqzw-x/mdcx#76]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

1.搜刮失败后会把整个搜刮目录del掉
2.好像因为权限问题导致失败(旧版本没这个问题)
开始搜刮:
⏰ Start time: 2024-02-03 08:02:36
 🖥 Movie path: W:\JAV\分类\A-日本\working4
 🔎 Searching all videos, Please wait...
    Done!!! Found (1)! Skip successfully scraped (0) repeat softlink (0)! (0s) 　
 📺 Find 1 movies
 🕷 开启多线程，线程数量（1），线程延时（12）秒...
<font color="brown"> 🍯 间歇刮削 已启用，连续刮削 25 个文件后，将自动休息 302 秒...</font>
 🕷 08:02:36 开始刮削：1/1 4k2.com@cawd-636.mp4
Traceback (most recent call last):
  File "models\core\scraper.py", line 335, in _scrape_exec_thread
  File "models\core\scraper.py", line 247, in _scrape_one_file
  File "models\core\file.py", line 327, in move_other_file
PermissionError: [WinError 5] 拒绝访问。: 'W:/JAV/分类/A-日本/working4'
搜刮后整理
🍀 Folder done! (new)
 🍀 Thumb done! (kawaiikawaii)(0s) 
 🍀 Fanart done! (copy thumb)(0s)
 🍀 Poster done! (thumb right)(0s)
 🍀 Nfo done! (new)(0s)
Traceback (most recent call last):
  File "models\core\scraper.py", line 335, in _scrape_exec_thread
  File "models\core\scraper.py", line 247, in _scrape_one_file
  File "models\core\file.py", line 327, in move_other_file
PermissionError: [WinError 5] 拒绝访问。: 'W:/JAV/分类/A-日本/working4'

 🔴 [Failed] Reason: c1oreMain error: [WinError 5] 拒绝访问。: 'W:/JAV/分类/A-日本/working4'
 🔴 该问题为权限问题：请尝试以管理员身份运行，同时关闭其他正在运行的Python脚本！
 🔴 Move file to the failed folder!
 🙊 [Movie] W:\JAV\分类\A-日本\failed\4k2.com@cawd-636.mp4

失败后会导致整个搜刮目录del.

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
尝试使用管理员权限运行 mdcx, 不过后面移动文件成功了, 那可能是因为挂载工具的限制, 你这个 W 盘应该是挂载的网盘吧
整个目录删除应该是因为开启了清理空文件夹，我注意到你的失败目录不在刮削目录下，所以全部文件移动到失败目录后源目录被清理了, 可以关闭此选项或者关闭移动失败文件
