### ISSUE TITLE
字幕复制

### ISSUE THREAD

**Issue by PoiYuudachi** [sqzw-x/mdcx#77]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

在给已刮削的视频添加字幕时，复制的字幕全部都是0字节

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
本地无法复现。检查你的字幕文件目录，以及目录权限，以管理员身份启动重试
