### ISSUE TITLE
javdb 安卓端

### ISSUE THREAD

**Issue by wxhbts** [sqzw-x/mdcx#8]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

javdb 在安卓端能正常进入FC2的详情 不需要VIP

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

希望能支持

**Comment by wxhbts** [comment]
> 不清楚app的数据来源，或许可以抓包试一下

我测试了 能抓包  访问必须有 jdsignature 头 但是加密了 

搜索接口地址https://api.hechuangxinxi.xyz/api/v2/search?q=FC2-xxxxxx&from_recent=false&type=movie&movie_type=all&movie_sort_by=relevance&movie_filter_by=all&page=1&limit=24

**Comment by sqzw-x** [comment]
我怎么只能抓到访问api.liquidlink.cn，你是直接手机抓的吗

**Comment by wxhbts** [comment]
手机使用的是代理工具  不是设置wifi代理
