### ISSUE TITLE
DMM刮削失败

### ISSUE THREAD

**Issue by AceCandy** [sqzw-x/mdcx#80]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

指定使用dmm网站进行刮削，看日志里面的网址直接点开已经搜索到内容了，但是提示‘数据获取失败: 未找到数据’

### 相关 Logs

```Text
🙈 [Movie] F:\9kg-个人整理\chinaDB待整理\SDDE-642-C.mp4
 🚘 [Number] SDDE-642
 😸 [Note] You specified 「 dmm 」, some videos may not have results! 
 🌐 [website] dmm(1s)
    🌐 dmm
       搜索地址: https://www.dmm.co.jp/search/=/searchstr=sdde00642/sort=ranking/ 
       番号地址: https://tv.dmm.co.jp/list/?content=1sdde00642&i3_ref=search&i3_ord=1 
       数据获取失败: 未找到数据
 🔴 Data failed!(1s)
 🔴 [Failed] Reason: 数据获取失败: 未找到数据 
 🔴 Move file to the failed folder!
```

**Comment by ygt1233211** [comment]
请问是否能在指定网站搜刮的时候重新添加tv.dmm 因为大部分iv写真信息都在tv.dmm

**Comment by sqzw-x** [comment]
> 请问是否能在指定网站搜刮的时候重新添加tv.dmm 因为大部分iv写真信息都在tv.dmm

能否给出几个示例?
因为原来获取 tvdmm 是通过官方(?) api 而非爬取网页, 而这个 api 已经失效了. 如果确有必要我可以尝试重新实现

**Comment by ygt1233211** [comment]
> > 请问是否能在指定网站搜刮的时候重新添加tv.dmm 因为大部分iv写真信息都在tv.dmm
> 
> 能否给出几个示例? 因为原来获取 tvdmm 是通过官方(?) api 而非爬取网页, 而这个 api 已经失效了. 如果确有必要我可以尝试重新实现

例子是FTBD-042 
这个影片在dmm.co.jp搜索都没有结果 在dmm.com输入番号也没有结果 在dmm.com搜索主演的话 可以搜到在DMM TV里面的影片 链接直接跳转到TV（https://tv.dmm.com/vod/restrict/detail/?title=5533ftbd00042&season=5533ftbd00042）
正常搜刮会有时不成功 但指定影片网址搜刮可成功

**Comment by sqzw-x** [comment]
我测试了一下, 这个可以正常获取, 是通过 `tv.dmm.com`. 
36927a8 实际上只删除了 `tv.dmm.co.jp` 的请求, 如果正常刮削获取不到, 应该是网络不稳定导致的

**Comment by ygt1233211** [comment]
噢噢了解了 iv类影片不涉及tv.dmm.co.jp 不冲突

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年02月11日 21:50 |
| 收件人 | sqzw-x/mdcx ***@***.***> |
| 抄送人 | ygt1233211 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [sqzw-x/mdcx] DMM刮削失败 (Issue #80) |

我测试了一下, 这个可以正常获取, 是通过 tv.dmm.com.
36927a8 实际上只删除了 tv.dmm.co.jp 的请求, 如果正常刮削获取不到, 应该是网络不稳定导致的
