### ISSUE TITLE
群晖docker网盘挂载刮削无写入权限

### ISSUE THREAD

**Issue by luffycc** [sqzw-x/mdcx#85]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

群晖docker里刮削的时候显示创建文件夹失败，检查是否有写入权限，用的网盘挂载刮削的。。刮削设置的目的地都是在刮削网盘的目录里。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
权限问题和你使用的挂载工具有关。
一种变通的方式是创建指向网盘内视频的软链接，然后对软链接刮削
