### ISSUE TITLE
JAVDB网络连接错误

### ISSUE THREAD

**Issue by kiworets** [sqzw-x/mdcx#87]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

已经开启非日本代理的情况下，db站无论是在刮削、网络测试都无法连接。在浏览器中可以正常打开
日志中除了502也没有显示原因
上个作者的10月份与6月份版本也有一样的问题，我电脑上留存最老的是22年2月份的(AVDCx)，还能够正常访问db
使用 `curl_cffi`的其他库都可以正常访问，只有db有问题

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
❌ JavDb 连接失败！请检查网络或代理设置！ 502 https://javdb.com/v/D16Q5?locale=zh
```

### 截图

![d46be645191c9a18f93e400c9e43561](https://github.com/sqzw-x/mdcx/assets/159447343/4d467114-dcf3-47f2-8e11-3c158c61b73b)

**Comment by sqzw-x** [comment]
502 是服务器返回的错误码，一般来说是触发了反爬或者访问限制

**Comment by daiguaxiaobai** [comment]
db无法使用+1
试了一下从  MDCx-120231219  到今天最新发布多刮削不了


以前的  MDCx-win-20230212  正常刮削

**Comment by kiworets** [comment]
0220的版本可以刮削db了 感谢大大
