### ISSUE TITLE
请教下大佬，不知道能不能给一个下载预告片的清晰度选择选项 ^_^

### ISSUE THREAD

**Issue by pikachullk** [sqzw-x/mdcx#92]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

现在这个版本下载预告片清晰度往往选择了最低的那个，记得之前在群里和yoshiki大佬好像提过能不能优先下载清晰度更高的预告片，当时我记得是改过的~不知道是不是现版本又不一样了。
也有朋友是希望不要那么大的~不知道能不能直接给个选项让用户自己选择希望下载更大的预告片还是更小的~

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
预告片来源基本是dmm，但是下游网站引用的清晰度是不同的，应该只有直接从 dmm 才可以获取到各种清晰度的
换句话说你获取的预告片清晰度是和选择的刮削网站相关的，虽然理论上 dmm 都有，但是并不是所有时候都会去访问 dmm

**Comment by pikachullk** [comment]
只留DMM也是下载最低清晰度的。。。emmm
手动去dmm下载可以下载到的最清晰的....
