### ISSUE TITLE
Windows 7 兼容

### ISSUE THREAD

**Issue by qq707432712** [sqzw-x/mdcx#93]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

win7打开提示“出现了一个问题，导致程序停止正常工作,请关闭该程序。” 请大佬谅解还在使用win7的苦逼党

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
我没有 win7 环境，无法复现此问题。这个报错信息太少了，无法确定问题所在，你可以尝试从源代码运行

**Comment by qq707432712** [comment]
> 我没有win7环境，无法解决这个问题。
> 这个报错信息太少了，无法确定问题所在。
> 你可以尝试直接从源代码运行，这样或许可以搞清楚哪里不兼容

我就是一个小白 报错信息又没有错误代码什么的 想找找是什么问题都无从下手 之前那个大佬最后一个版本win7能正常运行 前段时间使用的时候软件提示有版本更新 点进去看见是您接手这个项目了

**Comment by qq707432712** [comment]
> https://send.portailpro.net/download/13f90d58df2726ff/#rOwFHkudmI5ipjr8s-FQjQ
> 
> 这是使用 python 3.8 构建的，你试一下

**Comment by qq707432712** [comment]
> > https://send.portailpro.net/download/13f90d58df2726ff/#rOwFHkudmI5ipjr8s-FQjQ
> > 这是使用 python 3.8 构建的，你试一下

好的 谢谢大佬

**Comment by sqzw-x** [comment]
https://send.portailpro.net/download/c583c8b663528362/#K50urq_HuCwv1Q7eTzmjQg

**Comment by qq707432712** [comment]
> https://send.portailpro.net/download/32148fc9ee3b8c0e/#Un0ZIMhBZrY4hWZDXXwHVg

感谢大佬的不放弃  这个版本win7可以正常运行了 谢谢大佬

**Comment by julyyy** [comment]
链接已过期，同求谢谢

**Comment by qq707432712** [comment]
邮箱 我发您

**Comment by julyyy** [comment]
***@***.***
谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月20日 10:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sqzw-x/mdcx] Windows 7 兼容 (Issue #93) |

邮箱 我发您

**Comment by qq707432712** [comment]
地址全是星号 您就把地址的前缀打出来 注明什么邮箱就行

**Comment by qq707432712** [comment]
地址全是星号 您把地址前缀打出来 注明是什么邮箱就行

**Comment by qq707432712** [comment]
只打地址前缀 注明什么邮箱

**Comment by qq707432712** [comment]
地址全是星号 只打地址前缀 注明是什么邮箱就行

**Comment by julyyy** [comment]
julyyy
163邮箱，谢谢
gmail也可以



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月20日 11:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sqzw-x/mdcx] Windows 7 兼容 (Issue #93) |

地址全是星号 您把地址前缀打出来 注明是什么邮箱就行

**Comment by qq707432712** [comment]
已发送Gmail  谷歌云盘链接

**Comment by julyyy** [comment]
gmail没收到。麻烦发一下163的谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月20日 11:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sqzw-x/mdcx] Windows 7 兼容 (Issue #93) |

已发送Gmail 谷歌云盘链接

**Comment by julyyy** [comment]
收到谢谢



---- 回复的原邮件 ----
| 发件人 | Natural ***@***.***> |
| 日期 | 2024年03月20日 12:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sqzw-x/mdcx] Windows 7 兼容 (Issue #93) |

链接已过期，同求谢谢

我fork的仓库 northsea4/mdcx Releases 会跟进发布win7版的exe（不过只是简单测试过，不确保一定可用），可以试试。

**Comment by braumhuang** [comment]
我fork了仓库[下载含有legacy](https://github.com/braumhuang/mdcx/releases)
发版是按照日期，其中包含原仓库这个日期之前的代码
