### ISSUE TITLE
建議對ABF系列優化

### ISSUE THREAD

**Issue by luckbli5234** [sqzw-x/mdcx#96]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

javdb中 ABF-XXX 被兩個片商所使用 常常刮到舊的 
EX:
https://javdb.com/v/E2yyJ0       
https://javdb.com/v/0X60

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

希望PRESTIGE社的優先順去能往前

**Comment by sqzw-x** [comment]
参考 #22 
理论上来说对某些番号做特判是可行的，不过增加了维护开销（现在的代码里已经充斥着特判了，其中很多都意义不明，估计只有原作者记得了）
另外一个问题是大部分网站在搜索页无法判断发行商，所以只能全部刮削然后筛选，这就要大改刮削器代码，不容易实现

**Comment by luckbli5234** [comment]
了解 謝謝各位
