### ISSUE TITLE
发现一个刮削可用的网站

### ISSUE THREAD

**Issue by windyhun** [sqzw-x/mdcx#99]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

https://db.msin.jp/
就是这个，我在图书馆找不到的信息（女优）这里找到了

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
非常感谢
